### ISSUE TITLE
Warlord's rule blinking frame stays behind

### ISSUE THREAD

**Issue by gillatine** [Dugy/Legend_of_the_Invincibles#101]
When unit with Warlord's rule ability moves after attack (Hit and run or Penetrate feature), blinking blue frame stays behind.
![image](https://user-images.githubusercontent.com/44468974/47501246-abca5900-d86d-11e8-9986-c0f924bfd56a.png)

BfW version 1.14.4

LotI downloaded 9/15/2018

**Comment by Dugy** [comment]
It's a bug in Wesnoth, report it to them.
