### ISSUE TITLE
<Invalid WML found> [micro_ai_fast] not supported

### ISSUE THREAD

**Issue by gillatine** [Dugy/Legend_of_the_Invincibles#102]
Right at the beginning of Despair scenario, this error appears.

BfW version 1.14.4

LotI downloaded 9/15/2018

**Comment by Dugy** [comment]
Please provide a save file that shows it when loaded.

**Comment by gillatine** [comment]
[LotI2-Epilogue.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/2514969/LotI2-Epilogue.gz)

**Comment by gillatine** [comment]
Now it says "<Warning>  [micro_ai] uses side=: side does not exist.". Although I am not sure I installed patch the right way. I just made exactly the same changes to files global_events.cfg and 01_Despair.cfg as you did. Should I download the whole package and install it instead ? I found more bugs but to report it and test it I would prefer more simple method.

**Comment by Dugy** [comment]
I did it wrong. Use the changes in commit e6db486 pertaining to that scenario.
