### ISSUE TITLE
Incorrectly calculating Hit and Run MP after attack

### ISSUE THREAD

**Issue by gillatine** [Dugy/Legend_of_the_Invincibles#103]
After attack should be 7 MP, but it is 4 MP. Take a look at the unit Aigalalis.

BfW version 1.14.4

LotI downloaded 9/15/2018

[LotI2-And Another Orcish Assault Turn 6_before_attack.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/2519060/LotI2-And.Another.Orcish.Assault.Turn.6_before_attack.gz)
[LotI2-And Another Orcish Assault Turn 6_after_attack.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/2519061/LotI2-And.Another.Orcish.Assault.Turn.6_after_attack.gz)

**Comment by Dugy** [comment]
I cannot load the save file.

**Comment by gillatine** [comment]
Right. It only happens if Aigalalis advances. Try with this save file
[LotI2-And Another Orcish Assault Turn 6.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/2522595/LotI2-And.Another.Orcish.Assault.Turn.6.gz)

**Comment by Dugy** [comment]
It seems that due to advancing, his items and advancements weren't in effect for a while, causing his remaining moves to be reduced to his temporary lowered max moves.

**Comment by gillatine** [comment]
Are you this fixed the problem ? It didn't for me.

**Comment by Dugy** [comment]
You have to restart the scenario to have it take effect.

**Comment by gillatine** [comment]
Restarted scenario, then restarted the game, then cleared cache and restarted the game. Same result :(

**Comment by Dugy** [comment]
Clearing cannot help with changes of this kind.

You mean that you restarted the scenario, fought the enemies again, got him in the position next to a weakened demon again, had him advance with the hit and run attack again and it happened again?

**Comment by gillatine** [comment]
No, I meant reloading the game, sorry. I thought scenario code and game save are independent.

**Comment by Dugy** [comment]
No. Once you start the scenario, all WML code except for unit types becomes a part of the save file and only the code from the save file is run. I have edited the code in the save file to investigate the problem and test the fix.

Some of the recent changes I have done are in lua, which isn't a part of the save file and simply reloading the save file is enough for the changes to apply. This is what could have confused you.

**Comment by gillatine** [comment]
I see. Thank you for explanation.
