### ISSUE TITLE
Unequipping unit in a recall list invokes unpredictable consequences

### ISSUE THREAD

**Issue by gillatine** [Dugy/Legend_of_the_Invincibles#106]
Resulting buggy behavior seems to be random. Once one of my units changed site and became enemy (unfortunately I don't have save faile for that), another time unit got duplicated. Take a look at Eloic in two save failes. I am not sure this behavior is related to unequipping unit on recall list but it is likely to be so in my opinion.
[LotI2-Where the Flames Freeze Turn 8.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/2519174/LotI2-Where.the.Flames.Freeze.Turn.8.gz)
[LotI2-Where the Flames Freeze Turn 9.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/2519176/LotI2-Where.the.Flames.Freeze.Turn.9.gz)

BfW version 1.14.4

LotI downloaded 9/15/2018

**Comment by Dugy** [comment]
This is a known bug, but I haven't been able to replicate it so far.

I can't load the save file.

**Comment by gillatine** [comment]
I downloaded both files and loaded it succesfully. Files should be OK. The only difference I noticed after download is that files have dots instead of spaces in their names.

I'll try to find exact action which invokes the problem maybe that will help you.

**Comment by Dugy** [comment]
The problem is different. I can read the save file code, but somehow, it doesn't load anything, just tries to open the scenario without any resources. I have found a way around it, though.

**Comment by Dugy** [comment]
Strange, now I can load it without problems and I did absolutely nothing.

I can see the duplicated unit, but I don't know how did the second one make it to the game. I can't find him on the recall list.

**Comment by gillatine** [comment]
I found how to reproduce this unit duplication:
1. Load LotI2-Where.the.Flames.Freeze.Turn.8.gz
2. right-click on Hare-al_Free -> Items -> Show items on units on the recall list
3. Select Rhugwyran_Titan then unequip all his items
4. Gryphon Rider Hare-al_Free instantly becomes Eloic_IceDragon

Hope that helps

**Comment by Dugy** [comment]
I was able to replicate it and I have a rough idea what could be going on.
