### ISSUE TITLE
lua.lua:699: attempt to index a nil value (field '?')

### ISSUE THREAD

**Issue by arobinson** [Dugy/Legend_of_the_Invincibles#109]
Error after killing Beelzebub with Krux:

20181027 12:02:53 error scripting/lua: ~add-ons/Legend_of_the_Invincibles/lua.lua:699: attempt to index a nil value (field '?')
stack traceback:
	~add-ons/Legend_of_the_Invincibles/lua.lua:699: in local 'cmd'
	lua/wml-utils.lua:145: in field 'handle_event_commands'
	lua/wml-flow.lua:6: in function <lua/wml-flow.lua:5>
	[C]: in field 'fire_event'
	lua/wml-tags.lua:153: in local 'cmd'
	lua/wml-utils.lua:145: in field 'handle_event_commands'
	lua/wml-flow.lua:6: in function <lua/wml-flow.lua:5>
20181027 12:02:53 error engine: Unit has too many (293) XP left; cascade leveling goes on still.

[LotI2-The Desert-Auto-Save24.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/2522076/LotI2-The.Desert-Auto-Save24.gz)

**Comment by Dugy** [comment]
It's in a piece of new code, not yet uploaded to the server. I have seen this one before, but I could not find a way to replicate it. Thanks.
