### ISSUE TITLE
Least unit ability takes precedence

### ISSUE THREAD

**Issue by gillatine** [Dugy/Legend_of_the_Invincibles#110]
In attached save file Beelzebub should take Frail tide (30, Gumbrul) and Despair (40, Aigalalis). Instead it takes Frail tide (15, Krux) and Despair (20, Krux). Should take maximum ability value of all surrounding units IMHO.
Also I suspect that same would be with Conviction ability but don't have suitable units at hand to test it.
[LotI2-Corrupted Town Turn 20.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/2525064/LotI2-Corrupted.Town.Turn.20.gz)

**Comment by matsjoyce** [comment]
This is a known occurrence and is a result of the way wesnoth applies abilities (highest takes precedence, so as these abilities are negative leaderships the lowest is selected). This means that it is not really fixable without a lot of hackery.

**Comment by Dugy** [comment]
You may report this to the wesnoth developers, there is no good way to work this around in add-on code.

**Comment by matsjoyce** [comment]
Unless we reimplement all the abilities in lua, which would be a PITA.

**Comment by Dugy** [comment]
I don't even know how that could be done with the current lua interface.
