### ISSUE TITLE
8_10_Ruins_of_Wesnoth leaders missing traits

### ISSUE THREAD

**Issue by dalong76** [Dugy/Legend_of_the_Invincibles#111]
In chapter 8 scenario 10_Ruins_of_Wesnoth, the demon leaders that appear after the start have no traits.

**Comment by Dugy** [comment]
Actually, there are no leaders in _Ruins of Wesnoth,_ the problem is in _Odd World_ as it was initially set.

**Comment by dalong76** [comment]
No, I really meant Ruins of Wesnoth. Two demon leaders spawn a couple turns in and recruit demons, but the leaders have no traits.

**Comment by Dugy** [comment]
Strange, by all means they are supposed to have traits. Can you please upload a save file? All my save files from that scenario are horribly obsolete.

**Comment by dalong76** [comment]
Start of scenario and mid scenario attached. It is possible (probable?) that the start of scenario one won't load properly for you because I'm playing with several experimental additions to LotI, and I'm running Wesnoth 1.12. I hope the mid scenario one loads.

[LotI2-Ruins_of_Wesnoth.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/2527254/LotI2-Ruins_of_Wesnoth.gz)
[LotI2-Ruins_of_Wesnoth-Auto-Save10.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/2527328/LotI2-Ruins_of_Wesnoth-Auto-Save10.gz)

**Comment by dalong76** [comment]
There is probably a better fix anyway - don't make them leaders. Just spawn x number of demons and bypass the recruiting concept. I'll see what I can do along those lines tomorrow.

**Comment by Dugy** [comment]
Nah, I can work around that strange traitless leader generation.
