### ISSUE TITLE
Nonterminal mercy not defined

### ISSUE THREAD

**Issue by arobinson** [Dugy/Legend_of_the_Invincibles#112]
![image](https://user-images.githubusercontent.com/93213/47692425-320ed400-dbbb-11e8-9e76-2587ff75c685.png)
[LotI2-Wasteland of Lost Eternity.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/2527807/LotI2-Wasteland.of.Lost.Eternity.gz)

Thanks so much for the fixes thus far. This one appears at the start of turn 1

**Comment by Dugy** [comment]
Okay, finally I have the error message that was failing to display because of #108  Thanks for reporting.
