### ISSUE TITLE
Demon leaders without traits in scenario 8_12

### ISSUE THREAD

**Issue by dalong76** [Dugy/Legend_of_the_Invincibles#114]
I believe scenario 8_12_Gladiatrix-The_Reckoning has the same problem as issue #111. However, I tried the same fix and it didn't fix it. Maybe demon infiltrators work differently?

**Comment by Dugy** [comment]
Did you try the same thing as 88d2391 rather than the first unsuccessful fix?

**Comment by dalong76** [comment]
Looking again, I left in the line `can_recruit=yes`. I will try without that.

**Comment by Dugy** [comment]
Removal of that line was the sole reason why all the rest was written.
