### ISSUE TITLE
FIX: spawned dwarves are costing upkeep despite showing trait loyal

### ISSUE THREAD

**Issue by RolandDH** [Dugy/Legend_of_the_Invincibles#123]
--- a/scenarios3/02b_Mining.cfg
+++ b/scenarios3/02b_Mining.cfg
@@ -266,12 +266,14
             [variables]
                 chapter=3
             [/variables]
+            upkeep=loyal
         [/unit]
         {GENERIC_UNIT 1 "Dwarvish Fighter LotI" 35 6}
         [+unit]
             [variables]
                 chapter=3
             [/variables]
+            upkeep=loyal
         [/unit]
         {GENERIC_UNIT 1 "Dwarvish Fighter LotI" 36 7}
         [+unit]
@@ -281,6 +283,7 @@
             [variables]
                 chapter=3
             [/variables]
+            upkeep=loyal
         [/unit]
         {UPDATE_ATTACKS 38 6}
         {UPDATE_ATTACKS 35 6}

**Comment by Dugy** [comment]
It appears to be a bug in Wesnoth 1.14, but it is not fixable for them without causing OoS errors. This workaround fixes it well enough.
