### ISSUE TITLE
Incinerate is not applied to already poisoned unit

### ISSUE THREAD

**Issue by edwardspec** [Dugy/Legend_of_the_Invincibles#126]
Save file is attached. [incinerate-poisoned-target.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/2603829/incinerate-poisoned-target.gz)

Demigod unit has Entropy attack with "incinerate" weapon special.
If she attacks a poisoned Shadow Hound (present on the map), the Shadow Hound won't become incinerated. On the next turn, affected Shadow Hound will only take 8 damage.

In case this matters, Entropy has both "poison" and "incinerate" weapon specials, and "incinerate" was unlocked earlier than "poison".

**Comment by Dugy** [comment]
I loaded your save file and the enemy attacked by the _entropy_ attack was incinerated, I have seen both the change of colour and the status icon. He was under the effect of some healing ability, which has removed the incineration.
