### ISSUE TITLE
Please add COPYING file

### ISSUE THREAD

**Issue by edwardspec** [Dugy/Legend_of_the_Invincibles#139]
Could you please add a license file? Something that allows modifications, like GPL or MIT.
(Wesnoth itself is GPL 2.0+)

Technically it's not a free software without it.

**Comment by matsjoyce** [comment]
Or `LICENCE`. Not sure about the convention. Note that this code is on the addon server, and so "must be licensed under a version of the GNU GPL" (https://wiki.wesnoth.org/Wesnoth:Copyrights#User_Made_Content_-_Code). Not sure how that fares legally though.
