### ISSUE TITLE
Gather ideas on inventory screen UI (items currently on the unit)

### ISSUE THREAD

**Issue by edwardspec** [Dugy/Legend_of_the_Invincibles#145]
I was thinking about improving the Items menu.
(only currently equipped items, not the item storage)

At the very least we can add things like "Sword: [none]" for not-yet-equipped (but possible to carry) items. I mentioned this in #136.

But we might as well draw a full-scale inventory dialog (as in many RPGs), with clickable images of weapon, armour, gauntlets, etc.
Click on a sword slot will open an item storage menu with items of "sword" type. (where the item can be selected in one click, one of the options will be "Unequip")

Each slot will show the name and icon of the currently equipped item. (or, if no item is equipped, "[no gauntlets]" label and placeholder image)
Details can either be in a tooltip (but we need a fallback, since Wesnoth is played on mobile devices), or written below the icon, or can be shown when you click on the item. (having "Keep current item: [...description...]" as one of the options in the "change item" menu)

**Comment by edwardspec** [comment]
![inventory1a](https://user-images.githubusercontent.com/1163218/50049044-8bd84880-00ec-11e9-9767-e4c3dcd27ee7.jpg)
![inventory1b](https://user-images.githubusercontent.com/1163218/50049046-8e3aa280-00ec-11e9-88cc-479c8d324cfa.jpg)
![inventory1-unequipped](https://user-images.githubusercontent.com/1163218/50049047-9266c000-00ec-11e9-851a-7df0dfd74d02.jpg)
![inventory1-3weapons](https://user-images.githubusercontent.com/1163218/50049048-94c91a00-00ec-11e9-9ff5-d92770531e97.jpg)
![inventory1-bat](https://user-images.githubusercontent.com/1163218/50049051-97c40a80-00ec-11e9-8db6-b110581eb9ba.jpg)

**Comment by edwardspec** [comment]
Non-weapons are always displayed in fixed positions.
Weapons are displayed to the right and to the left, but rgw exact type of equippable weapon is shown.

The inventory has 3 or 4 rows. Most units will have 3 rows in their inventory.
If the unit has 3 weapons or a leftover item (e.g. sword on a Dragon Rider - from the time when it was a Knight), additional fourth row appears.

**Comment by edwardspec** [comment]
Non-weapons are always displayed in fixed positions.
Weapons are displayed to the right and to the left, but the exact type of equippable weapon is shown.

The inventory has 3 or 4 rows. Most units will have 3 rows in their inventory.
If the unit has 3 weapons or a leftover item (e.g. sword on a Dragon Rider - from the time when it was a Knight), additional fourth row appears.

**Comment by Dugy** [comment]
I don't think it's possible to implement any kind of item dragging, so an itemised view would not be useful for inventory manipulation.

That is why I suggested to place them in a selectable list like those redeem advancements.

**Comment by edwardspec** [comment]
> it's impossible to show item properties when hovering the mouse over the items.

... the said item storage menu will show two additional pseudo-items (on the very top):

1) Unequip
2) Keep current item: [... here is the list of item properties ...]

**Comment by Dugy** [comment]
They are buttons? Well, I guess it could work then.

**Comment by edwardspec** [comment]
They are.
Their clickability may not be evident from the sketch above, but if we draw a background for them that looks like a button...

**Comment by Dugy** [comment]
Yeah, good idea.

**Comment by edwardspec** [comment]
To avoid extra clicks, menu items like "Unit information", "Pick up items on the ground", etc. will become buttons at the bottom of the inventory dialog.

Just opening inventory (and not doing anything in it) will no longer prevent Undo (`[set_menu_item]` will have `synced=no`, because nothing in its contents will be changing the game state). Lua will use `wesnoth.synchronize_choice()` where needed.

**Comment by edwardspec** [comment]
My preliminary idea for Tutorial is to have a global variable in Lua, e.g. `inventory_config`.
It will store callbacks for events like "slot_clicked(sword)".

Default callback will do what it should (in case of clicking on the sword - open the item storage with swords),
but some scenario (such as Tutorial) could replace this callback with its own - the one that would instead show some message. (unit's sarcastic comment on why noone takes his diamond encrusted family sword from him)

Another callback can return the list of menu items that are needed. Default callback will return all of them, the one redefined by Tutorial will exclude things like "Disable retaliation attacks".

**Comment by Dugy** [comment]
I think that optional arguments would be better than global variables. Global variables are a bad practice that should be used only if necessary, i.e. keeping some data cached (it cannot be done differently here).

Otherwise I think it should work this way.

**Comment by edwardspec** [comment]
Update on UI:
![inventory2](https://user-images.githubusercontent.com/1163218/50201251-5b054700-036a-11e9-80ee-2ccd7a6fae00.jpg)

**Comment by edwardspec** [comment]
... those buttons even animate when hovering/pressing.
Had to make a custom widget for that (via `wesnoth.add_widget_definition()`).

**Comment by matsjoyce** [comment]
This is looking pretty good now! Some suggestions (feel free to ignore if they can't be done):

 - Center the icon buttons 
![image](https://user-images.githubusercontent.com/6631310/50212874-0bc41400-0374-11e9-8742-367541787dbd.png)
 - Move the close button to the bottom right, as that is where people expect it to be.
 - Add more spacing between the left buttons and the slots.
 - Does it show information about all equipped items anywhere, as it is useful to see how items interact, especially as part of sets. Maybe we could adapt the unit information screen to show which items contribute to what or something like that.

**Comment by Dugy** [comment]
@edwardspec That UI now looks pretty usable.

You can center the widgets by placing spacers before and after them. The spacers will adjust their size to make it fit.

I however don't think there's a good way to center the icons if the original images aren't centered or to enforce equal width of the columns.

**Comment by edwardspec** [comment]
> Move the close button to the bottom right, as that is where people expect it to be.

Done.

> Add more spacing between the left buttons and the slots.

Done.

> I however don't think there's a good way to center the icons if the original images aren't centered 

Indeed, if the item picture itself has 30px of empty space to the right and 5px of space to the left, our code won't even know that it's not centered.

> to enforce equal width of the columns.

This should be possible by making "slot button + label below it" into a custom widget (subtype of `[panel]`), and then enforcing a fixed width. Investigating.

**Comment by edwardspec** [comment]
> Does it show information about all equipped items anywhere,
> as it is useful to see how items interact, especially as part of sets.

It's in brainstorming phase of development.

Properties of 1 item will be shown when clicking on it, as "Current item: [... here are the properties ...]" above the displayed Item Storage section.

Not sure about "properties of all items in one place". Can add this to unit information screen, or can make its own screen just for that (+1 button to left menu of Inventory screen).

**Comment by edwardspec** [comment]
Short-term plan on left menu buttons:

1) "Crafting", "Unit information" and "Pick up items on the ground": no immediate changes (will just open those screens, same as now). They can be improved later (e.g. Crafting could use some GUI), but it is not necessary to do it BEFORE the rollout of the new inventory.

2) "Item storage" screen: will reimplement via Lua. Because new inventory will directly interact with it.

3) "Select weapons for retaliation": will reimplement as a dialog that shows checkboxes near attack names. No more "Enable N/Disable N" menus. This screen will also show a help message "why is this needed" (example with berserker, example with knight, example with leeching attack).

4) "Unequip (store) all items": will ask "Are you sure?", then unequip them via Lua. This shouldn't leave the Inventory screen.

5) "Items on units on the recall list": when player chooses the unit from the list, we might as well display this unit in the Inventory dialog.

6) Overall: status of some buttons can be changed depending on the situation. For example:
a) "Pick up items on the ground" button may be inactive if unit isn't standing on any items or when viewing a unit on recall list,
b) "Unequip (store) all items" button may be inactive if unit doesn't have any.
c) "Select weapons for retaliation" button may be highlighted (e.g. asterisk or red font) if there are currently enabled limitations. A player may forget to turn off "no retaliation" mode.

**Comment by Dugy** [comment]
Seems fine for me.

**Comment by edwardspec** [comment]
> to enforce equal width of the columns

Done.
Even "Ancient Armour of the Power of the Ancients" fits on the screen, and the dialog is not too large.
![inventory3a](https://user-images.githubusercontent.com/1163218/50254421-052eae80-03ff-11e9-8202-ef5a908c4e6a.jpg)
![inventory3b](https://user-images.githubusercontent.com/1163218/50254424-07910880-03ff-11e9-964f-cf09cdc3aaf5.jpg)

**Comment by Dugy** [comment]
Nice job. Meanwhile, I am still struggling with getting the lua version of stats.cfg to work.

**Comment by edwardspec** [comment]
If you need help with stats.cfg, let me know.
I just wrote a Lua function where I need to call "update stats" - https://github.com/edwardspec/Legend_of_the_Invincibles/commit/66db308c476d5d65919da5239083647da5853828 - left this as TODO comment for now (just `wesnoth.fire_event("update_stats", x, y)` doesn't do the trick).

**Comment by Dugy** [comment]
I was able to deal with the problems, I am in the final phase of testing the rewrite of stats.cfg at the moment.

The new way to call it will be simply `local updated = wesnoth.update_stats(unit)`.

**Comment by Dugy** [comment]
I have committed the new lua implementation of the update_stats code. A lot of stuff should be now easier to do from lua, but there might be some errors I failed to find.

**Comment by edwardspec** [comment]
Update on UI (item storage):

![item_storage1](https://user-images.githubusercontent.com/1163218/50403967-06bbf600-07b4-11e9-8ca9-34ee6fbdfb92.jpg)
![item_storage2](https://user-images.githubusercontent.com/1163218/50403966-06235f80-07b4-11e9-8335-6f70e5099cdc.jpg)

**Comment by edwardspec** [comment]
"Select weapons for retaliation" dialog:
![retaliation1](https://user-images.githubusercontent.com/1163218/50404024-7631e580-07b4-11e9-828f-97feb9d5acde.jpg)

**Comment by Dugy** [comment]
Very good.

Just the attack disabling window should have a bar - instead of an x between damage and attack count, for conformity with other panels.

I'd be glad if the disabled attacks were identified by some better way than their position on the list, but I have no concrete ideas how could it be done. Writing this just so that you might happen to have a better idea.

**Comment by edwardspec** [comment]
> I'd be glad if the disabled attacks were identified by some better way than their position on the list

We can use the attack name (e.g. `unit.attacks[2].name`) in Lua, because it's not translatable and doesn't change when you equip an item.
For example, for an archer with Fine Bow, `attack.name="bow"` and `attack.description=_"Fine Bow"`.

**Comment by Dugy** [comment]
The attack's name isn't unique, unfortunately. Maybe if there was the attack's name _and_ the index number of the attack with such a name, it could be enough.

**Comment by edwardspec** [comment]
> The attack's name isn't unique

How many units have several attacks with the same name?
Maybe we can just change attack name in them to be unique.

**Comment by Dugy** [comment]
Orcish Archer line, Halberdier... there are mainline units among them and replacing them is error prone.

**Comment by edwardspec** [comment]
Replacing them _manually_ is error-prone.

But `update_stats()` is called in "unit placed" event for every unit on the map (even mainline units), operates on WML array of unit, and can rename the duplicate names of attacks in this WML array (if any) - for example, add consecutive numbers to them (second "bow" of Orcish Archer becomes "bow2").

**Comment by Dugy** [comment]
Yeah, that could work. Great idea.

**Comment by edwardspec** [comment]
Header of the inventory dialog now shows name and type of the unit. (like the "Unit information" screen, but more compact)

"Items on units on the recall list":
![recall-list-items](https://user-images.githubusercontent.com/1163218/50427464-10c81c80-08ba-11e9-9af1-43f42a165fed.jpg)

"View" button opens inventory of selected unit in the usual interface.
![recall-list-view](https://user-images.githubusercontent.com/1163218/50427469-2a696400-08ba-11e9-997c-0fff85526924.jpg)

Units on the recall list can't perform operations that require taking a new item. For simplicity (to not add various checks like "can unit A drop the item to the ground" to the code) and because it would be illogical (how would they take an item from units on the battlefield when they are absent from the battlefield?).
![storage-no-equip](https://user-images.githubusercontent.com/1163218/50427503-3e619580-08bb-11e9-8de0-4eee5b33beed.jpg)

**Comment by Dugy** [comment]
Nice work.

The list of units on recall list contains lines that are too long. This problem wasn't solvable with WML-based UI, but with lua, it can be dealt with. Of course, it's not essential and I can change it once you're done with this, without having to alter other components of the code.

The `update_stats()` function should work on units on the recall list. If it doesn't, then it's a bug.

The leftover items have become some sort of feature now. It was once an oversight, but I wasn't fixing it for long because the way it was written in WML made the code impossible for reuse at checking which items should be removed - which is no longer an issue now. On the other hand, I feel it adds a lot of possibilities at developing units, which is a good thing. I think that there are even some items made specifically to be used as leftover items, but they can be changed to be used as stat sticks. I am giving you a free hand on this.

If you need some advice on the remaining things, feel free to ask.

**Comment by edwardspec** [comment]
> The update_stats() function should work on units on the recall list. If it doesn't, then it's a bug.

Submitted issue #165.

**Comment by edwardspec** [comment]
> handle the "leftover item" slots somehow.

Done. Item storage when viewing a leftover item (and trying to unequip it):
![unequip-leftover](https://user-images.githubusercontent.com/1163218/50459308-fdc95100-097a-11e9-86bc-c826447efeea.jpg)

**Comment by Dugy** [comment]
I have implemented the crafting window and committed it into master. It allows creating items and transmuting gems. It does not fit into your item framework very well (mainly because I was working on master), so feel free to change it in any way to suit your needs. You also seem to be more skilled with the GUI system than I am.

**Comment by edwardspec** [comment]
Question: is there any non-bug situation when `loti.item.type[number]` may be called with non-existent item number?
I added `helper.wml_error` (basically an exception) there as a typo-catcher (suppose a wrong item number is added into some code, with wml_error this will be noticed and reported, but with "return nil" it gets silently ignored and we'll never know about the problem). Also shorter code due to less if-s, because return value is always valid.

**Comment by edwardspec** [comment]
> ```for i = word_from, word_to do local item = loti.item.type[i]```

I'll provide a method to find type IDs between A and B.

**Comment by Dugy** [comment]
That is also a possibility.

**Comment by dalong76** [comment]
Dugy, the new crafting window is cool ... except it truncates lines that explain what the items do.
![image](https://user-images.githubusercontent.com/26093847/50527757-f0fa4980-0aaf-11e9-82fd-bdb7fde91832.png)

**Comment by edwardspec** [comment]
I'll have a look at it.

**Comment by edwardspec** [comment]
@dalong76 It's possible that #186 already fixed it. Can you please check?
`git fetch origin pull/186/head:crafting && git checkout crafting`

**Comment by Dugy** [comment]
I fixed it in 8a583b6

**Comment by edwardspec** [comment]
> I was placing the item to the ground and firing item_pick event, it works just fine
> [...]
> which leads to accumulation of old items on the ground

Here is a better idea (clicking Equip would immediately equip without the item_pick menu):
![equip-dropdown](https://user-images.githubusercontent.com/1163218/50528694-dac8a980-0b00-11e9-87c4-a45e3de885b0.jpg)
![equip-dropdown2](https://user-images.githubusercontent.com/1163218/50528697-e025f400-0b00-11e9-9a19-36edd89b969d.jpg)

Those dropdown options would act as buttons (when they are clicked, the item is dropped or destroyed)

**Comment by Dugy** [comment]
Yes, it could be better than the current approach.

**Comment by dalong76** [comment]
Sometimes a unit does not get the GEARED trait when picking up an item.

![image](https://user-images.githubusercontent.com/26093847/50529073-e17efe80-0ab7-11e9-86cf-498de09b6051.png)

**Comment by Dugy** [comment]
I have fixed that problem. I don't know why did you post it here.

**Comment by edwardspec** [comment]
Cool thing is, `set_dialog_tooltip()` was recently implemented in Wesnoth - https://github.com/wesnoth/wesnoth/issues/3692
It's unclear if it will be in Wesnoth 1.14, but here is how Inventory dialog will look when running in Wesnoth that supports it:

![tooltip-item](https://user-images.githubusercontent.com/1163218/50553111-15714400-0cb1-11e9-8749-ce8a8db289f2.jpg)

**Comment by edwardspec** [comment]
... or a smaller tooltip:
![small-tooltip](https://user-images.githubusercontent.com/1163218/50553740-c7af0880-0cbd-11e9-8d8b-53f6062c9767.jpg)

**Comment by Dugy** [comment]
I didn't know such a feature was added. It's veeeery handy in this case.

Please make sure it won't cause crashes on 1.14, supporting the stable versions is essential.

**Comment by edwardspec** [comment]
Current status: everything in Inventory dialog works (the only TODO thing is Tutorial),
however I plan to do some refactoring:
1) it looks like tooltips (with item descriptions) can be shown even without set_dialog_tooltip() (e.g. would work even in Wesnoth 1.14), just by passing them as tooltip= parameter when opening the dialog.
2) code can be simplified by having all [button]s close the dialog (have return_value) and immediately reopen it when needed. In current implementation, the Inventory dialog is a multi-tab widget, and some buttons use goto_tab() instead of closing it. It works correctly, but there is no real benefit and the code can be shorter without this. (currently some buttons close the dialog, some don't close it, and some close and reopen, and also it can be closed by Enter/Escape - four different types of handling. Can be replaced with just one `if ret == ... elseif ret == ...` on the value returned by `open_dialog()`).

**Comment by Dugy** [comment]
That's not what is called refactoring, but I support your plan to make those changes.

**Comment by edwardspec** [comment]
Replacing already working code with better code is exactly what is called refactoring.

**Comment by Dugy** [comment]
It depends on other conditions. Refactoring is when those changes make the code more cleaner. However, this is not the case. You are changing the way it works. In that case, it's called _reengineering._

**Comment by edwardspec** [comment]
Closing as resolved, as the inventory dialog has been merged into master.
