### ISSUE TITLE
Parry always has one attack

### ISSUE THREAD

**Issue by arodiss** [Dugy/Legend_of_the_Invincibles#15]
First of all thank you for creating (and supporting!) this awesome piece of campaign.

I noticed that whatever unit get an advancement "can attack while parrying enemy blows" (I tried with Forester and Delly Start) this attack always has only 1 hit, which of course substantially reduces it's usability.
Finally, in generated docs https://wiki.wesnoth.org/LotI_Unit_Advancements it is always said something like "10 more attacks for ..." - it took me ages to figure out that this is actually 10%

LoTI 3.1.23, Wesnoth 1.12.5

**Comment by matsjoyce** [comment]
The wiki bug is now fixed. @Dugy I'll have the generation script updates at https://gist.github.com/matsjoyce/bd13afe1a50882436103a2f506991f3d if you want to use that as a link on the forum topic instead of the zip file.

**Comment by arodiss** [comment]
Sorry for misreport - there is no bug in parry, just it by default has 70% less attacks.
Ie you if you have 6 basic attacks or less you will get only 1 parrying attack
