### ISSUE TITLE
Elvish Juggernaut has unlabeled AMLA

### ISSUE THREAD

**Issue by arodiss** [Dugy/Legend_of_the_Invincibles#16]
I noticed that in list of AMLAs available for Elvish Juggernaut there is an item with same icon as sword but no label.
When I will encounter it next time I will specify what the effect is

LoTI 3.1.23, Wesnoth 1.12.5, English interface

**Comment by Dugy** [comment]
I think I was fixing it before. Have you seen it on the version downloaded from here (not from the add-on server)?

**Comment by arodiss** [comment]
@Dugy 
I will check with master version and report the result

**Comment by arodiss** [comment]
@Dugy 
Problem reproduces with latest version

**Comment by Dugy** [comment]
I was not able to replicate it. It can only be the mayhem weapon special (nothing else has the same icon), but there is no missing text.
