### ISSUE TITLE
call_event_on_unit() tries to modify unit.id, which is a readonly field

### ISSUE THREAD

**Issue by edwardspec** [Dugy/Legend_of_the_Invincibles#161]
In Gladiators:
```
$ wesnoth.update_stats(wesnoth.get_unit(24,4))
Lua Error:
  When executing, Lua runtime error: ~add-ons/Legend_of_the_Invincibles/lua/stats.lua:21: bad argument #2 to '__newindex' (unknown modifiable property of unit: id)
stack traceback:
	[C]: in metamethod '__newindex'
	~add-ons/Legend_of_the_Invincibles/lua/stats.lua:21: in function '.call_event_on_unit'
	~add-ons/Legend_of_the_Invincibles/lua/stats.lua:38: in field 'update_stats'
	[string "ilua._pretty_print(wesnoth.update_stats(wesno..."]:1: in main chunk
```

This probably needs wesnoth.copy_unit() or something.

**Comment by Dugy** [comment]
You must call it on a variable of type `WML table` representing a unit, not on a variable of type `unit`. You have to convert it using a `.__cfg` call, for example using `wesnoth.update_stats(wesnoth.get_unit{id="moderator"}.__cfg)`.

**Comment by edwardspec** [comment]
Confirming that is works.
My code (in not yet committed `lua/items.lua` - utilities like "put item 123 onto `unit`") operates on `unit` variables directly (without temporary copies), so I used
```lua
wesnoth.put_unit(wesnoth.update_stats(unit.__cfg))
```
... to update the unit on the map.
