### ISSUE TITLE
Uneqiping items from unit in recall list does not work as intended

### ISSUE THREAD

**Issue by arodiss** [Dugy/Legend_of_the_Invincibles#17]
"Items" menu -> "Show items on units in recall list" -> Select unit -> "Unequip all items" -> recall unit afterwards

Upon doing this unit has no items visible in "items" menu, but item effects are still there (ie attacks have special names, damage and resistance modifications are applied etc)

LoTI 3.1.23, Wesnoth 1.12.5

**Comment by Dugy** [comment]
This has already been reported on the forums.

**Comment by arodiss** [comment]
OK, close as duplicate
