### ISSUE TITLE
Dwarves no longer get legacy advacements

### ISSUE THREAD

**Issue by arobinson** [Dugy/Legend_of_the_Invincibles#173]
After updating to the latest git version, the dwarven units no longer get legacy options.

[LotI2-The Den of Evil Turn 5.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/2712993/LotI2-The.Den.of.Evil.Turn.5.gz)

**Comment by edwardspec** [comment]
Old `stats.cfg` had some code related to legacies, it seems to be missing in `stats.lua`.
All units are affected (not just dwarves).

**Comment by Dugy** [comment]
I have moved the legacy-related code into another file. I want to have the lua code capable to work with completely different WML code and the legacies looked very much like something that should be tweakable.
