### ISSUE TITLE
Lua error with equipping crafted item

### ISSUE THREAD

**Issue by arobinson** [Dugy/Legend_of_the_Invincibles#175]
[LotI2-Arctic Wastelands-Auto-Save62.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/2713437/LotI2-Arctic.Wastelands-Auto-Save62.gz)

![screen shot 2018-12-27 at 2 51 41 pm](https://user-images.githubusercontent.com/93213/50495554-12dbc980-09e7-11e9-92f1-c01243950c4e.png)

Error happened after trying to craft and equip "lightning agility" boots for Tede (the faerie incarnation). The bug causes the unit to be deleted from the game.

**Comment by arobinson** [comment]
To reproduce:

1. Load the save game
2. Right-click on the Faerie
3. Craft an item
4. Choose Lightning Agility
5. Make them Boots
6. Equip them
7. Error happens and the Faerie is deleted

**Comment by Dugy** [comment]
Funny, the bug was there for years and didn't manifest before because of WML's weak typing.
