### ISSUE TITLE
Lua error with defense still occurs

### ISSUE THREAD

**Issue by arobinson** [Dugy/Legend_of_the_Invincibles#178]
I'm still having the lua error with the "defence" variable

![screen shot 2018-12-28 at 9 00 23 am](https://user-images.githubusercontent.com/93213/50520714-11f67680-0a7f-11e9-8336-68999f39d6bc.png)

To reproduce, load this save game and then just end the turn:
[LotI2-The Den of Evil Turn 8.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/2715188/LotI2-The.Den.of.Evil.Turn.8.gz)

**Comment by Dugy** [comment]
You are using the same old bugged version like before. The problem was _not_ in the lua file, but in items.cfg and your save file contains the old, unchanged version.

**Comment by arobinson** [comment]
Thanks, I'll try to restart the scenario to see if that works
