### ISSUE TITLE
Crafting with new dialog does not work

### ISSUE THREAD

**Issue by arobinson** [Dugy/Legend_of_the_Invincibles#179]
[LotI2-The Den of Evil Turn 1.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/2715246/LotI2-The.Den.of.Evil.Turn.1.gz)

Right-click the faerie
Select Items
Select Crafting
Select Armor>Boots>Lightning Agility
Click Craft
Click Yes

Gems are reduced, but the item is never created or equipped

**Comment by arobinson** [comment]
BTW, Works fine if done with the Champion with the same item.

**Comment by edwardspec** [comment]
@Dugy I will investigate this.

**Comment by Dugy** [comment]
@edwardspec Nah, I have already found it. It's simply that the event isn't fired, the item was under the unit.

**Comment by edwardspec** [comment]
Ok.

**Comment by Dugy** [comment]
The problem is that once I pick it, a strange error appears.
