### ISSUE TITLE
Cannot do multi-turn moves

### ISSUE THREAD

**Issue by arobinson** [Dugy/Legend_of_the_Invincibles#182]
Not sure if this has anything to do with this extension, but I think something has changed in the last couple of weeks that I can recall. If you give a command to a unit for multiple turns (move more than one turn away), the unit does not perform that action the next turn. It is almost as if the unit is being changed out every turn.

**Comment by Dugy** [comment]
Didn't inventory manipulation do this like always?

Considering the depth of the recent changes, it is entirely possible that this is my fault. It may be happening that all units are being updated as if their inventories were manipulated every turn (and the significant increase in efficiency makes it invisible).

I will need to investigate whether `update_stats()` isn't called more often than it should.

**Comment by edwardspec** [comment]
Can probably just remember/restore `unit.__cfg.goto_x`, `unit.__cfg.goto_y` in update_stats().

**Comment by Dugy** [comment]
That would hide the problem, but `update_stats()` would still be called too often.

Thanks for telling that I forgot to keep these two properties, though.

**Comment by Dugy** [comment]
Fixed the problem that manifested and also the problem that the function was called too often.
