### ISSUE TITLE
Elvish overlord no longer animates on webbed sword strike

### ISSUE THREAD

**Issue by arobinson** [Dugy/Legend_of_the_Invincibles#184]
[LotI2-Avengers-Auto-Save7.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/2715447/LotI2-Avengers-Auto-Save7.gz)

Attack the daemon Fala with Panar, the Elvish Overlord with the webbed sword strike. He attacks and deals damage, but never moves or animates

**Comment by arobinson** [comment]
Looks like it is affecting multiple units, like the animation speed is off as there seems to be a flicker of movement

**Comment by Dugy** [comment]
It seems that bonus attacks aren't always receiving proper animations. I will look at it.

**Comment by Dugy** [comment]
I had to fix three bugs to get this working.
