### ISSUE TITLE
Level up allows attacking again

### ISSUE THREAD

**Issue by dalong76** [Dugy/Legend_of_the_Invincibles#187]
If a unit levels up while attacking, it can immediately attack again.

**Comment by dalong76** [comment]
If a unit levels up while attacking, it can immediately attack again.

**Comment by Dugy** [comment]
I cannot replicate it.

**Comment by edwardspec** [comment]
There was such problem in the past, but not anymore.
Some recent change must have fixed it.

**Comment by dalong76** [comment]
Fixed by other fixes.
