### ISSUE TITLE
Gold dropped at end of scenario lost

### ISSUE THREAD

**Issue by dalong76** [Dugy/Legend_of_the_Invincibles#188]
If the final leader that triggers the end of a scenario drops gold, the gold goes into the item storage, but can never come out.

**Comment by Dugy** [comment]
You cannot just take it out of the item storage and walk over it?

**Comment by Dugy** [comment]
Gold isn't listed as an item type when the items are sorted into types, so the gold is retrievable only if there is less than 20 items in the storage.

Shall we fix this now or with the rewrite of the inventory system?

**Comment by edwardspec** [comment]
Rather than showing gold in storage, let's make sure it never gets added to storage.
INSERT_INTO_ITEMS macro can call loti.storage.add(), which can check if the item is gold (and handle it accordingly).

**Comment by Dugy** [comment]
That could be a good approach.

**Comment by edwardspec** [comment]
Resolved by #205.
