### ISSUE TITLE
Scythemaster Trickery AMLA increases attacks by percentage

### ISSUE THREAD

**Issue by IamTechknow** [Dugy/Legend_of_the_Invincibles#2]
The Scythemaster trickery AMLA is suppose to increase the number of attacks for the trickery attack but it does not appear to do so. I spent 2 AMLAs to see if it would change and it did not. I looked into my save file and found the number of attacks is 2.4 (1 from Fiery blood gauntlets) so with 2 AMLA the attacks are increased by 20%). Since trickery starts with 1 attack, shouldn't an AMLA add 1 more attack instead?

**Comment by Dugy** [comment]
When the trickery attack is gained, it has 50% less attacks. Each trickery improvement adds 10%, so if you have them all, it has 20% less attacks. This applies to the attack after being modified by all weapon properties. There may be some rounding on the way, I am not sure how this is done.

**Comment by IamTechknow** [comment]
I did some testing with the debugging features and yes I think I better understand it now. Given enough AMLAs and attacks added by gear, it is possible to get another attack for trickery but never more than whirlwind/impale. The number of attacks is rounded down.

**Comment by Dugy** [comment]
Wesnoth always rounds down unless the number is between 0 and 1, then it rounds up.

Are you saying that now it makes sense and there's no bug?

**Comment by IamTechknow** [comment]
I think it does make sense and is balanced, but the wording of the trickery AMLA could be improved. "Confusing enemies more often" implies more attacks, and the more AMLAs I put into it the more attacks I expected, but I put three AMLAs in before I noticed I wasn't quite sure it does what it says. Perhaps "Confusing enemies as often as impale/whirlwind"?

**Comment by Dugy** [comment]
The number of attacks of other depends on other stuff. Trickery will not have the same number of attacks than whirlwind if whirlwind is upgraded. I suggest something like 'Attacking more times with the confusing attack'.

**Comment by IamTechknow** [comment]
I think the statement should say the unit can attack more often but it probably won't happen right away. How about "Able to attack more times with the confusing attack" or "Able to confuse enemies more often"?

**Comment by Dugy** [comment]
_Able to attack more times with the confusing attack_ sounds the best. I will make the change if there are no objections.

**Comment by Dugy** [comment]
Done.
