### ISSUE TITLE
Crafting window issues

### ISSUE THREAD

**Issue by dalong76** [Dugy/Legend_of_the_Invincibles#206]
Maybe you already know this, but there are still problems with the new crafting window. This is based off pulling the latest github last night. It sometimes doesn't do line returns when it should and it doesn't list some features of items. Examples:

![image](https://user-images.githubusercontent.com/26093847/50598034-13ed7a80-0e6f-11e9-8e56-53b0650984b9.png)
The amount of fire resist is off the screen. It also doesn't attempt to list Murderlust or cold resist. Similar issues exist for other items.

Also notice the odd scroll bar problem, if I switch to armour view. The armour vs weapon box is super tiny, with a tiny scroll bar. If I click armour, it won't resize the window, so it is impossible to select type of armour. It restores if I exit crafting and go back in.

**Comment by edwardspec** [comment]
Investigating.

**Comment by edwardspec** [comment]
I fixed truncated description of items. Please try it now.

> if I switch to armour view. The armour vs weapon box is super tiny, with a tiny scroll bar

Doesn''t happen for me.
Anyway, I adjusted some widths/margins in the dialog, so please check if it's a problem.

**Comment by Dugy** [comment]
What OS are you using, edwardspec?

I am using Ubuntu 18.04 and it behaved exactly as dalong76 screenshotted.

**Comment by edwardspec** [comment]
Ok, rather than tweaking this 3-column build (which we can do endlessly with imperfect results), let's make Armour/Weapon into buttons (not listbox),
and move item description (which can be wide) below the columns 1 and 2. (gem stats will collapse into a rather thin column 3, leaving a lot of space for type and recipe listboxes in columns 1-2)

**Comment by Dugy** [comment]
I was thinking about placing weapon-armour selection, description and requirements into column 1, item sort into column 2 and recipe into column 3, but your idea might be better actually.

**Comment by edwardspec** [comment]
I rearranged the Crafting dialog to minimize resizing of widgets.

@dalong76 @arobinson Please try it out.

**Comment by Dugy** [comment]
Now the weapons/armour choice is too shrunk when armour is selected.

**Comment by edwardspec** [comment]
This is how it looks for me (in different screen resolutions):
1366x690: ![1](https://user-images.githubusercontent.com/1163218/50625036-47470c80-0f36-11e9-952e-997bbb9ebb85.jpg)

800x600: ![2](https://user-images.githubusercontent.com/1163218/50625041-49a96680-0f36-11e9-86f6-801530bcd428.jpg)

Switching between Armour/Weapon, or between recipes, or between types doesn't cause any glitches.
Maybe it only occurs at large screen resolutions? I'm testing on a notebook.

**Comment by dalong76** [comment]
Now, when I first load the crafting window, on armour, it looks okay. Switch to Weapons and it still looks okay. Basically just like edwardspec posted. But switch back to armour, and it messes up.
![image](https://user-images.githubusercontent.com/26093847/50640846-b4a17000-0f2b-11e9-9ab2-f9ed973a1100.png)

Maybe if the item list has a smaller vertical area initially and thus a permanent vertical scroll bar?

PS This really proves why my job is embedded software - I don't like doing GUIs. :)

**Comment by edwardspec** [comment]
> Maybe if the item list has [...] a permanent vertical scroll bar?

Does the following change help?
```patch
--- a/lua/crafting.lua
+++ b/lua/crafting.lua
@@ -344,6 +344,7 @@ loti.gem.get_crafting_dialog = function()
 
        local recipe_listbox = wml.tag.listbox {
                id = "gui_recipe_chosen",
+               vertical_scrollbar_mode = "always",
                wml.tag.list_definition {
                        wml.tag.row {
                                wml.tag.column {
```

**Comment by Dugy** [comment]
There is also `wesnoth.set_dialog_canvas()` which might do it, but everything I tried with it caused the game to crash with assertion failed.

**Comment by edwardspec** [comment]
No need to look into set_dialog_canvas(), it doesn't affect positioning or size of elements in any way.

**Comment by Dugy** [comment]
I thought it would cause the GUI to redraw.

**Comment by dalong76** [comment]
vertical_scrollbar_mode = "always" did not work for me. When I click 'weapons', no items appear - left column is empty.

**Comment by arobinson** [comment]
Only issue I see is when selecting a weapon, the Armor/Weapon buttons are truncated with and they have a scrollbar

![screen shot 2019-01-03 at 8 06 13 pm](https://user-images.githubusercontent.com/93213/50672081-206af380-0f93-11e9-8fdc-9a17712306ed.png)

**Comment by dalong76** [comment]
That is working for me.
I do suggest a slight wording change though - for the helm/boots/gauntlets, instead of saying "1/3 of promised resistances", it should say "1/3 physical resistance". The first implies the 1/3 applies to everything, but really the 1/3 applies only to "Increases physical resistances by X"

**Comment by Dugy** [comment]
That wording can be removed, my new `loti.item.describe_item()` function takes it into consideration.

I just don't want to edit `crafting.cfg` right now due to concerns about merge conflicts.

**Comment by edwardspec** [comment]
Here we go (boots are selected, so item description shows "physical resistances" bonus of 5% - if armour is chosen, it will be 15%):
![1](https://user-images.githubusercontent.com/1163218/50707228-30f19b80-1071-11e9-9f38-781434d1c569.jpg)

**Comment by Dugy** [comment]
That seems to work, but the bad thing is that the upper block for selecting armour and weapons is compressed to half of its horizontal size, with a slider on the right.

I think the only feasible solution to this is to put there three columns, with these contents:
1. item type, recipe properties gem quantities
2. recipes
3. base type

**Comment by edwardspec** [comment]
> upper block for selecting armour and weapons is compressed to half of its vertical size

Should be fixed if we replace horizontal_listbox with two buttons.

**Comment by Dugy** [comment]
The lower listbox for selecting weapon types is in my opinion unnecessarily small and its items have different widths.

**Comment by edwardspec** [comment]
Well, feel free to experiment.

>  everything I tried with it caused the game to crash with assertion failed.

One simple rule to avoid that: grid must have same number of columns in each rows.

If you need first row to have 2 columns A, B and second row to have 3 columns C, D, E, then make two additional grids:
grid K will have 1 row and 2 columns A, B,
grid L will have 1 row and 3 columns C, D, E.

Then the main grid would have two rows with 1 column each. K will be in one cell, L in another cell.

**Comment by Dugy** [comment]
Does it work now? For me, there are no problems, besides that it isn't arrayed exactly in the most logical way.

**Comment by edwardspec** [comment]
Seems to be resolved.
