### ISSUE TITLE
Leadership level 6 on level 5 friend

### ISSUE THREAD

**Issue by dalong76** [Dugy/Legend_of_the_Invincibles#207]
Under the new definition, a level 5 unit (Duke) with leadership level 6, provides no bonus to a friendly level 5 unit (Dragon Rider). That seems wrong to me.

**Comment by dalong76** [comment]
I'm pretty sure that fix is incorrect. You put
`formula="level < " + {LEVEL}`
I think the answer is:
`formula="other.level < {LEVEL}"`

Before posting this, I tried fixing it myself and failed, so I submitted it. But I must have done something wrong 4 hours ago because the above works for me now. I'm going to submit it.

**Comment by edwardspec** [comment]
> formula="level < " + {LEVEL}

This also works, WML concatenates "level < " and {LEVEL} as strings.

**Comment by edwardspec** [comment]
> I'm pretty sure that fix is incorrect.

It's not. Name `other` within [filter_adjacent] refers to the unit with leadership.
See ABILITY_LEADERSHIP macro in Wesnoth: https://github.com/wesnoth/wesnoth/blob/1340c005b3beb992aef09a86bf2c7d62862bcef7/data/core/macros/abilities.cfg#L114

**Comment by edwardspec** [comment]
> I'm pretty sure that fix is incorrect.

It's not. Name `other` within [filter_adjacent] refers to the unit with leadership.
See ABILITY_LEADERSHIP macro in Wesnoth: https://github.com/wesnoth/wesnoth/blob/1340c005b3beb992aef09a86bf2c7d62862bcef7/data/core/macros/abilities.cfg#L114

**Comment by edwardspec** [comment]
@Dugy please double-check this.

**Comment by Dugy** [comment]
I am getting the item description generating function to work, I don't want to make too much magic with my repository right now. I should finish it tonight.

**Comment by dalong76** [comment]
Okay, my formula is definitely wrong. It applies negative damage to higher level units because the filter is checking the leader level.

I apologize for committing bad code.

**Comment by edwardspec** [comment]
Seems to work correctly, so closing as resolved.
