### ISSUE TITLE
Absorb AMLA does not work

### ISSUE THREAD

**Issue by arodiss** [Dugy/Legend_of_the_Invincibles#21]
When I give Lethalia / Efraim Lich / God absorbs AMLA ("able to heal from enemy attacks" / "heals from enemy attacks better"), it is shown in "unit information" screen, but is not actually working

LoTI 3.1.23, Wesnoth 1.12.5

**Comment by Dugy** [comment]
I have seen that ability work this week.

**Comment by arodiss** [comment]
@Dugy 
I expect this ability to do following:
- Hero is hit
- Red number with damage is shown
- **Green number 1 is shown** (on first level)

This last thing for sure does not happen. Maybe actually heal is applied, I did not check it.
Am I wrong about how does this work?
Also please notice that I am using somewhat not latest version

**Comment by Dugy** [comment]
I haven't been changing that part of code for years, so it's unlikely that the version is the problem.

I have observed the green number 1 this week. I may retest it if you are so certain that it does not appear while it should.

**Comment by arodiss** [comment]
@Dugy 
Here is the screencast: https://www.youtube.com/watch?v=vG8vq1Yl4IA&feature=youtu.be
(notice that Efraim has leeching ability and that's why have green **3**, this has nothing to do with absorb)

**Comment by Dugy** [comment]
I will check it out. Maybe I was observing leech before and thought it was absorb.

**Comment by arodiss** [comment]
thank you

**Comment by Dugy** [comment]
I have tested it. Absorb does not show any healing visual effect (intentionally disabled, probably to prevent the healing sound from becoming annoying), but the resulting hitpoints were correct.
