### ISSUE TITLE
Automatic update on the addon server?

### ISSUE THREAD

**Issue by edwardspec** [Dugy/Legend_of_the_Invincibles#211]
How inconvenient is it to upload new versions to addon server manually?

We can make a "stable" branch, and have Travis script upload new versions to addon server automatically (when new commits appear on "stable" branch).

So when "master" branch gets merged into "stable", it would be uploaded to addon server as a new version.
Also important bugfixes can be cherry-picked into "stable" branch, if the master branch is not yet stable enough.

**Comment by Dugy** [comment]
Uploading it is easy, but I don't update more often because the add-on is quite large, would be downloaded by a lot of players and the server's bandwidth is limited.

A problem with automatic uploading is that the upload is, as far as I remember, done by a piece of C++ code that is pretty hard to emulate in a script. Furthermore, this is a public repository and putting a script here would make the script public, allowing anyone to upload the campaign to the server.

**Comment by edwardspec** [comment]
If the server's bandwidth is indeed limited, then I agree that releases shouldn't be frequent.
In case in the future the bandwidth situation changes, note that there are no technical problems:

1) Wesnoth has a command-line tool (written in Python) that can upload the addon: https://github.com/wesnoth/wesnoth/blob/master/data/tools/wesnoth_addon_manager
2) Passkey for uploading can be written into configuration file in encrypted form (Travis will decrypt it using the key noone knows). https://docs.travis-ci.com/user/encryption-keys/

**Comment by Dugy** [comment]
I don't know what is the situation right now. But as a consumer I hate when stuff updates often.

Wesnoth used to have an alternative add-on server that could be used to upload testing versions, but it's not running any more. I propose to create a new add-on called _LotI dialy builds_ or something that would be updated more often, it should satisfy all possibilities.

**Comment by edwardspec** [comment]
> daily builds

Good idea.
No Travis is even needed, you can just use wesnoth_addon_manager in crontab.

**Comment by matsjoyce** [comment]
Well, Travis is better as it doesn't depend on any particular machine.

**Comment by Dugy** [comment]
Also, often a week passes and no commits are made. I'd also prefer using travis over crontab. However, unlike crontab, I have no idea how travis is used (not that I am good at using crontab).

**Comment by konecnyjakub** [comment]
@Dugy Looks like Travis can run builds at scheduled intervals: https://docs.travis-ci.com/user/cron-jobs/. Also if you want to keep your passphrase hidden, you can entry it in the repository's settings on Travis: https://docs.travis-ci.com/user/environment-variables/#defining-variables-in-repository-settings.

**Comment by edwardspec** [comment]
Added a preliminary script that does this. (see the comment in `.travis.yml` for details).

How to enable:
1) login to Travis and turn "on-off switch" on https://travis-ci.org/account/repositories near the repository:
![travis-enable](https://user-images.githubusercontent.com/1163218/51068809-7b0beb80-1634-11e9-8056-3f76cb7a52c4.png)

2) Visit https://travis-ci.org/Dugy/Legend_of_the_Invincibles/settings
- 2a) in section "Environment Variables", add variable called PBL_PASSPHRASE (with correct value). This variable is not public. Furthermore, Travis won't use it when checking pull requests.
- 2b) in section "Cron Jobs", add the following job: Branch: master, Inverval: monthly, Options: Always run.

3) Add _server.pbl (**without the passphrase= line**) to the repository.

4) Double-check that it works.

**Comment by Dugy** [comment]
I have some difficulties with that.

1. How does it know it has to add the contents of PBL_PASSPHRASE to the _server.pbl file?
2. Is there a way to do it without adding a _server.pbl file to the repository? The file is only for use by travis, I don't want it to ever make it into my local repo (as it would cause me to accidentally publish the beta version).
3. How do I check it works?

Just in case, here is the the _server.pbl file:
```
title="Legend of the Invincibles"
type="campaign"
icon="misc/blank-hex.png~BLIT(units/elves-wood/sorceress-melee-attack-6.png~RC(magenta>black)~CROP(20,0,52,72),0,0)~BLIT(halo/undead/idle-flash-6.png~CROP(30,20,62,72),0,0)~BLIT(halo/elven/elven-shield-halo-60pct.png~CROP(64,64,72,72),0,0)~BLIT(halo/elven/druid-healing4.png~CROP(20,20,72,72)~O(70%),0,0)~BLIT(halo/elven/druid-healing5.png~CROP(0,0,62,62)~O(40%),10,10)~BLIT(halo/elven/druid-healing5.png~CROP(0,0,52,52)~O(40%),20,20)~BLIT(halo/elven/druid-healing2.png~O(40%)~CS(200,-200,-200)~CROP(5,5,57,37),5,35)~BLIT(units/human-outlaws/assassin-melee-2-1.png~RC(magenta>black)~CROP(0,0,67,62)~BLIT(units/human-loyalists/master-at-arms-melee-1-1.png~CROP(11,1,10,20)~FL(horizontal),27,16)~BLIT(halo/elven/druid-healing6.png~O(40%)~CS(200,-200,-200)~CROP(5,15,57,37),0,25)~BLIT(halo/undead/idle-flash-7.png~CS(50,-50,-50)~CROP(10,0,62,62),0,0),5,10)~BLIT(halo/elven/druid-healing4.png~CROP(0,0,62,62)~O(30%),10,10)~BLIT(halo/elven/druid-healing5.png~CROP(0,0,52,52)~O(60%),20,20)~BLIT(projectiles/dagger-ne.png~CROP(25,25,22,22)~FL(vert)~O(30%),44,40)~BLIT(projectiles/dagger-ne.png~CROP(25,25,22,22)~FL(vert)~O(50%),47,45)~BLIT(projectiles/dagger-ne.png~CROP(25,25,22,22)~FL(vert),50,50)"
version="3.2.4c"
author="Dugi"
passphrase=REDACTED
description="Sometimes, people don't embrace the tempting powers of darkness because of desires to rule, but merely for survival. Can the dark powers be used to fight against dark schemes with no limits or will they eventually corrupt its users?

A massive 200 scenarios long campaign divided into 2 parts, each of them consisting of five substories. The chapters offer a varied character development and changing strategies throughout. Although preserving the traditional Wesnoth gameplay, there are also many powerful items to collect, as well as a level-up system for all units that goes beyond the L3 limit. Your recalls will be all the more unique and fun to use due to the many power-ups obtained throughout this campaign.

Also contains two coop multiplayer scenarios related to the campaign.

The campaign has two spin-offs, 'The Beautiful Child' and 'Affably Evil'. The campaign 'Kill the King' is also related."
email=REDACTED
translate=yes
[feedback]
    topic_id=32384
[/feedback]
```

**Comment by edwardspec** [comment]
> How does it know it has to add the contents of PBL_PASSPHRASE to the _server.pbl file?

When Travis runs the script (`.travis.yml`), it places the value of this into $PBL_PASSPHRASE variable.

We then pass parameter `--pbl-key passphrase $PBL_PASSPHRASE` to `wesnoth_addon_manager`.
This causes `wesnoth_addon_manager` to ignore "passphrase" key from _server.pbl and instead use the value of $PBL_PASSPHRASE. (which is the real passphrase)

> Is there a way to do it without adding a _server.pbl file to the repository? 

Yes, we can name this file differently (e.g. `beta.pbl`),
and then pass `--pbl beta.pbl` as parameter to `wesnoth_addon_manager`.

> How do I check it works?

Wait 24 hours (since it's a daily cron task),
then check https://travis-ci.org/Dugy/Legend_of_the_Invincibles/builds - logs of recent builds.

It would look something like this - https://travis-ci.org/edwardspec/Legend_of_the_Invincibles/builds/478648892 - except `after_success` line in the end (which was skipped in this example, because no PBL_PASSPHRASE was defined and it wasn't a cron build).

**Comment by edwardspec** [comment]
Added `beta.pbl`.
Note that email is also skipped and should be defined as PBL_EMAIL in the same manner as PBL_PASSPHRASE (in Travis settings).

**Comment by edwardspec** [comment]
Success: https://travis-ci.org/Dugy/Legend_of_the_Invincibles/jobs/478775878
Relevant lines in the log:
```
Setting environment variables from repository settings
$ export PBL_PASSPHRASE=[secure]
$ export PBL_EMAIL=[secure]
[...]
Opening socket to add-ons.wesnoth.org:15014 for 1.14.x
Connected as 42.
Adding directory Legend_of_the_Invincibles_beta as Legend_of_the_Invincibles_beta.
Receiving 55 bytes.
Received 55 bytes.
('Ignored file', 'beta.pbl')
55/55
Add-on accepted.
Closing socket.
```

Result:
![uploaded](https://user-images.githubusercontent.com/1163218/51075764-281c4d80-16a1-11e9-8aa8-090c9c64a06e.jpg)

**Comment by matsjoyce** [comment]
You could set the version number to be the output of [`git describe HEAD`](https://git-scm.com/docs/git-describe), that way people can see which commit they are on and the version number will increase when updated.

**Comment by edwardspec** [comment]
> I was expecting there was some trick to wait for a cron task without waiting for 24 hours.

I allowed manually triggered builds ("More options" menu -> "Trigger build" on https://travis-ci.org/Dugy/Legend_of_the_Invincibles) to upload the addon the same way as cron tasks.

This only happens when "Trigger build" is explicitly used in Travis by someone who has commit access. cron-invoked builds do the same thing, so they should also work.

**Comment by Dugy** [comment]
By the way, why is the automatically uploaded beta so much larger?

**Comment by edwardspec** [comment]
Unknown. Downloaded both and "diff -r" shows they are the same (aside from version in _info.cfg).
Probably different compression/encoding are used in wesnoth_addon_manager.

**Comment by Dugy** [comment]
Could be. The one in travis might be using something lighter on the CPU.

**Comment by Dugy** [comment]
Okay, then.

**Comment by edwardspec** [comment]
I have temporarily disabled the cron task until the Wesnoth filesize issue is confirmed/explained. (to demonstrate the problem to Wesnoth developers)
Will re-enable when this is done.

**Comment by Dugy** [comment]
Fine. We are not making many updates right now anyway.

**Comment by edwardspec** [comment]
Re-enabled the cron task.
Turns out, Wesnoth sometimes incorrectly shows addon size (for other addons too). The real size of the beta addon was the same as non-beta addon.

**Comment by Dugy** [comment]
Isn't it showing the download size (the size of the archived add-on) rather than the size when unpacked?

**Comment by edwardspec** [comment]
Apparently not, see https://github.com/wesnoth/wesnoth/issues/3870#issuecomment-455227705 - Wesnoth addon server stores them as .tar.bz2 archives (and then provides them to players when they use "Download addon"), but the size of this .tar.bz2 file is still different from what is shown in the game.

**Comment by Dugy** [comment]
Strange, now I have absolutely no idea what could be happening.
