### ISSUE TITLE
minor cleanup possibilities

### ISSUE THREAD

**Issue by dalong76** [Dugy/Legend_of_the_Invincibles#213]
Dugi,
I delete this stuff and nothing immediately breaks, but maybe you (or someone else) knows a reason for these that I'm not seeing.

1) Most chapter 7 scenarios have gold amounts that vary based on #ifdef CAMPAIGN_LEGEND_OF_THE_INVINCIBLES_VII.  Other chapters don't do that.
2) Scenario 7/01_Another_Orcish_Assault contains [modifications] to Efraim that aren't needed and don't seem to take effect. I'm not sure what is intended. He gets his initial advancements for being created as a demigod in the previous scenario.

**Comment by Dugy** [comment]
Those are leftovers from very old versions where it was possible to start from any chapter. Nobody was using it, so I removed it. I have forgotten a few bits.
