### ISSUE TITLE
item description does not show magical damage increase

### ISSUE THREAD

**Issue by dalong76** [Dugy/Legend_of_the_Invincibles#221]
I don't see anything in the new lua to cover magic damage bonus, and nothing shows in my game.

**Comment by arobinson** [comment]
I'm seeing the same thing.

![screen shot 2019-01-04 at 9 35 34 pm](https://user-images.githubusercontent.com/93213/50720346-c2a8db00-1068-11e9-8080-b87a822679ba.png)
