### ISSUE TITLE
Weird behaviour when using Foul Potion

### ISSUE THREAD

**Issue by arodiss** [Dugy/Legend_of_the_Invincibles#23]
At the end of scenario "Invasion" (part IV) I gave Lethalia `Foul Potion`.
She scored some kills, got some bonus to max HP, and than scenario was over.
Next two scenarios are Efraim-only (+1 story), I passed them.
Than in scenario "Library" Lethalia is back and ooops! - at first turn she gets "-42 to max HP", than "-43 HP" at second turn etc. This looks pretty much like Foul Potion counter is ticking during Efraim-only scenarios.

I think the easiest way to fix this is to remove all active potions between scenarios.
However if you just remake counter for `Foul Potion` so it will not tick when unit is not in play - this would be fine too.

**Comment by Dugy** [comment]
Nah, the solution was easy, all I had to do was to prevent it from affecting units on the recall list. The problem was that I thought that I had done it years ago.
