### ISSUE TITLE
item drop to end scenario, non leader

### ISSUE THREAD

**Issue by dalong76** [Dugy/Legend_of_the_Invincibles#231]
If a scenario is ended by killing the last enemy, as opposed to the last leader, an item dropped by that enemy cannot be picked up. This issue is more a question of why is last leader special while last enemy is not. Maybe the answer is that since leaders always drop something, it is more annoying to know you will never get that last drop, while this situation is much more rare and thus doesn't bother players so much.

Technically, I believe the fix is just adding turn=$turn_number to global_events.cfg line 34. I believe that will automatically pick up all items dropped on the last turn, although maybe that is overkill.

**Comment by Dugy** [comment]
I never considered implementing a feature to automatically pick up items dropped by last non-leader enemy.

I'll leave this parked here until the overhaul is done.

**Comment by edwardspec** [comment]
Closing as implemented. Since commit 59c2d6b6c9fce56e49db45d33b033eca5c5aacb0, all items dropped on the last turn are automatically picked (even if they were dropped by a non-leader).
