### ISSUE TITLE
Guide to Lycanthropy doesn't use most damaging attack

### ISSUE THREAD

**Issue by Chergnobarp** [Dugy/Legend_of_the_Invincibles#232]
Instead, it uses the last attack in the list. Here's a patch. I haven't used github in ages, let me know if there's a better way to share patches.

[loti-diff.txt](https://github.com/Dugy/Legend_of_the_Invincibles/files/2765341/loti-diff.txt)

**Comment by edwardspec** [comment]
Works correctly.
Merged. Thank you.

> a better way to share patches

Click "Fork" button in top-right:
![fork](https://user-images.githubusercontent.com/1163218/51348529-0b728200-1ab4-11e9-82d2-6e5e7b805342.png)

It will copy a repository to your account (will be at https://github.com/Chergnobarp/Legend_of_the_Invincibles ). Edit the file(s) as needed and click "Pull request" button in your repository:
![pull-request](https://user-images.githubusercontent.com/1163218/51348652-4f658700-1ab4-11e9-969d-aa510b1af450.png)

This will send a patch here, with a button to merge it in one click.
