### ISSUE TITLE
Titles given to inappropriate units

### ISSUE THREAD

**Issue by Dugy** [Dugy/Legend_of_the_Invincibles#233]
Units that shouldn't get titles:

* Low level units that don't advance
* Infernal plants
* Infernal machines
* Imps

Anything else?

**Comment by edwardspec** [comment]
Evil Lethalia, resurrected Argan in Chapter 7, maybe other key figures like Niflheim.
They are famous and their names are unique, adding titles seems unnecessary.

**Comment by Dugy** [comment]
Units that are set to be unrenamable don't receive titles. Of course, there are instances where I forgot to mark them as unrenamable.
