### ISSUE TITLE
Reaper cannot equip crafted claws

### ISSUE THREAD

**Issue by alain-bkr** [Dugy/Legend_of_the_Invincibles#235]
The reaper cannot equip with the crafted claws

[LotI2-Heart Mountains Tour 1_reaper_no_claws.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/2776352/LotI2-Heart.Mountains.Tour.1_reaper_no_claws.gz)

![reaper_cannot_take_claws](https://user-images.githubusercontent.com/31039036/51436438-8b077900-1c8d-11e9-8021-142a70e4392c.png)

**Comment by Dugy** [comment]
The items a unit can equip depends on the unit type, not on special attacks gained through advancements.

**Comment by alain-bkr** [comment]
In #234 , the unit type did not changed, but at the beginning, it could not take crossbow, and later it became possible (i don't know when).
That's why i did two seprates tickets, as the behavior does not look the same.

The allowed items seems to depend on the advancement (fist only one weapon, then 2, or 3 depending on the unit), that's why i expected the reaer to be abble to use claws. Or it should be named differently (like jaws for the skeleton dragon, they cannot be crafted)

**Comment by Dugy** [comment]
The base unit does not have that attack. In the case of Phillip, it is added by one of the advancements that also change the unit type. If you had selected another upgrade, he would not have it.

**Comment by edwardspec** [comment]
Can be easily fixed by passing a unit (instead of unit_type) to `loti_util_list_equippable_sorts()`.
This is a regression bug. Old WML version allowed Reaper to equip claws.

**Comment by Dugy** [comment]
I wasn't sure how it was before and whether it would not break the inventory UI you are working on.

**Comment by edwardspec** [comment]
> whether it would not break the inventory UI

Don't worry about it. It's not a live feature yet, improving master branch is more important.

I periodically merge master branch into inventory branch and check that it's up to date to current APIs. So there wouldn't be any problem.
