### ISSUE TITLE
weapon attack bonus description missing % symbol

### ISSUE THREAD

**Issue by dalong76** [Dugy/Legend_of_the_Invincibles#238]
I have been meaning to put this out myself and kept forgetting until forum post reminded me.
Instead of saying "20% more attacks", weapons say "20 more attacks". Code looks like it works to me, but clearly it doesn't.

It would also be prettier if an item that gave only +1 attack left off the 's'; singular instead of plural. 
"1 more attack" instead of
"1 more attacks"

**Comment by dalong76** [comment]
The % symbol still doesn't show up for me.

**Comment by Dugy** [comment]
I was able to replicate it while looking at the Equality crafting recipe in the crafting window.
