### ISSUE TITLE
[question] Please provide more details about "hose" and "storm" specials

### ISSUE THREAD

**Issue by arodiss** [Dugy/Legend_of_the_Invincibles#24]
Currently descriptions are as following
```
hose – If this attack us used, many enemies behind and around the original target are hit (...)
storm – The damage of this attack will affect also a lot of other enemy units around the caster, and will also deal some impact damage (...)
```
Can you please replace "many enemies", "lot of other enemy units" and "some damage" with more exact definitions?

BTW I have no idea what those exacts are

**Comment by Dugy** [comment]
You can use the forums to ask me about things, can't you?

The 'some damage' means damages between 4 and 8, depending on distance. Hose in particular hits the target and units up to five hexes behind him and all adjacent units, the damage somewhat decreases with the distance from the main direction and the caster. Storm hits all adjacent units to the caster for full damage and all units adjacent to them for a half of the damage.

**Comment by arodiss** [comment]
@Dugy 
Thank you for the explanation.
Though, I asked not solely for explanation, but also for update of [this](https://github.com/Dugy/Legend_of_the_Invincibles/blob/master/utils/abilities.cfg#L1143) [code](https://github.com/Dugy/Legend_of_the_Invincibles/blob/master/utils/abilities.cfg#L988)
Do you prefer to get such things on forum as well? I am not currently there but surely will do the way that fits you. I would like you to spend time on campaign itself, not on juggling feedback channels :smile: 

BTW if you really want forum as the only feedback channel you can mention this in `README` and remove GitHub Issues section entirely (Repository main screen -> "Settings" -> Tab "options" -> remove tick from "Issues")

**Comment by Dugy** [comment]
I do not want to remove the issues section altogether because it makes sense to report issues here. But some things fit more into a discussion than here.

The forums are mentioned in README.md.

I think that if I added all that information into the ability description, it would be too long, taking too much space and preventing other weapon specials from being shown there.
