### ISSUE TITLE
"Invasion" Scenario bug at start

### ISSUE THREAD

**Issue by carbonpenguin** [Dugy/Legend_of_the_Invincibles#248]
Got to the "Invasion" scenario, and it's choking in different ways depending on which option I choose. Either the player side disappears entirely and the remaining AIs duke it out, or the player-side undead vanish (bone dragons not created), but the player can still play, albeit w/ just normal recalls.

Curious to see if others are running into this?

Error Message screenshot: [screenshot from 2019-01-31 23-21-40](https://user-images.githubusercontent.com/47235094/52102560-18609c80-25af-11e9-9e17-c17b5f48df7d.png)

On LOTI 3.2.4d on Wesnoth 1.14.5 on Ubuntu.

**Comment by Dugy** [comment]
Everything seems to be fine when I try it.

The error message is too vague. Can you please upload a save file from the start of the scenario, one that causes the bug to appear after loading?

**Comment by carbonpenguin** [comment]
[LotI1-Invasion.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/2823957/LotI1-Invasion.gz)
