### ISSUE TITLE
<Invalid WML found> [micro_ai_fast] not supported

### ISSUE THREAD

**Issue by johncburr** [Dugy/Legend_of_the_Invincibles#25]
Right after the dialog finishes at the beginning of An Orcish Assault, this error appears.

BfW version 1.13.6 and 1.13.7

LotI downloaded 9/5/2017 @ 07:16 CDT

I've noticed the error for a month or so. (That's when I first started trying to play this campaign in 1.13.x)

**Comment by Dugy** [comment]
I can replicate it. It is a fatal problem.

**Comment by Dugy** [comment]
Should be fixed now. Thank you for telling me of this, support for 1.13 needs to be debugged before I make a working upload.

**Comment by johncburr** [comment]
Yeah, I figured that it wouldn't be fully compatible just yet. But that's why I'm playing it, so I can find all of the bugs for you.
