### ISSUE TITLE
get_type_advancement() and 09_Fencer unit

### ISSUE THREAD

**Issue by edwardspec** [Dugy/Legend_of_the_Invincibles#255]
`get_type_advancement()` currently doesn't work for 09_Fencer (early Efraim), because it doesn't have Advancing type.
Can be reproduced by starting the Tutorial.

Possible solutions:
1) look for advancements in the unit type itself if Advancing type is not found.
2) add Advancing type to 09_Fencer.

**Comment by Dugy** [comment]
I think option 1 is significantly better. Will you do it or should I do it?

**Comment by edwardspec** [comment]
Will do this shortly.
