### ISSUE TITLE
Strange error at start of scenario The First Blow

### ISSUE THREAD

**Issue by Dugy** [Dugy/Legend_of_the_Invincibles#256]
The error message is `<Invalind WML found> unknown conditional wml: [set_variable] (65536)`

The exception isn't thrown from the scenario code, but I am clueless what actually causes it or what does the error message mean. It doesn't seem to be thrown from lua. There doesn't seem to be a good way to locate the exact line.

[LotI1-The First Blow.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/2865817/LotI1-The.First.Blow.gz)

**Comment by edwardspec** [comment]
Investigating how to find it.
What usually causes this is having `[set_variable]` instead of `[variable]` within some `[if]` tag.

**Comment by Dugy** [comment]
I expected it could be something like that, but I didn't expect it to be a macro, so I assumed it was in one of the files in utils.

How did you find it, btw?

**Comment by edwardspec** [comment]
> How did you find it, btw?

Checked all occurences of "variable" string (case-insensitive) in 09_The_First_Blow.cfg for whether anything is out of place.

**Comment by Dugy** [comment]
I searched for `set_variable`. Either I had bad luck or you had more insight.
