### ISSUE TITLE
Cannot use potions anymore

### ISSUE THREAD

**Issue by arobinson** [Dugy/Legend_of_the_Invincibles#265]
Potions cannot be used anymore, instead they are equipped, giving no benefit in the latest `master` branch source.

Open the save game and try to give a health potion to the dwarvish dragonguard

[LotI2-Betrayers of Humankind Turn 5.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/4008720/LotI2-Betrayers.of.Humankind.Turn.5.gz)

**Comment by Dugy** [comment]
The potions do apply bonuses as stated (the healing potion in question increases maximum hitpoints by 10). It just doesn't trigger the on use effect.

I wanted to rewrite that code anyway, so I'll do it now.
