### ISSUE TITLE
Last scenario, items don't combine with an error "loti.item.type[]" not found

### ISSUE THREAD

**Issue by arobinson** [Dugy/Legend_of_the_Invincibles#266]
Error:
![image](https://user-images.githubusercontent.com/93213/71631625-db3dc980-2bc6-11ea-9b66-7ff8516e4a66.png)

Happens in `LotI2-End of the World` turn 1

Save game (happens after dialog)
[LotI2-End of the World.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/4013351/LotI2-End.of.the.World.gz)

**Comment by arobinson** [comment]
I think the fix is to add this to line 541:
```
                [set_variable]
                    name="i"
                    value="0"
                [/set_variable]
```
Not sure anymore if Lua is 1 or 0 based, but this seemed to work.

**Comment by arobinson** [comment]
[266.patch.txt](https://github.com/Dugy/Legend_of_the_Invincibles/files/4013494/266.patch.txt)

**Comment by arobinson** [comment]
[266.patch.txt](https://github.com/Dugy/Legend_of_the_Invincibles/files/4013497/266.patch.txt)

**Comment by Dugy** [comment]
Lua is 1-based, but WML is 0-based.

I will add it to the code once I finish the stuff I am doing.
