### ISSUE TITLE
bugs in 3.2.6, unit will disappear when equipping items

### ISSUE THREAD

**Issue by kevinmama** [Dugy/Legend_of_the_Invincibles#267]

**Comment by Dugy** [comment]
I'll fix it when I come back from work in a couple of hours.

**Comment by edwardspec** [comment]
Works for me on master (probably was fixed by 8ce7c6f59bb4c178a9b58993783b93d282cb6982). Please confirm.

**Comment by Dugy** [comment]
Seems that I broke it with my half-assed attempt to fix the problem with units on recall list not being updated in 97ac0d4.

**Comment by Dugy** [comment]
I have checked it out and it seems to have worked before and also works after the patch.

However, it was also reported on the forums, so there was probably something wrong, just somehow not affecting me.

**Comment by edwardspec** [comment]
It was only affecting new units (units created on this turn), like Delenia on turn 1 of Tutorial. For some reason wesnoth.get_unit() wasn't finding them,

Units didn't just disappear, they were moved to the recall list.

Closing as resolved.

**Comment by Dugy** [comment]
Thanks for the help.
