### ISSUE TITLE
AI too cautious in Campaign 1 

### ISSUE THREAD

**Issue by arobinson** [Dugy/Legend_of_the_Invincibles#280]
I started playing again, this time Campaign 1 (I usually replay campaign 2) and have noticed that even on hard difficulty, it is extremely easy and almost boring. The reason for this is that the enemy often does not attack, they just move their units next to mine and don't attack. As a result, battles are slow and simple.  Only heroes with low defense or less powerful ones are targeted, but ones with good equipment with high health never have to defend. Looks like the aggressive stats on the AI needs to be increased in Campaign 1 especially after the initial few scenarios.  

Wesnoth Version 1.14.12
Using git master branch for LotI

**Comment by arobinson** [comment]
[LotI1-Gehenna Turn 13.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/4799897/LotI1-Gehenna.Turn.13.gz)

In this example save, move some units near the enemy and end a turn, many won't attack or only target a few units. Efraim and Lethalia are never attacked by the AI

**Comment by Dugy** [comment]
I was able to replicate your issue and it seems that increased aggression does resolve the problem as you suggested.

Can you tell me in which scenarios does it happen? All of chapter 3?

**Comment by arobinson** [comment]
I can't recall when I noticed it, but I think it could have been most or all of 3. The next chapter seems fine, so I don't think it affects anything else. It creeps up as units get better equipment, so partially based on luck. 

Thanks for all the hard work!
