### ISSUE TITLE
Armour attribute appears to do nothing

### ISSUE THREAD

**Issue by IamTechknow** [Dugy/Legend_of_the_Invincibles#3]
When I used the Fire-Forged Friend potion, I noticed the unit's move points went done but its resistances did not increase at all. Upon investigating this I found in "item_list.cfg" that the defense attribute increases physical resistances, dodge increases terrain defense, but three items including the potion have "armour" instead of "defense", the latter of which does affect physical resistances. It appears then that armour does nothing and should be fixed by replacing it with defense.

**Comment by Dugy** [comment]
Wow, I call that well-researched bug report. I have released a patch for that.

**Comment by IamTechknow** [comment]
I tend to be good at figuring out how things could work. Thanks for the timely commit too
