### ISSUE TITLE
For some units an equipped weapon doesn't apply

### ISSUE THREAD

**Issue by Discontinuum** [Dugy/Legend_of_the_Invincibles#302]
For some units a weapon they're allowed to equip doesn't apply (in a sense that it doesn't change the attack's name and stats, resistances and moves and other non-attack properties work) when they actually equip it. Though logically it shall apply. A list of some examples (most likely incomplete):

Drake Fighter and Drake Warrior can equip a sword, but it doesn't apply. The attack's name is "war blade".

Drake Blademaster can equip a sword, but it doesn't apply. The attack's name is "war talon".

Dune Rider can equip a bow, but it doesn't apply. The attack's name is "composite bow".

Al Ghareeb from "The Beautiful Child" campaign can equip a sword but it doesn't apply. The attack's name is "long sword".

I suppose this might happen because all these examples above have slightly "non-standard" attack's name, not just "sword" or "bow". So the game is able to recognize a correct item type but for some reason it doesn't recognize it when calculates attacking stats

**Comment by dalong76** [comment]
Where can you get a drake unit on your own side? What is a Dune Rider?

**Comment by Discontinuum** [comment]
Dune Rider is https://units.wesnoth.org/1.14/mainline/en_US/Dune%20Rider.html

Well, Drakes and others I got in my experimental add-on where I plugged LotI items and drops to World Conquest II. But even omitting my add-on, the bug exists and has its effect in another dependent on LotI campaign, The Beautiful Child. You can look at this save ([TBC-Ziggurat Town-Auto-Save1.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/5675821/TBC-Ziggurat.Town-Auto-Save1.gz)), you'll need "The Beautiful Child" add-on to be installed.

**Comment by Discontinuum** [comment]
More on this, the code in lua/stats.lua recognizes as sword attacks only a fixed list of attacks' names
`if wn == "sword" or wn == "short sword" or wn == "greatsword" or wn == "battlesword" or wn == "saber" or wn == "mberserk" or wn == "whirlwind" or wn == "spectral blades" or wn == "lichsword" then
			weapon_type = "sword"`

While in lua/main.lua (the function which determines a list of allowed item types) any unit with any attack that satisfies "sword$" regex is allowed to equip a sword. A similar story is with bow. With "war talon" and "war blade" the things are more interesting: in stats.lua they are classified as some "exotic" while in main.lua they simply go as "sword".

Maybe this mismatch is the cause of the problem.

**Comment by Dugy** [comment]
Actually, I write the part in lua/stats.lua, while edwardspec wrote the part in lua//main.lua. Apparently, neither of us knew what the other one was doing. There should be only one function that matches attack names to weapon types.

While looking at this line:
```
-- TODO: This could be a WML resource file producing a table indexed by weapon name and receiving weapon type
```
it appears to me now that I even knew such a code didn't belong into lua/stats.lua, but I forgot to fix it.

**Comment by Discontinuum** [comment]
Well, the question is which way for resolving the issue to choose. Should we use a closed short list of names like in "stats.lua" or supplement it with regexes like edwardspec did in main.lua? Also I think it would be nice to move "war blade" and "war talon" from the "exotic" category to some existential one, maybe both in "sword" as it is in main.lua. It wouldn't affect LotI but would be great for my add-on, to give Drakes an ability to wield a weapon properly.

**Comment by Dugy** [comment]
I prefer the option with a closed short list like in stats.lua (though it should better be looked up in a table). The reason is that the regex cannot do it alone and has to be mixed with some extra conditions, and can match incorrect items (a _rainbow wave_ spell would be considered a bow, a blunt weapon called _relaxed blackjack_ would be considered an axe etc).

The reason why there are no Drakes in LotI is that making L4 drakes needs reconstructing something from existing unit parts, which is hard for drakes who are not humanoids. Furthermore, the drakes always left to me like a recent addition that does not fit into the rest of the lore or any particular theme (they are always just a random monster of the week with no consequence in the next scenario). Gameplay-wise, their strength of individuals combined with mobility would be a huge advantage compared to other units. However, I wouldn't mind if some code was added to support them like other units.

The _exotic_ weapons are nowhere near swords in appearance, they're more like the _metal claws_ category. There are no weapons in this group (except the crafted ones), however, it should be relatively easy to make it possible for add-ons that use LotI as resources to add new dropped item types now. Also, I could add some, they could be useful in LotI as well (the weapon types that drop are sceario-specific, so they won't drop in scenarios where they are useless).

**Comment by Discontinuum** [comment]
You have a point about regexes but are wrong with the specific examples. If we use the regexes of edwardspec, "sword$", "bow$", "axe$", your examples won't be classified wrongly because these regexes require the name to actually end with "sword" , "bow", ... But there are more subtle problems, like Lethalia_evil has a "flaming sword" attack, if we enable the all-regex mode, this attack would be overriden which I guess is undesirable. An even better example is "Searing Ice" sword as it adds two bonus attack "freezing sword" and "flaming sword" which ofc mustn't be overriden by itself (as it will ruin the idea of this item).

I thought about "war talon" being metal claws, yes. "War blade", mmm, not so like claws for me. But it's not so bad that claws aren't droppable, they are craftable and should be fine (esp. after bugs with crafting will be fixed). But being "exotic" is worse cause you can't craft this category, it's just like a non-existential category for this weird drakes' stuff.

Enabling add-ons which use LotI to add their own items would be a fine addition!

About Drakes, I even thought about adding LotI style 4lvl advancements and AMLAs specifically for my add-on because it's not very interesting to have some WC II factions inferior just because half of your units have no potential to grow further in the future (and also because I like Drakes appearances, but it's just my preference ofc). I intended to take sprites from some other extended eras like "Reign of the Lords" or something and then invent some convenient AMLAs, though I'm not very sure about the quality of animation there (I tested 4lvl Drake Blademaster of RotL and it was awful, the sprite just disappeared when he was attacking). And not only Drakes actually, I thought about adding AMLAs to everyone from default, Woses, Bats, Gryphon Riders, etc. But it's only my dreams ofc and it's like my personal headache because for LotI these units' enhancements have no value (as the player never controls these types of units).

**Comment by Discontinuum** [comment]
Also, it would be even more great if add-ons were able to register their own maps "attack name -> type of the item", though I don't know if it would be rational in terms of bug prevention and other stuff

**Comment by Discontinuum** [comment]
I think now it can be closed
