### ISSUE TITLE
When you equip an item to a unit recruited (recalled, created) during the current turn in MP, the game spits an OOS but everything's fine

### ISSUE THREAD

**Issue by Discontinuum** [Dugy/Legend_of_the_Invincibles#325]
That's an old bug but the recent fix hasn't fixed it so the problem seems to be deeper.

The thing is that if you recruit a unit and then in the inventory dialog equip an item on that unit on this very turn it's recruited (important!), the game spits an OOS. The one who did the action usually sees an OOS "dependent command found though is_synced=false", other parties see "random called 1 times, but the original replay called random 0 times". Sometime might be another one "input expected, recruit found" (if you recruit - equip that recruit - recruit a new one). The game though works fine after that, all sides seem to be synchronized, the equipped item is visible to all.

Also for some reason Undead units (of the Undead race) aren't affected by this: immediate equipping of them on the turn of recruitment doesn't cause any oos and works fine. I thought that might be because undead has neither random traits nor names, but my tests revealed a strange thing: only undead is unaffected. I tried Woses (no traits but names), Monsters, Mechanisms, Uria's Drones, but no, all of them who are not undead cause an OOS to pop up. Undead units, both LotI's ones like Will-o-Wisp and standard ones, don't.

**Comment by Dugy** [comment]
I think that it's a some problem that's suppressed by some run by some event run at every turn and by some event specific to undead. I tooked for something undead-specific in the lua code, but I found nothing suspicious,

**Comment by Discontinuum** [comment]
Indeed this seems like an undead-specific thingy, and my assumption about random traits and stuff is wrong: I made a test unit type of the undead race but with its own random traits. And it still works without an OOS just as any conventional undead

**Comment by Discontinuum** [comment]
I've just found the reason. It's `post stats update` of assigning a legacy. That's why OOSes tell something about random calls and undead aren't affected

**Comment by Dugy** [comment]
That would mean the legacy assignment is breaking it. Undead are not supposed to get legacies, so that it would be consistent with their absence of traits.

I think that the problem is that it's called from lua code within a synchronised call, however, this part isn't synchronised. I think that event should be fired after the synchronised call ends.

**Comment by Discontinuum** [comment]
Y, I guess it happens that for an equipping side "update stats" happens during the inventory dialogue, right after enqueuing an "equip" event (as for the doing side enqueuing executes the action immediately), and so before returning from synchronized_choice. For other sides, obviously, it happens only after returning from synchronized_choice, as they read actions from it.

Not sure though what kind of fix would be the best

**Comment by Dugy** [comment]
I think that the most practical solution would be to trigger the event when synchronized_choice ends. If this issue was addressed specifically, another `post stats update` event would break it again.

**Comment by Discontinuum** [comment]
What bothers me is that moving the legacy-picking event into the end of synchronized_choice might be kinda confusing, like here you have it after any stats update, quite logical, and in the other case you're tieing legacy-picking to items operation... Or maybe it's not so bad after all, I don't know

**Comment by Dugy** [comment]
That's a valid concern.

The problem is that it can't be part of update stats because it's randomised. It also can't be set when the unit is recruited because it's done also for units that aren't recruited. The `post stats update` looked like a good solution, but now it doesn't.

How about changing it into a `pre stats update` event fired before the synchronise_choice part?

**Comment by Discontinuum** [comment]
`unit placed` event might be an alternative to `recruit`. It may have its caveats but the legacy event is called once (like, not once but it stops immediately when fired repeatedly) and has no calls of other events.

About `pre stats update`, it might be the one, though it would require to add additional firing of that event in the items code (inventory dialogue + new item_pick) before entering the synchronise_choice.

**Comment by Dugy** [comment]
As for `unit placed`, I was worried that it might be called by update stats inside a synchronised section. If that's not the case, then it's an easy solution to the problem.

The problem with `pre stats update` may be a stopper, because there may be no guarantee that a stats update will be called inside that synchronize_choice.

**Comment by Discontinuum** [comment]
I think `unit placed` would indeed be called by update stats. But as update stats runs on an already existing unit, it will have a legacy already set in a previous `unit placed` fired on the first appearance of the unit. And multiple firing of that event shouldn't cause troubles, as we have `has_legacy` variable set after the first run, others run will return immediately.

> no guarantee that a stats update will be called inside that synchronize_choice
As for this, yes, we have no guarantees, but for assigning a legacy I guess we don't want this event to be run inside `synchronized_choice`. If we run it from some WML synched event, RNG will be autosynced, but running inside a synchonized_choice block would require us to synchronized it manually which would be mess and complication.

**Comment by Dugy** [comment]
Okay, so I guess that `unit placed` is the way.
