### ISSUE TITLE
Abnormal behaviour if Lethalia has some attacks disabled for retaliation when she transforms from Lich to Demigod

### ISSUE THREAD

**Issue by Discontinuum** [Dugy/Legend_of_the_Invincibles#333]
If Lethalia has her faerie fire attack retaliation disabled and transforms from Lich to Demigod, a bunch of abnormal things can happen. First is that her fearie fire becomes attack-only and you can't enable retaliation back. But that effect still can be cured by a healing potion, after taking it somehow an attack returns to normal. Second is that during this process her axe-whirlwind lost its attack-only status, in Apologies I had it disabled in menu but could enable it for retal. And this isn't restored by a healing potion, whirlwind remains retaliational. 

So, to conclude, as Leth changes her attacks and retaliation disabling variables alongside with attack weights are not corrected, weird things happen to her attacks.

**Comment by Discontinuum** [comment]
> Bug report: Battle for Wesnoth version 1.16.2, Legend of Invincibles 3.2.7b. Playing the Lethalia thread in Chapter VI. At the end of Frozen Land, if Lethalia only has Chill Tempest selected as a ranged retaliation method when she becomes a Demigod and loses Chill Tempest, she is not able to do any sort of ranged retaliation in Apologies (no ranged methods appear when you select retaliation methods). If she has Gossamer or Faerie Fire also selected as a retaliation method when she becomes a Demigod, then all works as I would expect (both those methods appears as selectable retaliation methods).

https://forums.wesnoth.org/viewtopic.php?p=673290#p673290

I believe the same issue, but instead of benefiting the player, hurts the player. I think we need just clear all custom disable retals right before changing Lethalia's type

**Comment by Dugy** [comment]
This can be problably generalised that every unit that loses an attack that is selected as always chosen for retaliation will break. There are probably several other units that can have this problem as well, even when some normal unit advances into something whose set of attacks isn't a superset of the previous type's attacks (like Grand Knight to Dragon Knight if the preferred retaliatory attack is sword).

I think that a proper solution would be to have the retaliation code detect that the attack is missing and reset the setting.

**Comment by Discontinuum** [comment]
The main problem is that we store retaliation data (most importantly data about attacks that can be enabled back) as indexes. So if the order of attacks changes (if some of them disappear for example), we get wrong info, indexes pointing at not intended things

**Comment by Dugy** [comment]
Yes, and it's saved as index because attack names are not necessarily unique, and the other differences like damage type are not guaranteed not to be overriden by items. At the same time, items can add new attacks, so manipulating the inventory will break the index, so neither attack names nor the index is a particularly good solution. This is more complicated than I thought.

Regarding backwards compatibility, I think that simply ignoring previously set retaliation settings could be a solution.

**Comment by Dugy** [comment]
I am sorry I forgot about this. I fixed it as part of #841.
