### ISSUE TITLE
New issue: Transporting Facility summons monsters in every hex when you arrive

### ISSUE THREAD

**Issue by arobinson** [Dugy/Legend_of_the_Invincibles#345]
I doubt this is intentional, but in the latest code, it seems that every single hex is filled with an enemy when entering the transporting facility for the first time. Never done this in the past.

It locks up the game pretty much completely if you try to end the turn after fighting ends (AI cannot handle that many units)

[LotI2-Transporting Facility.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/7033986/LotI2-Transporting.Facility.gz)
[LotI2-Transporting Facility-Auto-Save1.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/7033988/LotI2-Transporting.Facility-Auto-Save1.gz)

**Comment by Discontinuum** [comment]
Amazing. It was broken not by my latest change which seemed very dangerous, but by the legacy assignement commit https://github.com/Dugy/Legend_of_the_Invincibles/commit/2aa954750be545cd64ebabe0fedf4123edfa0277 Before this commit, everything's fine. I wonder how it broke the inferno utils, have to investigate

**Comment by Discontinuum** [comment]
Hm, the minimal code to cause this bug is 

    [event]
        name=unit placed
        first_time_only=no
        {VARIABLE has_legacy 0}
        [if]
            [variable]
                name=unit.race
                not_equals=undead
            [/variable]
            [then]
                {FOREACH unit.modifications.advancement i}
                   
                {NEXT i}
                
            [/then]
        [/if]
        {CLEAR_VARIABLE has_legacy,legacy_type}
    [/event]

If you remove FOREACH, everything's fine. Strange...

**Comment by Discontinuum** [comment]
Also, this is not only in transporting facility

**Comment by Discontinuum** [comment]
Hm, so far I've determined that something goes wrong in portal spawn and infernal flora, if you delete them, the bug disappear even with this legacy assignment code

**Comment by Discontinuum** [comment]
I think I have established the cause. The cycles in this unit placing inferno events use "i" wml variable. And when they placed a unit, legacy assignment procedure also use "i" variable for internal processing (iterating unit's modifications). And this changes the "i" of the outer cycle so it runs out of control and spawns units everywhere.

Amazing

**Comment by matsjoyce** [comment]
The real flaw is no variable scoping in WML, and that isn't going to change :disappointed:

**Comment by Discontinuum** [comment]
I believe we can hide this code in a Lua block, this will prevent any possible name clash with any outer cycle that could possibly place units

**Comment by arobinson** [comment]
I've had the same issue in my own add-on. The fix is to clear the index variable after the FOREACH loop. Unfortunately you cannot nest FOREACH loops as a result of their code, but you can just use WML and pick a different iteration variable than i

**Comment by Discontinuum** [comment]
Legacy assignment previously was in the post update stats event and it caused the bug with oos when you recruited and equipped the same turn. Update stats isn't called for each unit appeared on the board immediately, afaik it's called pretty rarely, on equipping, on advancing and on a new turn (with some conditions), but not immediately at unit placing. So with this now we have no guarantee that update stats will be called in synchronized code first.

**Comment by Dugy** [comment]
I wrote most of the WML code while `unit_placed` did not exist. When it was added, I used it sparingly because it can get called at inappropriate places. However, that meant that some updates were delayed until `turn_refresh` or something, but was called at enough locations to make sure it would never miss. You changed it to `unit_placed` causing my fear to come true.

After thinking about it for a while, I think that what could work would be to trigger this legacy assignment code before the `synchronize_choice` with all the GUIs is called on the unit in addition to the usual stuff like advanced, recruited etc.

**Comment by Discontinuum** [comment]
> get called at inappropriate places. You changed it to unit_placed causing my fear to come true

Well, there is a point about this, but actually my implementation was betrayed only by lacking variable scope in WML. If we move all the code into an "assign_legacy" lua-implemented wml tag (using local lua variables for cycles and whatnot) and replace the wml part with just "[assign_legacy] <passing a unit> [/assing_legacy] we should resolve the problem.

Anyway, I'm not quite how you can implement your plan, "trigger this legacy assignment code before the synchronize_choice with all the GUIs is called on the unit". Do you mean triggering legacy assignment when GUI opens from the menu (and so it would be unconnected from update stats)?

Also, a little contemplation, maybe irrelevant: it would be nice not to bind legacy assignment and update stats to each other because right now update stats (if I'm not missing any detail) has a nice property of being deterministic, so perfectly synchronized and more or less insensitive to exact time and order of invocation. And spoiling it with indeterministic effects... Not desirable if we can avoid that

**Comment by Dugy** [comment]
> If we move all the code into an "assign_legacy" lua-implemented wml tag (using local lua variables for cycles and whatnot) and replace the wml part with just "[assign_legacy] [/assing_legacy] we should resolve the problem.

I was considering this option, but later forgot about it because it seemed to me like if there were better ways. It is indeed a valid solution.

> Do you mean triggering legacy assignment when GUI opens from the menu (and so it would be unconnected from update stats)?

Yes. Just before the GUI opens, it does the RNG-dependent stuff and the rest can be deterministic.

> It would be nice not to bind legacy assignment and update stats to each other because right now update stats (if I'm not missing any detail) has a nice property of being deterministic, so perfectly synchronized and more or less insensitive to exact time and order of invocation.

Yeah, this makes sense.

**Comment by Discontinuum** [comment]
In theory we can even assign legacy only during turn event. I doubt it can ever be that you need to know a unit's legacy on the very first turn of its appearance. The only problem is that in this case AI leaders would have no legacies during the title assignment so the influence of legacy on the title would stop working

**Comment by Dugy** [comment]
I don't think that enemy leaders not getting legacies is a problem, legacy has only a minor influence on the title and enemy legacies are impossible to learn. However, I think that the possibility a unit would advance in the same turn as it entered the game is not to be neglected.

However, I can think of yet another solution. Use the unit's name, traits and maybe some other properties it had at that time to generate a seed and use that seed to select a legacy. Undead don't have names or traits, but conveniently also don't happen to have legacies.

**Comment by Discontinuum** [comment]
> However, I think that the possibility a unit would advance in the same turn as it entered the game is not to be neglected.

Technically if this is not a problem. If you even manage to advance immediately and take awareness, I doubt you could take advancements on a single turn (it would a very unusual situation) and you'll get a legacy on the next turn anyway

> and enemy legacies are impossible to learn

Allied legacies are possible to learn. In LotI 2 three allied leaders join you and they have autogenerated titles.

> However, I can think of yet another solution. Use the unit's name, traits and maybe some other properties it had at that time to generate a seed and use that seed to select a legacy. Undead don't have names or traits, but conveniently also don't happen to have legacies.

Hm. Tbh seems too complicated for a part of the game users will hardly ever notice...

**Comment by Dugy** [comment]
> Allied legacies are possible to learn. In LotI 2 three allied leaders join you and they have autogenerated titles.

True.

> Hm. Tbh seems too complicated for a part of the game users will hardly ever notice...

It has a huge advantage that it would not interact with anything, so there would be little probability something would break it unexpectedly.

And it would be also quite easy to do now that I realise that every unit has an autogenerated unique id. It's not a number, but I estimate that the code to get numeric seed from it would take only about 5 lines of code.

**Comment by Discontinuum** [comment]
I've tried today to write a lua version fix quickly, and I must confess: I failed. In the lua function I saved a unit with the "put_unit" method (just like in the title assigning function), but that causes a new triggering of the "unit placed" event which might mess things up. Maybe I didn't find the way to circumvent it, to save the unit without calling "put_unit", but anyway "unit placed" is a really complicated tool to use (especiall in LotI with its amounts of magic), I start to share your suspicion about it.

**Comment by Dugy** [comment]
I have changed the code so that the legacy is assigned in `stats.lua` based on a random number set at scenario start, the unit's position and type. This allows doing 'random' stuff on units in synchronised sections.

**Comment by Discontinuum** [comment]
Oh, that's a good solution, I like it. Should be pretty efficient as well

**Comment by Discontinuum** [comment]
I wonder though why it's >> shift, doesn't it mean right-most digits be lost?

**Comment by Dugy** [comment]
Yeah, I did it wrong. It's fixed now.

**Comment by Discontinuum** [comment]
Well, I'm not going to revert this change, cause having legacies this way means less things can go wrong, but I have to note: I found out that documentation says that [foreach] has scoping. Macro {FOREACH}, which is deprecated btw, seems not

**Comment by Dugy** [comment]
I also think that my approach to fix this avoids a lot of other potential problems and should stay in place even if the original source of the problems is removed.
