### ISSUE TITLE
Experience modifications are broken

### ISSUE THREAD

**Issue by Dugy** [Dugy/Legend_of_the_Invincibles#348]
Mind raid doesn't seem to work. Awarding experience to units that die from incinerate also doesn't work (the [kill] tag didn't ever award experience).

**Comment by Discontinuum** [comment]
Mind raid afaik works. I think I saw it working

**Comment by Discontinuum** [comment]
One thing noticed with mind raid: seems like if you attack an enemy with 1 xp to advance with mind raid attack, the target levels during your attack, instead of gifting exp

**Comment by Dugy** [comment]
I think I know how to fix that - kills from splash attack deliver experience after the fight ends, the same mechanic could be repeated here.
