### ISSUE TITLE
New liminal and demons

### ISSUE THREAD

**Issue by Discontinuum** [Dugy/Legend_of_the_Invincibles#355]
Liminal now works differently: gives +25% when neutral ToD and 0% during the day/night. It means all demons now became stronger. Maybe we should now decrease their damage a bit to compensate? But I dunno how serious this new challenge is

**Comment by Discontinuum** [comment]
Ugh, if so that's no good, yeah

**Comment by Discontinuum** [comment]
Then I can propose to weaken demons more, by 30% at least instead of 20%. This will make demons weaker than they were in general but kinda compensate the inability to blind them with +50% illumination (and darkening)

**Comment by Dugy** [comment]
Yeah, that makes sense.

**Comment by dalong76** [comment]
Is it possible to re-create the liminal from before, just under a different name? The new implementation makes no sense ... if light/dark matters, all degrees of it should matter.

**Comment by Dugy** [comment]
I think it would have to be done by setting a time of day variable when the unit moves or otherwise enters some hex and also when the time of day changes and using it in a formula in a self-affecting leadership ability. I think this approach would have performance implications and be quite bug prone.

**Comment by Dugy** [comment]
Okay, I reduced their damage approximately by 30%, but I had to do it a bit randomly because of rounding. Demon Infiltrators from chapter 8 were less weakened because they are affected by normal day and night cycles.
