### ISSUE TITLE
A "cursed bat" which resets stats when attacked.

### ISSUE THREAD

**Issue by Discontinuum** [Dugy/Legend_of_the_Invincibles#363]
A strange save I get on the forums
[LotI1-Escape from Oblivion-Auto-Save4.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/7464799/LotI1-Escape.from.Oblivion-Auto-Save4.gz)
. 
If you attack the 16,3 bat with any unit, it loses its equipment stats and amlas stats (although it's recovered back if you drop-take back some item). Only that specific 16,3 bat triggers it, you don't need to kill it to trigger it, neither unit levels but still triggers it

**Comment by Discontinuum** [comment]
I have found the cause of the problem, it's FORCE_CHANCE_TO_HIT on Vampire Bats. It's macroexpanded into
[force_cth.txt](https://github.com/Dugy/Legend_of_the_Invincibles/files/7468418/force_cth.txt)
and this [remove_object] causes the unit to be reassembled from the type. Which obviously resets all our custom changes from stats.lua (I myself run into a similar problem that remove_object deleted my changes on units)

**Comment by Dugy** [comment]
Maybe it could be done differently, by giving these enemies some objects that give them an opponent-affecting [chance_to_hit] weapon special, so that the playable units would not be touched.

**Comment by Discontinuum** [comment]
With 1.16 new thing about weapon specials as abilities I think it's possible (the same way as marksman/charge/drain/... leaderships)

**Comment by Dugy** [comment]
You could do `apply_to=opponent` since a very early version, and actually LotI has the _struggle_ weapon special that does affect the opponent's chance to hit.

**Comment by Discontinuum** [comment]
I meant not `apply_to=opponent` but using `[chance_to_hit]` as an ability of the unit instead of a weapon special of its attack

**Comment by Dugy** [comment]
That's fine too.

**Comment by Discontinuum** [comment]
I think it's resolved now, two remaining FORCE... on the player are just precautions not to kill accidentally Lethalia_evil_good and a story Silver Mage guy (Taruk afaik his name), and they shouldn't ever come to play in the correct scenario flow (as the dialogue must be triggered before any possible attack on them)
