### ISSUE TITLE
Transition between Library and Lost in Space seems broken

### ISSUE THREAD

**Issue by Discontinuum** [Dugy/Legend_of_the_Invincibles#373]
This was occasionally reported a year ago but turns out to be still there: when you jump into teleport, all units for some reason disappear, and then next scenario you lose on start (cause Lethalia can't be recalled)

[LotI1-The Library-Auto-Save9.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/7508581/LotI1-The.Library-Auto-Save9.gz)

I wonder if it's a macro used here fails somehow and just wipes all units or what is hapenning

**Comment by Discontinuum** [comment]
For some reason PUT_TO_RECALL_LIST doesn't work, all units that were in the mission, including Lethalia, aren't in the list. I can't figure out why

**Comment by Dugy** [comment]
It might be the recall list of a wrong side, one defined by its leader Lethalia rather than Efraim (who is nominally the protagonist).

**Comment by Discontinuum** [comment]
Noticed another thing: after the end of the scenario, in the linger mode, in 1.16 the last of the units stands on the place of the former portal, like it wasn't deleted. Like it's not deleted from the board. In 1.14 it wasn't the case.

**Comment by Discontinuum** [comment]
> It might be the recall list of a wrong side, one defined by its leader Lethalia rather than Efraim (who is nominally the protagonist).
Dunno, we have the same side number. I tried to recall Efraim before instead of after the teleportation: no change afaik

**Comment by Discontinuum** [comment]
Finally I have found the immediate cause. The scenario starts working fine when you delete the line "{DISABLE_UPKEEP 1}". So something should be wrong with this macro

**Comment by Discontinuum** [comment]
It seems like a Wesnoth bug. [modify_unit] tag in 1.16 for some reason places back on the map each unit we put to the recall list. And if several units were put to the recall list on the same hex, only the last of them would appear, all others are just gone. Which happens in this scenario

**Comment by Dugy** [comment]
That would mean that redefining the `PUT_TO_RECALL_LIST` macro to use store/unstore unit would fix the issue?

**Comment by Discontinuum** [comment]
The problem with storing would be that the finishing effect of removing loyalness won't be reset if we unstore in the next scenario. We may try unstore here, placing everyone on the map somewhere (which will create trash on the linger mode screen but maybe will have no units disappearings)

Also we may just remove DISABLE_UPKEEP or remove the cool effect of jumping into the portal... But that's meh

**Comment by Dugy** [comment]
Maybe the loyalness could be removed by the code that makes the unit disappear inside the portal. This should be relatively safe, but there would be a risk that changes to the `DISABLE_UPKEEP` macro might break this.

**Comment by Discontinuum** [comment]
DISABLE_UPKEEP seems working okayish. The pitfall of this scenario is that Wesnoth bug of flawed interaction of put_to_recall_list and modify_unit. LotI has no any other calls of put_to_recall_list.

I hope the Wesnoth team will fix it although I can't estimate when. It seems we have to make some workaround although I really don't know which one would be the lest ugly

**Comment by Dugy** [comment]
Maybe there could be a special area that looks like the start of the next scenario and the units would be teleported there so that `DISABLE_UPKEEP` could finish its job.

**Comment by Discontinuum** [comment]
Altering the map adding some additional place looking like that world we're jumping to? That might be a good idea
