### ISSUE TITLE
 Bad Beelzebub placement in LotI2-Where the Flames Freeze

### ISSUE THREAD

**Issue by arobinson** [Dugy/Legend_of_the_Invincibles#375]
Due to the location of the stone, it is not possible to get all the items he drops in this board. You've done a great job in other boards to give non-picked up items that are unreachable to the user at the end of the scenario, but in this level that does not seem to work.

![image](https://user-images.githubusercontent.com/93213/141530984-e8f99253-e8c0-404a-861b-e878a3b74fa3.png)

You can use the same game to reproduce the victory scenario and see no items are picked up (other than what the leader drops when you kill him).

[LotI2-Where the Flames Freeze Turn 23.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/7530260/LotI2-Where.the.Flames.Freeze.Turn.23.gz)

Thanks. Still love the campaigns!

**Comment by Discontinuum** [comment]
That sounds more like a bug of autopicking than a bad placement, as far as I remember that level, hardly there is any better place for Beelzebub, at least hardly any place with no items dropping on Unreachable

**Comment by Dugy** [comment]
I think that items are auto picked at scenario end only under two conditions:

- They dropped in the last round (no time left to pick them)
- The scenario is Jungle Hell (because there are enemies who walk through impassable and attack you from there)

Neither of those apply in your case, so they are not picked.

**Comment by Discontinuum** [comment]
The help says another:
"There's an item in the wall! How do I reach it?"
"Your thirst for loot is boundless, isn't it? It's moved into your item storage at the end of the scenario."

https://github.com/Dugy/Legend_of_the_Invincibles/blob/c4650ccd901c9a53e3eb3af0c00c8b6ee143f61a/utils/global_events.cfg#L566 the cycle checks either on the last turn or on impassable (I guess that's impassable?)

And in the Jungle Hell it gathers all items you left behind, on unreachable or reachable.

**Comment by Dugy** [comment]
Apparently, I remember it wrongly.

The problem might be here that custom terrains (that the impassable jungles and these ice walls both are) are not allowed to follow the usual naming patterns where starting with `X` means they're impassable.
