### ISSUE TITLE
Lich after Death advancement broken with Snow Hunter

### ISSUE THREAD

**Issue by arobinson** [Dugy/Legend_of_the_Invincibles#380]
I used the Necromancer book to get the "Lich after death" advancement, but the unit dies, does not convert. Could be that the event is only firing once (I already had my elf lord become a lich in this level)?

Unit is about to die, so will reproduce with this same game
[LotI2-The Den of Evil Turn 21.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/7558611/LotI2-The.Den.of.Evil.Turn.21.gz)

**Comment by Dugy** [comment]
Yeah, this is a typical problem when I forget to add that `first_time_only=no` line.
