### ISSUE TITLE
Back-up amla has a confusing description

### ISSUE THREAD

**Issue by Discontinuum** [Dugy/Legend_of_the_Invincibles#381]
It has a description "Oops, this is only temporary, or something went wrong" which is shown if you hover the mouse over the unit's level in the right bar. It's probably confusing for a player who might think that it's a bug or some other bad thing. So it would be good to give it a less scary description

**Comment by Dugy** [comment]
Whoops, I didn't know there is a UI that shows the AMLA the unit has. It definitely needs some generic information.
