### ISSUE TITLE
Troubles with units overlays

### ISSUE THREAD

**Issue by Discontinuum** [Dugy/Legend_of_the_Invincibles#383]
First of all, they create this message in the log

[unit]overlays has been deprecated and may be removed in version 1.17.0.; This warning is only triggered by the cases that *do* still work: setting [unit]overlays= works, but the [unit]overlays attribute will always be empty if WML tries to read it.

Secondly, they aren't removed when they are supposed to be removed. In 1.14 if you unequipped the item that gave you an overlay, it's removed, but in 1.16 it's not removed, it stays

**Comment by Dugy** [comment]
The wiki says that overlays are now a type of `[effect]` that is stored in `[modifications]`, creating the unit with `[unit]` will create an `[object]` there with the overlays that were set in its `overlays=` field, but the actual unit will not have any such property.

This means that they are removed from a location where they aren't stored.

I think it could be solved changing the code in `stats.lua` to create a special object for overlays and always find it and update its contents.
