### ISSUE TITLE
If you add "meteor" or "lava flow" with a great spell but don't use these attacks before the end of the scenario, your leader stats wiped before the next recalc

### ISSUE THREAD

**Issue by Discontinuum** [Dugy/Legend_of_the_Invincibles#385]
Similar to #363 but in a different version: the object is added with "scenario" duration. If you use the attack, it's deleted by LotI's code and all is okay. But if you quit the scenario, I guess the game calls [remove_object] under the hood to wipe "scenario"-long objects which causes the same erasure of stats as in #363

**Comment by Dugy** [comment]
Maybe the removal could be an end scenario event force triggered by using the attack.

**Comment by Discontinuum** [comment]
Or make named events for deleting attacks and call them both during attacking and during exiting a level
