### ISSUE TITLE
Delly_lich advancements aren't GREATER_AMLA_DEFAULT_BONUSES

### ISSUE THREAD

**Issue by Discontinuum** [Dugy/Legend_of_the_Invincibles#386]
Her amlas are usual amlas (~~and the "faster" advancement even lacks any~~ faster is the same usual amla, I just didn't notice the macro). Is it supposed to be so or should she be as other heros with GREATER_AMLA_DEFAULT_BONUSES?

**Comment by Dugy** [comment]
Hm, yeah, I think she should better have the greater version.
