### ISSUE TITLE
Vitra's earthquake in 10/01_Despair

### ISSUE THREAD

**Issue by matsjoyce** [Dugy/Legend_of_the_Invincibles#39]
[The terrain used is `Xu^Dr`](https://github.com/Dugy/Legend_of_the_Invincibles/blob/master/scenarios10/01_Despair.cfg#L383-L387) which doesn't seem to display well. Should it be switched to plain `Xu`, maybe with `Ur^Dr` on each side?
![image](https://cloud.githubusercontent.com/assets/6631310/26722146/a127f6a2-4786-11e7-9275-1b2a6fde6dc4.png)

**Comment by Dugy** [comment]
Is it visible without shroud? I thought that it looked better before.

**Comment by matsjoyce** [comment]
Initially it isn't covered by fog, but the weird cropped rubble still occurs.

**Comment by Dugy** [comment]
I agree to switch that to plain Xu then. I will do it tomorrow if you don't fix it before.

**Comment by Dugy** [comment]
Thanks for the fix.
