### ISSUE TITLE
Strange unit placed event

### ISSUE THREAD

**Issue by Discontinuum** [Dugy/Legend_of_the_Invincibles#390]
https://github.com/Dugy/Legend_of_the_Invincibles/blob/6d4a732927847aac58f0b684f7416adabba1aaf6/utils/global_events.cfg#L554-L567

Why do we need this? It's triggered only once on the first unit that happen to trigger unit placed. Luckily it seems not affecting that much but it caused a subtle bug in Kill the King on 1.14: when Calcy is modified from Calcy_early to Calcy, it happens that Calcy triggers this event, and UPDATE_STATS prevents him from changing the type. Also interesting that this bug in KtK started to appear after https://github.com/Dugy/Legend_of_the_Invincibles/commit/e88c2149276afc98d7414528835d8f192e4ac2ac It's because before the changes this event was always fired on Event Loader so it didn't affect players' units. And now, with side=$allied_sides, Event Loader created before this variable is set, so the unit placed event fires on the first unit of the player that caused unit placed.

**Comment by Dugy** [comment]
It was meant to make sure every unit would be affected by update_stats before being used. There is a macro to do it for most units appearing in the LotI campaign, but once `unit placed` was added, I added this event to make it happen automatically. However, I forgot that `first_time_only=no` and it seems that some units are negatively affected.

**Comment by Discontinuum** [comment]
first_time_only is impossible to add, as it's an eternal cycle then

**Comment by Dugy** [comment]
The event is supposed to set the `update_started` variable so that the unit would not match the filter next time.

**Comment by Discontinuum** [comment]
Even so, it seems a problem that it prevents {ADVANCE_UNIT id=Calcy Calcy} from succeeding and Calcy stuck as Calcy_early (when I placed other guys ahead of Calcy, this event made them to be bugged the same way)

**Comment by Dugy** [comment]
IIRC, ADVANCE_UNIT is just a `[modify_unit]` tag that changes the unit type. It will trigger `unit placed`, but I don't see why this particular trigger undoes the change. Also, I think it worked fine before 1.16.

**Comment by Discontinuum** [comment]
Yes, it's modify_unit after macroexpansion. No, this problem is with Kill the King on 1.14 with the current LotI

**Comment by Discontinuum** [comment]
Hm, it turns out there is a bug in LotI because of it. If in LotI 2 in the first scenario Lethalia advances, she appears as advanced but then she reappears with backup_amla. And this bug works only if this event is triggered when she advances, so she must not equip any items before it to reproduce
[LotI2-The Awakening Turn 9BadBug2.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/7653955/LotI2-The.Awakening.Turn.9BadBug2.gz)
[LotI2-The Awakening Turn 5BadBug.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/7653956/LotI2-The.Awakening.Turn.5BadBug.gz)
![изображение](https://user-images.githubusercontent.com/68666085/144710437-1cb53d95-e580-4bdb-a97b-ab5a764313cb.png)
![изображение](https://user-images.githubusercontent.com/68666085/144710462-445ec10e-5ddd-4cbe-9ccb-0f55aa0abe60.png)

**Comment by Discontinuum** [comment]
Tbh, as this event never worked and nothing was broken with that, I would just remove it. Also it needs to be either backported to 1.14 or Kill the King needs some kind of workaround for Calcy to work properly again

**Comment by Dugy** [comment]
It was easier than I thought. The `[update_stats]` tag simply wasn't setting the `update_started` variable in the unit. I think I added the `[update_stats]` tag to replace a monstrous piece of WML code somewhere during 1.14's lifetime.

**Comment by Discontinuum** [comment]
Hm, it should prevent the loop, but the event is without first_time_only=no. And will it fix the bug with Calcy and things like that with Lethalia (when the first advancement is corrupted by update stats)?

**Comment by Dugy** [comment]
I advanced Lethalia in that scenario without touching an item and she advanced correctly. I guess I should test it also for Calcy.

**Comment by Dugy** [comment]
The bug still happens in Kill the King, seems it's not fixed.

**Comment by Dugy** [comment]
It appears that `[modify_unit]` triggers `unit placed` before the unit's type is changed, causing the operation to abort and never change the unit type. Also, `unit placed` is not called if the unit exists from the start of the scenario, causing the `unit_placed` from `[modify_unit]` to happen before the first `turn refresh` event that would normally do the first `[update_stats]`.

I have changed the behaviour so that the `unit placed` event is created on the first `turn refresh`, so that no earlier `[modify_unit]` breaks it. This fixes the problem in Kill the King, Calcy properly starts scenario 1 as Skeleton Minstrel.

**Comment by Discontinuum** [comment]
Yeah, that were the core problems, this modify/unit place/already existing at the start interaction, I hope now things work as should
