### ISSUE TITLE
Lua errors when start Gladiators

### ISSUE THREAD

**Issue by Discontinuum** [Dugy/Legend_of_the_Invincibles#393]
![изображение](https://user-images.githubusercontent.com/68666085/146357585-91d32b15-b31a-4e17-8c2c-90f80dc69ba1.png)
Whether affect further game, I didn't find out, just appear on the start

**Comment by Dugy** [comment]
I broke it recently. It should not affect gameplay.

**Comment by Discontinuum** [comment]
Just in case, to inform you, Gladiators for more than 1 player for now broken because of https://github.com/wesnoth/wesnoth/issues/6285 Wesnoth 1.16 can't load custom terrains for any scenarios for non-host players. The bug is being worked on by Wesnoth dev team

**Comment by Dugy** [comment]
No, that's not related.
