### ISSUE TITLE
Legacy of fire breath - 11x4 or 14x4 damage?

### ISSUE THREAD

**Issue by akdjka** [Dugy/Legend_of_the_Invincibles#395]
Here I see a description that breathing fire does 11 damage:
https://github.com/Dugy/Legend_of_the_Invincibles/blob/03a76ac7c237753926a2d9df671841b14021de2d/utils/amla.cfg#L2147

But a few lines below I see 14. Is this a bug or is three something else going on?

**Comment by Dugy** [comment]
Yeah, the description was wrong.
