### ISSUE TITLE
Redeem with horrid always fails

### ISSUE THREAD

**Issue by Discontinuum** [Dugy/Legend_of_the_Invincibles#396]
Horrid from  Tracking the Lost Knowledge

Reported on the forums https://forums.wesnoth.org/viewtopic.php?p=669884#p669884

**Comment by Discontinuum** [comment]
The reporter on the forum traced the problem correctly: after gaining an advancement redeem special readded in the end of the list, so it's before horrid (horrid is also [damage] special). As a result, this code https://github.com/Dugy/Legend_of_the_Invincibles/blob/9929fd0778dfa2c06830c819c16ca6c2272095ee/utils/redeeming.cfg#L212-L217 operates on horrid's id and redeem level is always 0

**Comment by Dugy** [comment]
He pretty much identified the problem, so it was relatively easy to fix.
