### ISSUE TITLE
Copy / paste error in comment

### ISSUE THREAD

**Issue by akdjka** [Dugy/Legend_of_the_Invincibles#404]
The comment is incorrect, the range is 3.
https://github.com/Dugy/Legend_of_the_Invincibles/blob/49adcdf0f618c8f68566dfec0437dd49e84eff90/utils/abilities_events.cfg#L3931

Please note that the issue is repeated a little lower as well.

**Comment by Dugy** [comment]
Interesting that nobody read that comment for years.
