### ISSUE TITLE
LotI2-The Chase is unwinnable if Krux redeems Deliria

### ISSUE THREAD

**Issue by Chergnobarp** [Dugy/Legend_of_the_Invincibles#408]
Krux redeemed her at (24, 34). She ran away, but didn't reappear. I double-checked in `:inspect`, she's not hiding, she's truly gone.

**Comment by Discontinuum** [comment]
Maybe just forbid lesser redeeming of "canrecruit=yes" enemies? This was always kinda troublesome

**Comment by Dugy** [comment]
There is a list of units that are immune to disintegrate because they were not supposed to be just killed. Maybe Deliria could be added to the list and Redeem and Lesser Redeem respect it.
