### ISSUE TITLE
Lethalia cannot use staves in second part ?

### ISSUE THREAD

**Issue by alain-bkr** [Dugy/Legend_of_the_Invincibles#41]
hello

I just compiled 1.13.8 and installed LotI 3.2.0 on a new account.
I started first part, it worked nicely.
I started the second part ,and then Lethalia could not use staff found on the ground. 

I can provide a gameif needed.

Thanks for all this.
cheers
Alain

**Comment by Dugy** [comment]
Yes, please provide the save file.

**Comment by alain-bkr** [comment]
I redirected the console messagesto the  log file  attached.

[20170815.log.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/1229372/20170815.log.gz)

[LotI2-Who_Am_I_Tour_1-no-bjects-stored.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/1229380/LotI2-Who_Am_I_Tour_1-no-bjects-stored.gz)
[LotI2-The_Awakening_Tour_4-no-staff.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/1229379/LotI2-The_Awakening_Tour_4-no-staff.gz)

**Comment by alain-bkr** [comment]
Also at the beginning of the second level of the second part , the object store is mostly empty and lose many items

**Comment by Dugy** [comment]
I have seen nothing out of ordinary. No items from previous parts appear as intended. There is no unpickable staff anywhere. There is nothing interesting in the log. Everything seems to be working fine.

**Comment by alain-bkr** [comment]
Another game, saved jsut befoire trying to pick a staff, and a screenshot whith the message "this unit cannont use staves" 

wesnoth 1.13.8 , compiled on ubuntu16.04 32 bits.


---
about my previous message, i may be unclear : 
the scond part starts with 1st level "the awakening" during whihc some items are stored.
Then second level is "who am i" , where it is impossible too get back the stroed items, or they have disapeared .

**Comment by Dugy** [comment]
Aha, the version of Lethalia in early chapter 6 does not have a staff attack and she is not listed as an exception. Added that exception, so she should be able to carry a staff now,
