### ISSUE TITLE
Make Ice Wraith?

### ISSUE THREAD

**Issue by Discontinuum** [Dugy/Legend_of_the_Invincibles#415]
Probably not the most needed thing, but I think may be tried to add variety a bit, or for advanced difficulties

In 1.16 they made an advancement for Fire Guard - Fire Wraith. And Ice Spirit's sprite is a recoloured Fire Guard. Maybe we can make an Ice Wraith to be an advancement for Ice Spirit, recolouring Fire Wraith's sprite?

Although I myself don't know how to recolour sprites

**Comment by Dugy** [comment]
Okay, I made it.
