### ISSUE TITLE
several bugs with 1.13.8 and LotI_3.2.0

### ISSUE THREAD

**Issue by alain-bkr** [Dugy/Legend_of_the_Invincibles#42]
Hi

i checked again , starting from the second part in 'campaign"

I encounted several bugs : 
-  Lethalia rise level but is not healed to full HP (and stay wounded)
- Lethalia conical attack is not conical 
- Efraim raise, causes Lua errors
- trying to see Efraim unit information causes errors
- several objects stord during the first level(armour, sword,bow,armor) , are not available in the second level, (even on a castle) , only the first one seems to be stored.

I attach several screenshot, with self explaing names, showing what i did or the bug symptom.
/alain

store_staff
![al3_store_staff__2017-09-10_11-43-30](https://user-images.githubusercontent.com/31039036/30248584-e79cdc5e-962a-11e7-9116-d9d06bdb7bc7.png)

rise_level_but_no_heal_to_full_hp
![al3_rise_level_but_no_heal_to_full_hp_2017-09-10_11-46-53](https://user-images.githubusercontent.com/31039036/30248583-e7960a3c-962a-11e7-9c2b-207a2ee2c813.png)
![al3_rise_level_but_no_heal_to_full_hp_start_of_my_turn__2017-09-10_11-46-53](https://user-images.githubusercontent.com/31039036/30248586-e7a0466e-962a-11e7-86f0-05cdebec9190.png)

store_generous_armour
![al3_store_generous_armour_2017-09-10_11-57-25](https://user-images.githubusercontent.com/31039036/30248588-e7a71f2a-962a-11e7-9e8d-f083b25cf999.png)

store_claymore
![al3_store_claymore_2017-09-10_12-00-06](https://user-images.githubusercontent.com/31039036/30248585-e79f97aa-962a-11e7-8bf2-a9f28400f526.png)

efraim_raise_produces-lua-error
![al3_efraim_raise_produces-lua-error_2017-09-10_12-05-21](https://user-images.githubusercontent.com/31039036/30248587-e7a0510e-962a-11e7-8114-76d51430394e.png)

trying to see Efraim 's "unit_information" causes error
![al3_efraim_unit_information_causes_error__2017-09-10_12-11-51](https://user-images.githubusercontent.com/31039036/30248589-e7af4d30-962a-11e7-83c1-9b0160a620f3.png)

store bow
![al3_store_bow_2017-09-10_12-32-53](https://user-images.githubusercontent.com/31039036/30248590-e7b8af88-962a-11e7-9583-26e6b97a4ecb.png)

store book (ok)
![al3_store_tome_of_the_lich_2017-09-10_12-34-16](https://user-images.githubusercontent.com/31039036/30248592-e7bcbe16-962a-11e7-9a5f-2b9adab583b5.png)

store potion (ok)
![al3_store_potion_2017-09-10_12-35-11](https://user-images.githubusercontent.com/31039036/30248593-e7bcd036-962a-11e7-8234-c2ec0ef7bcea.png)

store mitral armor
![al3_store_mitral_armor_2017-09-10_12-43-42](https://user-images.githubusercontent.com/31039036/30248591-e7bbcd12-962a-11e7-8150-18cdf1dfaeca.png)

store potion (ok)
![al3_store_potion_healing_2017-09-10_12-48-04](https://user-images.githubusercontent.com/31039036/30248594-e7c0c7d6-962a-11e7-8299-9f30f094228e.png)

Next level : where are all the stored objects ?
![al3_level_2_no_item_in_storage__2017-09-10_12-50-55](https://user-images.githubusercontent.com/31039036/30248595-e7c9d7ea-962a-11e7-93d6-ed280a83b750.png)

even on a castle , object storage seems rather empty
![al3_level_2_even_on_castle_no_item_in_storage_2017-09-10_12-56-16](https://user-images.githubusercontent.com/31039036/30248596-e7d5250a-962a-11e7-9e60-ddead454cae2.png)

**Comment by alain-bkr** [comment]
Start of the seconde part of the campaign level 1 

[LotI2-The_Awakening_Tour_1_al3.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/1290460/LotI2-The_Awakening_Tour_1_al3.gz)

Conical attack from Lethalia does is not conical and does nothing to neigbours
[LotI2-The_Awakening_Tour_32_conical_attack_does_nothing.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/1290463/LotI2-The_Awakening_Tour_32_conical_attack_does_nothing.gz)

autosave a turn 70
[LotI2-The_Awakening-Sauvegarde_automatique70.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/1290459/LotI2-The_Awakening-Sauvegarde_automatique70.gz)

Second level : where are the stored objects ?

[LotI2-Who_Am_I-Sauvegarde_automatique1.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/1290461/LotI2-Who_Am_I-Sauvegarde_automatique1.gz)
[LotI2-Who_Am_I-Sauvegarde_automatique2.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/1290462/LotI2-Who_Am_I-Sauvegarde_automatique2.gz)

**Comment by Dugy** [comment]
Je vais l'examiner. Je voudrais savoir si cela se fait aussi dans part 1 ou si c'est unique pour les premiéres scénarios de part 2.

Quel advancement de Lethalia a été pris avant qu'elle n'était pas complétement remédiée?

**Comment by Dugy** [comment]
J'ai trouvé pourquoi il est impossible à voir l'information sur Efraim. C'était causé par la nouvelle version de Lua utilisé par Wesnoth 1.13.8.

**Comment by Dugy** [comment]
J'ai trouvé pourqui le 'cone' a n'y était pas. Je l'ai corrigé.

Je ne sais pas quel problème t'as avec les objects manquant. Rien ne manque pas, tous les objects sont là.

**Comment by alain-bkr** [comment]
Merci , je retesterai bientot.

J'ai le même problème avec les objets , au tableau 1
Je joint une sauvegarde avec un arc , que je stocke et qui semble dispratitre ensuite

saved game with bow in 28.15 
[LotI1-An_Orcish_Assault_Tour_5-bow-in-28.15.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/1293245/LotI1-An_Orcish_Assault_Tour_5-bow-in-28.15.gz)

screenshot before saving
![store_bow_in_28 15_2017-09-11_18-05-41](https://user-images.githubusercontent.com/31039036/30285098-494510be-971d-11e7-94b5-a0a72ed009a2.png)

I move one unit on a "castle" and the object_store seems empty : 
[LotI1-An_Orcish_Assault_Tour_5-cannot_unstore_bow.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/1293244/LotI1-An_Orcish_Assault_Tour_5-cannot_unstore_bow.gz)

**Comment by alain-bkr** [comment]
[20170911_level1_storage_trouble.txt](https://github.com/Dugy/Legend_of_the_Invincibles/files/1293254/20170911_level1_storage_trouble.txt)

**Comment by Dugy** [comment]
Je l'ai trouvé. S'il avait moins que 20 objects dans l'inventoire, ils étaient différement listés et un erreur a caché tous ces objects. Tous ces objects ne sont pas perdus, ils sont invisible. Collectioner 20 objects va le réparer sans un besoin à installer ma correction.

Est-ce que je peux fermer cette discussion?

**Comment by alain-bkr** [comment]
oui merci

je regarde comment utiliser l extension depuis github ...
