### ISSUE TITLE
Cannot win scenarios1/14_Shadow_Empire if Beelzebub is summoned but not killed

### ISSUE THREAD

**Issue by agguser** [Dugy/Legend_of_the_Invincibles#420]
In the scenario, if Beelzebub is summoned but not killed, even if you "capture Zorox with Lethalia and defeat the necromancers", you will not win; and when time run out, you are defeated.

**Comment by Discontinuum** [comment]
So, victory is assigned here in the "enemies defeated" event. As far as I understand, it means all leaders of all enemies defeated. And if Beelzebub is summoned, he is a leader of his side.

(Also, not directly related, events on https://github.com/Dugy/Legend_of_the_Invincibles/blob/a6a9fb1f263134c223d2c45f9cb592050f90cfc8/scenarios1/14_Shadow_Empire.cfg#L344 and https://github.com/Dugy/Legend_of_the_Invincibles/blob/a6a9fb1f263134c223d2c45f9cb592050f90cfc8/scenarios1/14_Shadow_Empire.cfg#L357 seem to be duplicates)

**Comment by Dugy** [comment]
Maybe defeating the three main enemy leaders without having Beelzebub killed could add 10 turns. Or the winning requirement might change to having defeated these 3 enemy sides.

**Comment by Dugy** [comment]
I changed it so that running out of time counts as if enemies were defeated if the three regular enemy leaders are dead.
