### ISSUE TITLE
Undead get the loyal icon but not the trait

### ISSUE THREAD

**Issue by Discontinuum** [Dugy/Legend_of_the_Invincibles#424]
Tarquin from the forum reports https://forums.wesnoth.org/viewtopic.php?p=676368#p676368

> I'd like to file a bug report.
Recruiting undead has a chance to give them the loyalty icon, but the loyal trait is blocked from spawning on undead.
in global_events.cfg

https://github.com/Dugy/Legend_of_the_Invincibles/blob/master/utils/global_events.cfg#L1031

> if an undead rolls loyality, this is set to 1; then a check is made if the unit is undead (it checks for a must have trait), if they have this trait, dont give them loyal. A bit further

https://github.com/Dugy/Legend_of_the_Invincibles/blob/master/utils/global_events.cfg#L1146

> They are given the loyalty icon overlay, even if they don't have loyal

**Comment by Dugy** [comment]
I made the extra traits add as extra traits rather than replace existing ones. I used the replacement approach because I didn't know to append it at the end back at the time I was writing it.
