### ISSUE TITLE
regards moving units/items from chapter 1 to chapter 2 

### ISSUE THREAD

**Issue by starryskies2** [Dugy/Legend_of_the_Invincibles#425]
hey dogi, i know this is thread for the lotl only but i hoped you could help me with the add-on that move units from one campagin to another but sadly its no longer working,any chance you c an look at to fix it?if you dont have time i will understand,thanks much! 
(eg.i absolutely loved every second of the lotl,its is so fun)

**Comment by Dugy** [comment]
I can have a look at it. Don't take it as a promise.

**Comment by Dugy** [comment]
Done. Now it is a modification that needs to be enabled. While at it, I changed it so that it should also work in multiplayer (it requires every player to enable it and will break the game if some of the players don't have the original campaign installed).

**Comment by starryskies2** [comment]
thank you so much for the quick and fast fix, i appricate it
