### ISSUE TITLE
Lesser Lich is weak (and kinda flawed)

### ISSUE THREAD

**Issue by Discontinuum** [Dugy/Legend_of_the_Invincibles#428]
Maikal from the forum https://forums.wesnoth.org/viewtopic.php?p=677483#p677483

> Does anyone build the lesser lich item that replaced deathblade's inheritance? It seems really odd for an item requiring a black pearl. Suck 2 is strong but it converts your damage to arcane which suck doesn't work with. And it hardly increases damage at all. It's like a worse version of the searing flame sword. Idk I just feel like an item requiring a black pearl should be kind of OP like marrowrend/soul render

I checked and indeed, suck 2 doesn't work for lesser lich, as it makes the damage type arcane. So it's kinda flawed or strange at least, the item has suck but it doesn't work because of this very item properties. You can make it work, actually, equipping Rationality (which turns damage to blade), but for an expensive craftable seems like a costly limitation

**Comment by Dugy** [comment]
Okay, I increased its damage a bit. I also enabled the suck effect with arcane as well, mainly because it's consistent with many units in the game that have arcane attacks with drain. I wonder if it won't cause some balance problems.

**Comment by Discontinuum** [comment]
I wonder, to be honest, why this limitation (suck works only with physical types) was put in the first place. By the way, you enable it for arcane only on defense, on offense there is a separate event

**Comment by Dugy** [comment]
I think I prevented it from working with fire, cold and arcane because I thought these damage types were already more powerful because of going through the resistances of units with armour.

And I fixed the offense part. Earlier, I changed the defence part, started looking for the offence part, then forgot about it and went to add a damage bonus to that craft.

**Comment by Discontinuum** [comment]
One more thing, need to correct the code that generates unit descriptions 
https://github.com/Dugy/Legend_of_the_Invincibles/blob/876b1d32736a8c07ac48bb0029d6894b1cab443a/lua/main.lua#L438
It doesn't show suck for attacks of non convenient types, need to add arcane there as well

**Comment by Dugy** [comment]
Done.
