### ISSUE TITLE
Wrong physical resistances in descriptions of crafted armours; highlighting of set bonuses for set items you have stopped working

### ISSUE THREAD

**Issue by Discontinuum** [Dugy/Legend_of_the_Invincibles#429]
Defensive Stance should give +10% phys res if it's armour and +3% if it's helmet/boots/gauntlets. But the description in the master branch is broken: it always shows 3%. 

Also, when you had several items from a set equipped, the set bonus info string in the description was highlighted bold for items you have. It stopped working.

I bisected and found that both broke down in 142c1d423d68af54e75328dca83b19f6eb81e03e @edwardspec wondered in the commit description why to reset what `[describe_all_objects]` did. It seems it was for this:  `describe_item` logic is to return a precalculated description if there is one. `[describe_all_objects]` precalculated descriptions for all items, including craftables and items with set bonuses. And as the commit stopped clearing this, descriptions are never recalculated for craftable armours/set bonus items.

But I must note that the old logic seems confusing as hell to me as I try to unravel it. So at the start of a scenario in  {GENERATE_ITEM_LIST} `[describe_all_objects]` precalculated descriptions, then descriptions for armours and weapons were immediately deleted by `[clear_item_list_cache]`. But why precalculate then if it's cleared after?

**Comment by Dugy** [comment]
I think the problem was that something was behaving counter-intuitively and edwardspec's commit cleaned up some unnecessary stuff and the viewing of item descriptions was relying on it as some kind of optimisation, skipping the generation of the item's description even if there was a need for it.
