### ISSUE TITLE
side panel does not show "focused" property or other special effects of weapons

### ISSUE THREAD

**Issue by alain-bkr** [Dugy/Legend_of_the_Invincibles#43]
Hi

Delenia has a knif "rigor mortis" , witch gives weapon special "focused"

This is not shown on the right side panel , but i  think it works during game play (the kniwes are focused))

A screenshot :
![knife-gives_focus_or_not_2017-09-12_17-21-16](https://user-images.githubusercontent.com/31039036/30771151-e1bcf380-a040-11e7-8ed3-eff59475674b.png)

And the corresponding saved game 
[LotI1-Paradise_Lost_Tour_1.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/1326353/LotI1-Paradise_Lost_Tour_1.gz)

Running on 1.13.8 and 
$ git log | head
commit 7ae73cb10409433eb17803aff75da1171c2cf382
Author: Dugy <jan.dugacek@gmail.com>
Date:   Tue Sep 12 01:29:10 2017 +0200

    Items are now visible in inventory if the inventor contains less than 20 items.

It is the same with "konrad might"
cheers

**Comment by Dugy** [comment]
These weapon specials are attack-only and are not shown on the right panel because they are not active when choosing unit movements.

Please check if they show in the attack choosing window or in the unit information panel. If they don't, it's a regression.

**Comment by alain-bkr** [comment]
ok 
before these properties where always shown, it could be cool to see that again (maybe other color, or italic font or...)

While testing i have an lua error message showing up on the map , when the orcs move to attack my units

20170923 12:46:14 error scripting/lua: ai/micro_ais/cas/ca_fast_move.lua:109: variable 'm' must be assigned before being used
stack traceback:
	[C]: in function '.error'
	lua/ilua.lua:132: in metamethod '__index'
	ai/micro_ais/cas/ca_fast_move.lua:109: in function <ai/micro_ais/cas/ca_fast_move.lua:107>
	[C]: in function 'table.sort'
	ai/micro_ais/cas/ca_fast_move.lua:107: in field 'execution'
	[string "local self, params, data = ......"]:2: in main chunk

Nothing is ever displayed about focus ,
![not_focused_2017-09-23_13-10-47](https://user-images.githubusercontent.com/31039036/30772703-879735fc-a061-11e7-86b1-d03620ed0002.png)

 and the percentag shown stay at 60% (but maybe this part does not know Loti)
![not_focused_still_60_percent_2017-09-23_13-11-36](https://user-images.githubusercontent.com/31039036/30772704-8ddd6f44-a061-11e7-9dec-e64596a8ba46.png)

A saved game : 
[LotI1-Paradise_Lost_Tour_4_not_focused_delenia.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/1326492/LotI1-Paradise_Lost_Tour_4_not_focused_delenia.gz)

**Comment by alain-bkr** [comment]
few turns later
 
put delania on 21,13 to use knives on orc in his camp (60%defense)
= > i think the knives are not focused
I tried 5 times (the atteck is 3 knives) from the saved game, and the wolf was hit only by 4 knives out of 15.
[LotI1-Paradise_Lost-Sauvegarde_automatique6.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/1326505/LotI1-Paradise_Lost-Sauvegarde_automatique6.gz)

**Comment by Dugy** [comment]
Because Konrad's Might has marksman and it disappears, it's a change in 1.13. I did not implement marksman, it's the same marksman as Elvish Marksman line units have (it should also be invisible if inactive). I can change it, but I would receive more reports that it behaves differently than core units.

The lua error is an AI problem and the AI used is a part of the game. However, it's a specialist AI that is used extensively in LotI and not much elsewhere, so it's likely that it's not sufficiently tested.

**Comment by alain-bkr** [comment]
I believe the weapon special properties does not work  (like focus above) , and are not shown in the side panel (which may be logical if the porperty is not taken into account)

Attached an aotehr game, with 1.13.9 

The skeleton archer ***should*** slow , but the slow property is not shown, and it does not work.
For Efraim , the 'slows' property is shown and it works.
(both are near the demon)


so i believe , the weapon special effects are not taken into account  (focus , slow .. ).

[LotI2-Into_the_Light_Tour_3-slow-or-not.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/1347039/LotI2-Into_the_Light_Tour_3-slow-or-not.gz)
![slow_special_not_taken_into_account_2017-10-01_11-12-23](https://user-images.githubusercontent.com/31039036/31053436-60318480-a69d-11e7-96b2-237a8b55b823.png)

**Comment by Dugy** [comment]
I can replicate it. It definitely looks like a bug. The weapon specials received from item sets are implemented differently and should work.

**Comment by Dugy** [comment]
Fixed it. It was a part of a series of bugs introduced when trying to fix the stupid change of definition of the FOREACH macro.

**Comment by alain-bkr** [comment]
It does not work for me on 1.13.9, I erased all the caches, and git pull the latest LotI : 

* with the provided save game, delenia hit is 9 out of 30 knives, which is more or less 40% , not 80%

**Comment by Dugy** [comment]
It will persist until you start a new scenario, then unequip the item and then you equip it again.
