### ISSUE TITLE
Side story campaigns do not have added unit advancement paths

### ISSUE THREAD

**Issue by matsjoyce** [Dugy/Legend_of_the_Invincibles#435]
LotI has a macro `LOTI_EXTRA_ADVANCEMENT_LINES` in it's _main.cfg, while The Beautiful Child and Affably Evil do not. This results in normal units like Elvish Sharpshooter going into the normal AMLA cycle, not progressing into the LotI added unit types. Is this intentional? (I would submit a PR, but those campaigns aren't on GitHub IIRC)

**Comment by Dugy** [comment]
Okay, so I created a `spinoffs` subfolder and put these campaigns there (I set the folder to be ignored by the server). Then I fixed this bug.
