### ISSUE TITLE
Units in the recall list  seems "GEARED" even after being unequiped

### ISSUE THREAD

**Issue by alain-bkr** [Dugy/Legend_of_the_Invincibles#44]
Hi

right click >
items
Show items on unit on the recal list
choose one and unequip all

then in the recall list the unit seems to still have its items and be geared 
![unit_seems_geared_when_its_is_not_2017-09-12_17-32-30](https://user-images.githubusercontent.com/31039036/30771243-ccd3864e-a042-11e7-8ab4-4202c4424077.png)

In this example, the archer has nothing, and the sword is now Delenia's, as we can see in the right side panel
cheers
/alain

**Comment by matsjoyce** [comment]
Seems to be a regression: https://forums.wesnoth.org/viewtopic.php?f=8&t=32384&p=594232#p594232

**Comment by Dugy** [comment]
If I recall correctly, I never found the cause of this bug.

It's possible that it's caused by an item that can't be removed (potion, book) and is thus it's not a bug. Can you confirm that the unit is not affected by an unremovable item?

**Comment by alain-bkr** [comment]
The unit have nothing else.

Also after recalling the unti it still show in the ride panel the *name* of the "removed" weapon, ut do not tak it into acccount.

In order to fix the display , i do "unequip all" (even if the unit has no object) and then the display in the side panel is correct.

**Comment by Dugy** [comment]
You mean like unequipping the items one by one does not remove it, but uniquipping them all at once removes it?

**Comment by alain-bkr** [comment]
unequiping is ok

but to fix the wrong ***display*** that occurs if the unit is unequipped while in the recall list (and not in game) , then i need to "unequip all" again 

like if the names were in some kind of cache or something.

**Comment by Dugy** [comment]
I think that this is quite an old bug I forgot to fix. I'll look at it. Please leave this open.

**Comment by alain-bkr** [comment]
I stepped onto this bug again.
I think objets are NOT desactived.
It seems that they just go back in the inventory, but the bonuses are still granted.

It provides an easy way to "cheat" , by moving the object between characters (wandering boots ...).

**Comment by Dugy** [comment]
I have not fixed it yet, sorry.

**Comment by alain-bkr** [comment]
provided game : 
The character named "Rhuller" , still have the bonus given by the boots (+2mv) , whereas it was unkipped when it was not recalled.

[LotI1-Banished_Tour_15-Rhuller-still_has_6mv.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/1569539/LotI1-Banished_Tour_15-Rhuller-still_has_6mv.gz)
