### ISSUE TITLE
Craftable armour description reporting 1/3 physical resistances

### ISSUE THREAD

**Issue by Chergnobarp** [Dugy/Legend_of_the_Invincibles#441]
The value doesn't change when switching from armour to boots in the crafting dialog. This affects the UI before, during and after crafting. However, the unit information dialog is showing higher resistances for crafted armour than the same crafted boots.

**Comment by Discontinuum** [comment]
We had #429 , seems it wasn't resolved?

**Comment by Chergnobarp** [comment]
Crap, I should've checked for closed issues. I'm using the stable build, so I assume that the fix hasn't made it there yet. I am seeing both issues mentioned in #429.
