### ISSUE TITLE
maybe fixed : gems are kept from part 1  to part 2

### ISSUE THREAD

**Issue by alain-bkr** [Dugy/Legend_of_the_Invincibles#45]
hi

I am not sure this is still the case. i did this a long time ago.
/!\ SPOIL /!\
At the end onf part one, Efraim and Lethalia more or less die , and awake in part two without any objects.

But  the gems were still available.
So i cheated (oh!) i came back to the end of part one, destroyed all items of all units , and got a significant amount of gems for starting the second part "the awakening")

/alain

**Comment by Dugy** [comment]
This is impossible. These are two separate campaigns.

**Comment by alain-bkr** [comment]
ok then it is fixed (but i am sure i did this when it was 10 chapters.. several years ago)

**Comment by Dugy** [comment]
I mean that there's absolutely no way how this could happen. If this was to happen, I would have to specifically code it to happen and I have not. You must remember wrong.

**Comment by alain-bkr** [comment]
ok i trust you :)
sorry for this false report.
