### ISSUE TITLE
loyal or not or faithfull ?

### ISSUE THREAD

**Issue by alain-bkr** [Dugy/Legend_of_the_Invincibles#46]
hi

1/ In the recal list , some unit's icon have a golden mark on top left  (golden ring ?) and i believed it was for loyal units,but it is pérsent for many untis , i don't know what it means. 
In the english screen shot below, the first unit on the recall list does not have one, but the others do.

2/ i think there is a typo somewhere about the "loyal" trait , or two different translations or ...

In french the are 2 translations : 
- loyal   (loyal in english)
- fidèle  (faithful in english)

for both i have the explaination "no upkeep"

By default i run games in french -> i have  "fidèle" or "loyal"
![fr_fr utf8 fidele_ou_loyal__2017-09-12_17-36-43](https://user-images.githubusercontent.com/31039036/30771537-39096f3e-a04a-11e7-8633-527515d3486b.png)

But if i start the game with 
LANG=en_US.utf8 ./wesnoth    -> i have only "loyal" for both units
![en_us utf8_loyal_for_both_2017-09-23_10-17-39](https://user-images.githubusercontent.com/31039036/30771540-40578d16-a04a-11e7-8176-2015afcdbc6d.png)

The saved game :  
[LotI1-The_Assassination-Sauvegarde_automatique1.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/1326401/LotI1-The_Assassination-Sauvegarde_automatique1.gz)

/Alain

**Comment by Dugy** [comment]
The randomly added loyal trait (new recruits have a 2% chance of being loyal) had an untranslatable name. Fixed it.
