### ISSUE TITLE
Change some abilities with AOE damage to animate=yes

### ISSUE THREAD

**Issue by Toranks** [Dugy/Legend_of_the_Invincibles#460]
I've noticed that  [harm_unit_loti] supports animate=yes, and that the default option is animate=no same as the original [harm_unit}

So my request changes to the title thing.
**Whirlwind** of Efraim is my first request, in principle. I'll see how it looks in other skills. I've added animate=yes to my own copy to see how the abilities look.

~~As the description says, this function causes units to suddenly disappear, in an unsightly way. It would be nice to animate unit deaths when this happens. I have no idea about animation in lua.~~
~~An example can be seen using whirlwind special on any weapon with that.~~

~~File: main.lua line 94~~
~~function wesnoth.wml_actions.harm_unit_loti(cfg)~~

**Comment by Dugy** [comment]
I worry this could make large AoE attacks annoying, pausing the attack for a few seconds after every hit to animate all the enemies dying from it.

**Comment by Toranks** [comment]
Read the first comment, I've edited it and the title. I have seen that then it is an aesthetic and practical change. If someone finds it uncomfortable they can press "shift" to speed up the deaths, but I find it more pleasant to see the death and wound animations to better control what is happening as well.

**Comment by Toranks** [comment]
I've noticed that it can drag out combat a bit when multiple units have whirlwind and fully surrounded, so I'm closing this, and for anyone who'd rather change it in their game, it's as simple as adding animate=yes, which is what I will do. I think it is not suitable for "most" players to see the animation of each individual wounded.
That only death is animated and not individual hits, I guess it requires too complex a code, at least I have no idea.
