### ISSUE TITLE
Give a name to the Lich on Chapter 3 Scenario 1 

### ISSUE THREAD

**Issue by Toranks** [Dugy/Legend_of_the_Invincibles#466]
The unit is generated with its "title" but without the name, with an empty space at the beginning. That looks like a mistake.

**Comment by Dugy** [comment]
The title-generating code is supposed to give the unit a generic name in case if there is no name to attach the title to, but I can't find the code for that anywhere. So I gave that lich a name.

**Comment by Discontinuum** [comment]
The name generating code works only for max leveled units. I noticed that, when you have a Revenant leader, for example, it has a title but no name

**Comment by Dugy** [comment]
Ahaaaa... that's what I was missing.

**Comment by Toranks** [comment]
@Dugy the same happens to the Lich in chapter 3 scenario 7 End of all hopes

**Comment by Dugy** [comment]
Okay, I changed the logic that assigns the name to a nameless unit, now it happens exactly when giving a title to a nameless unit.

**Comment by Dugy** [comment]
Yes. I don't think I ever intended to give names to the usually nameless units, except for cases when they were eligible for a title.

On the other hand, we can change it if you disagree.
