### ISSUE TITLE
error config: Multiple [unit_type]s with id=Orcish Nightblade encountered.

### ISSUE THREAD

**Issue by alain-bkr** [Dugy/Legend_of_the_Invincibles#47]
I just start wesnoth > campain > LotI 1 
then quit the game as sson as possible (beginning of the tutorial)

There is one *error*in the log (see below)
I checked that my installation is clean , but i may have missed something.
I "grep" into the directories and did not  find any duplicate id in LotI extension , but currently i understand nothing in wesnoth or LotI code :-)

al3@servolant:/home/Big/Games/wesnoth-1.13.8/build$ ./wesnoth 2>&1 | tee start_part_1.log
Battle for Wesnoth v1.13.8
Started on Sat Sep 23 11:47:18 2017

Automatically found a possible data directory at /home/Big/Games/wesnoth-1.13.8/build/..

Data directory:               /home/Big/Games/wesnoth-1.13.8/build/..
User configuration directory: /home/al3/.config/wesnoth
User data directory:          /home/al3/.local/share/wesnoth/1.13
Cache directory:              /home/al3/.cache/wesnoth

Setting mode to 1680x1050
Checking lua scripts... ok
20170923 11:47:36 warning wml: [campaign] difficulties,difficulty_descriptions= is deprecated. Use [difficulty] instead
20170923 11:47:42 error config: Multiple [unit_type]s with id=Orcish Nightblade encountered.
al3@servolant:/home/Big/Games/wesnoth-1.13.8/build$

**Comment by alain-bkr** [comment]
oh i found it , in the main wesnoth_1.13.8 : 

./data/core/units/orcs/Nightblade.cfg
    id=Orcish Nightblade

**Comment by Dugy** [comment]
Part of the problem is that version 1.13 added Orcish Nightblade who is in LotI since 1.10. That means that there are two of them.

Fixing this would cause compatibility problems on 1.12, so I will fix this when 1.14 comes out.

**Comment by alain-bkr** [comment]
Hi Dugy

ok 

doing the same with part 2 (= just load , start and quit) , shows an other error message : 

Checking lua scripts... ok
20170923 12:20:57 warning wml: [campaign] difficulties,difficulty_descriptions= is deprecated. Use [difficulty] instead
20170923 12:21:03 error config: Multiple [unit_type]s with id=Orcish Nightblade encountered.
20170923 12:21:21 error engine: failed to auto-store $second_unit at (-999,-999)
20170923 12:21:21 error engine: failed to auto-store $second_unit at (-999,-999)

i can do another issue if you prefer t keep problems separated.

**Comment by Dugy** [comment]
Yeah, this will happen everywhere, even in campaigns that use LotI resources like _Affably Evil_.
