### ISSUE TITLE
Fix cumulative leadership (considering Wesnoth bug)  must be remain like now?

### ISSUE THREAD

**Issue by newfrenchy83** [Dugy/Legend_of_the_Invincibles#472]
Now that the bug concerning the ability of values in leadership to be cumulated is fixed by https://github.com/wesnoth/wesnoth/commit/f6c95611494bacdd5ef4f129508a87b36559b32f , can we consider reversing https://github.com/Dugy/Legend_of_the_Invincibles/commit/cde4796207c93d606efe6cccc3f60b64c240a25f for wesnoth version 1.18?

It depends on how ABILITY_EXTRA_DAMAGE_AURA and Legacy of Kings work, were these [leadership] designed to stack on their own (two Legacy of Kings exercised on the same unit stack) or should they be stacked with others different leadership (two Legacy of Kings on the same unit count as one but one Legacy of Kings and one leadership with another id add up)?

**Comment by Discontinuum** [comment]
1.18 isn't going to be released any time soon, is it?

**Comment by Discontinuum** [comment]
https://wiki.wesnoth.org/1.17_Roadmap says 1.18 will be next year. As it's not fixed in 1.16, the current stable, we should keep until 1.18 becomes new stable

**Comment by Dugy** [comment]
If we want to be perfectionists, we can wrap all changes done by cde4796 into an ifdef block that undoes them for versions above 1.16.
