### ISSUE TITLE
Sometimes an item appears without event to pickup them

### ISSUE THREAD

**Issue by Toranks** [Dugy/Legend_of_the_Invincibles#475]
(Rewritten several times trying to figure the cause xD)
For now, it is not reproducible. But it seems that there is a situation in which the item appears with an image but the event to pick it up is not generated.

https://github.com/Dugy/Legend_of_the_Invincibles/assets/40789364/7b224f0a-2629-4469-b816-3c18534d3ffc

**Comment by Dugy** [comment]
I didn't know they couldn't be picked. What is the simple solution you're suggesting?

**Comment by Toranks** [comment]
I've been looking where it's defined, but it's in Lua and I don't quite understand the mechanism, but if a unit can get on top of the item, it should be able to pick it up, without further checking.

**Comment by Discontinuum** [comment]
Why does it even matter what terrain a unit is on to pick up an item? I don't really believe the picking event has something to do with terrain...

**Comment by Toranks** [comment]
Wait, this is a Wesnoth problem and LOTI is not the cause? Then this is a bug...

**Comment by Discontinuum** [comment]
On 1.16 I didn't manage to repro. This save, the item's on a bridge, still you can pick it up as you should
[LotI1-Gehenna Turn 15ItemOnBridge.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/11468208/LotI1-Gehenna.Turn.15ItemOnBridge.gz)

**Comment by Toranks** [comment]
Your savegame works for me in 1.17
[LotI1-Gehena Turno 19 impassable item.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/11468242/LotI1-Gehena.Turno.19.impassable.item.gz)

I'm posting mine here to find out what happened. Maybe it only happens with crafting items, and not weapon/armor items?

**Comment by Dugy** [comment]
I don't know what happened, but the `loti.item.on_the_ground.add` lua function from `lua/items.lua` should place an event to the location and the event should be triggered by walking your unit on it. It looks like the event isn't there in the video (you can check it by looking for something with those coordinates in the save file). The creation of the event does not care about the terrain, it should be placed even into impassable walls if that is where the enemy dies. The only part where the terrain matters is the end-of-scenario autocollection of items on impassable hexes.

Also, that terrain where the problem happened is UNWALKABLE/cave, not impassable, and items on unwalkable terrain are not automatically picked up. It's fairly common to be attacked by a flying unit from unwalkable chasm, see it drop an item and send a flying unit to recover it.

**Comment by Toranks** [comment]
Actually that's what I wanted to say. It was a language problem, I said it wrong.

**Comment by Dugy** [comment]
Well, the wording implied as if it had something to do with the effect that items on impassable terrain are autopicked at the end, but now it's clear it has nothing to do with it. Just that sometimes, the item can't be picked, but unless you upload a save file where it can be replicated, there's no clue that could be used to reproduce it.

**Comment by Toranks** [comment]
I put it in my comment above

**Comment by Toranks** [comment]
One thing I didn't know is that items in chasm weren't automatically picked up at the end of scenario. I realized when you told me and saw the code.

**Comment by Dugy** [comment]
The event for pickup when stepping on that hex is missing. Any idea how the item came to appear there? Did something out of ordinary happen afterwards?

**Comment by Toranks** [comment]
The item was spawned when a simple footpad died. The only special thing there can be is that I attacked him with a unit with disintegrate (Stormrider).

**Comment by Dugy** [comment]
I tried to replicate it by killing enemies with 50% drop chance using Stormrider with Doombringer with an edit causing disintegrate to have a 100% chance to kill and I didn't see any problems with picking up items they dropped.

**Comment by Discontinuum** [comment]
[LotI2-Test Scenario Turn 1ItemsBeingUnpickable.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/11469371/LotI2-Test.Scenario.Turn.1ItemsBeingUnpickable.gz)

I don't know if it's the bug Toranks has but I've found a real bug that is there. In this save there are two hexes with items: the first item dropped on 21,2; the second item dropped on 2,12. The id of event for the first item is "ie212" https://github.com/Dugy/Legend_of_the_Invincibles/blob/bb3986aff0482eedf6ebf57af7fde128f7d495ff/lua/items.lua#LL407C4-L407C4 , for the second it would've been the same and the event wasn't created

**Comment by Dugy** [comment]
All right, you've figured it out. The rewrite of some parts of the code into lua has introduced a regression.

Previously, the events would be named `ie21|2` and `ie2|12`, but the separator was not transferred, probably because it wasn't very visible in the code or looked like if it served some other purpose. These tags exist to prevent having more events at the same hex, which would result in multiple pickup prompts for each item if there were multiple items on the same hex.

**Comment by Toranks** [comment]
Oh wait. | is a valid character? Wouldn't it be better to use _?

**Comment by Discontinuum** [comment]
I think it's working fine even with |

**Comment by Toranks** [comment]
Ah, ok, you are right

**Comment by Dugy** [comment]
There is still some old code that uses the `|` separator.

**Comment by Toranks** [comment]
I confirm that in 21,3 there was another object on my scenario, so it's the same error. (2,13 - 21,3)
