### ISSUE TITLE
WML warnings equipping Rationality gloves on Death Knight

### ISSUE THREAD

**Issue by Toranks** [Dugy/Legend_of_the_Invincibles#476]
Is the mainline Death knight evolved from a walking corpse.
This error shows a line every time I equip or un-equip any boot.
![imagen](https://github.com/Dugy/Legend_of_the_Invincibles/assets/40789364/e6484ee8-a709-45f7-bee9-b01d0619dd7c)
I don't know the cause or effect (seemingly harmless), so I'm leaving it as an issue here in case anyone knows where it came from.

**Comment by Dugy** [comment]
I can't replicate it. Can there be some other conditions under which it happens? Specific boots, specific other gear, specific advancements, specific scenario...?

Btw, _advertencia_ means _warning,_ not_error,_ or am I guessing wrong?

**Comment by Toranks** [comment]
I finally managed to replicate it. It is the "Rationality" object, a glove. I was following a false lead. Also, I have tried those gloves on other units and that message does not appear.

**Comment by Toranks** [comment]
And yes, it is a "Warning". It's not a bug and it doesn't break anything.

**Comment by Dugy** [comment]
I am still not able to replicate it, I got a Death Knight, gave him Rationality and random boots and no warnings.

**Comment by Toranks** [comment]
Try on debug mode

**Comment by Toranks** [comment]
Ok, it only happens with my death knight evolved from walking corpse. It does not happen with death knight mainline or loti (both created with debug mode). It's a very rare edge case, and doesn't seem to have any real effects, so if you're okay with it, I'll close it as a not planned.

**Comment by Dugy** [comment]
Can you upload the save file? It might help find the problem, I suspect it might not be confined to this very specific situation.

**Comment by Toranks** [comment]
[LotI1-Persiguiendo dragones Death Knight.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/11512546/LotI1-Persiguiendo.dragones.Death.Knight.gz)
