### ISSUE TITLE
Possible debug msg left in

### ISSUE THREAD

**Issue by matsjoyce** [Dugy/Legend_of_the_Invincibles#48]
Is the message at https://github.com/Dugy/Legend_of_the_Invincibles/commit/7ae73cb10409433eb17803aff75da1171c2cf382#diff-c96b7e7c6e9682cc21efebc7d30d78ffR1151 meant to be there? I checked the item list, and nothing looks wrong...

**Comment by Dugy** [comment]
The initialisation of the _i_ variable is what I wanted to add. I left that debugging message there by accident. I added a fix now.

**Comment by matsjoyce** [comment]
OK, no problem. I am converting a campaign to use LotI and I thought that might have been a warning message for a mistake I made.

**Comment by Dugy** [comment]
Nope. Most occasions when NARRATOR_MESSAGE appears is a print I accidentally left somewhere.
