### ISSUE TITLE
Changing the language to Deutsch does not change the language of the maps

### ISSUE THREAD

**Issue by Toranks** [Dugy/Legend_of_the_Invincibles#496]
I wanted to make the map in Spanish and I tried to change the language to German, but the map of antediluvian tunnels is still in English. Right now I don't know how to fix that, since I've never done image translation. If someone knows the method, please tell me.

Edit: Wiki says:

> Once the localized image is made, putting it to work is simple. If the path of the original image in the source tree is:
> 
> foo/bar/baz/image.png
> 
> then the localized image should be put in:
> 
> foo/bar/baz/l10n/ll/image.png

And in theory it is like this and it should work, but it doesn't. So it's possibly a bug.

**Comment by Dugy** [comment]
I think it has something to do with the map picture being saved so that it could be updated as you discover individual areas. Therefore, the language of the map depends on the language you had set when you entered Chapter 9.

**Comment by Toranks** [comment]
I have the Deutsch map in the Spanish folder, and it still doesn't appear in Deutsch, even if I start a scenario from the beginning. The antediluvian tunnels are from chapter 5, by the way. I haven't tried the 9 yet

**Comment by Toranks** [comment]
LOL
The problem is that the original is jpg and the translation is png. It is recommended to use png. 
I'm going to make the map in Spanish in png and send the original in png, seem to you?

**Comment by Toranks** [comment]
Chapter 9 maps works, both original and deutsch translation are in png

**Comment by Dugy** [comment]
Thanks for fixing it.
