### ISSUE TITLE
When two characters try to apply penetration, the least value applies, so the bigger value doesn't work 

### ISSUE THREAD

**Issue by IamTechknow** [Dugy/Legend_of_the_Invincibles#5]
Let's say two characters with different values of arcane penetration are next to a demon, so it has 60% arcane resistance.

My first unit has 10% arcane penetration while my second character has 58% (Lethal Axe, Ring of Deathaura, 3 items from Unsung set). But for some reason when the two units are next to each other, only the 10% penetration applies, but when that character moves away then the 58% penetration applies. Shouldn't the penetration stack, or the bigger value chosen?

This issue is not about the conviction ability, it is applied independently I think.

**Comment by Dugy** [comment]
I have no control over the way the resistances and penetrations stack. The game was made so that the prevailing value is the one whose numerical value is greater, and -10 > -58. I can't change and can't figure a way around it that would not be extremely unstable.
