### ISSUE TITLE
focus weapon does not work

### ISSUE THREAD

**Issue by alain-bkr** [Dugy/Legend_of_the_Invincibles#50]
I don t know how to reopen #43 where i added one comment

The focus of Delenia's knives does not work, on 1.13.9 , with the latest LotI

It does not work for me on linux, 1.13.9, I erased all the caches, and git pull the latest LotI :
git log :

commit f216bea
Author: Dugy jan.dugacek@gmail.com
Date: Mon Oct 9 10:47:30 2017 +0200

Tested with the previously provided saved game for #43 , Delenia hit is 9 out of 30 knives, which is more or less 40% , not 80% as it should be for focused knives

**Comment by Dugy** [comment]
See #43 .
