### ISSUE TITLE
Configure Autorecall - shared?

### ISSUE THREAD

**Issue by white-haired-uncle** [Dugy/Legend_of_the_Invincibles#508]
Chapter 5 and 9 both have a configure autorecall menu, which is effectively identical AFAIK (the only thing I see is they exclude different units in a store_unit).

Any reason not to merge these into utils/autorecall.cfg?

**Comment by Dugy** [comment]
No reason. I wrote that code before I started studying CompSci.

**Comment by white-haired-uncle** [comment]
Done
