### ISSUE TITLE
Charging backstab is broken

### ISSUE THREAD

**Issue by matsjoyce** [Dugy/Legend_of_the_Invincibles#53]
The ability definition uses `backstab=yes` and [the wiki says](https://wiki.wesnoth.org/AbilitiesWML#Common_keys_and_tags_for_specials_with_a_value) `backstab: if set to 'yes', this special will only apply to the attacker`. This should be fixed in 1.13 by https://github.com/Dugy/Legend_of_the_Invincibles/commit/92e57346199067f494fdae9d2c7bc1b0b300ad1e, but the nessecary WFL functions are not defined in 1.12. As a solution for both 1.12 and 1.13 we could use the LUA functions from https://github.com/wesnoth/wesnoth/pull/1806/commits/5109a36b5674a3ba990e276309d555590417e1bc

**Comment by Dugy** [comment]
I suggest to let it be. Version 1.14 is coming soon.
