### ISSUE TITLE
I haven't been using redeem

### ISSUE THREAD

**Issue by white-haired-uncle** [Dugy/Legend_of_the_Invincibles#534]
So I get to ch08s03 United.  Both E&L have redeem(3), and unit info shows they have each taken health and regeneration.  I take the upgrade and now he has health/regeneration/leadership, she has health/regeneration/heals, and both show redeem(5).

Looking at the code, it appears that if you have less than 5 redeem upgrades, and you choose to do so, it gives you enough to bring you up to 5 upgrades, but it just gives you the same upgrade over and over (for example, she probably has health/regeneration/heals/heals/heals).  Is the intended behaviour? 

If it is, and repeating heals multiple times is just intended to fill up those slots, then this is a horrible deal (especially if she already has heals, if that's possible), as there are tons of low level units to redeem in the next few scenarios.  But if it's not, and you're supposed to get enough real upgrades to get you to 5, it's too good a deal to believe.  Hence my confusion.  Based on the dialog, I think it's working as intended, but I had to read that over several times to come to that opinion.

And BTW, does the unstore need to be within the while loop?

I suspect Ch9,S1 has the same "issue".

thanks

**Comment by white-haired-uncle** [comment]
Hmm.  Got to Ch9.  L had 4 upgrades (according to Unit Info), both redeem(4) and redeem(5), and was given the choice.  E had 5 upgrades, redeem(5) twice, and was not.  I don't remember if I took the upgrades in ch8 or not.  I wonder if I did, and they account for the double redeem values.  I also wonder if E should have been given the choice, or if something about taking the upgrade in ch8 with fake upgrades (leadership 3 times) is messing up the count when you get to ch9.

**Comment by Dugy** [comment]
I think this part of the code was totally neglected for years. Redeem was changed to have a nice GUI, this was even backported to an ancient iOS version, but this part was overlooked, so it may look ugly.

However, this was not meant to compensate for negecting redeem. It was meant only to handle the problem that at some point, there might be so little level 1 enemies that redeem becomes nearly impossible to advance.

**Comment by white-haired-uncle** [comment]
Okay, I think I understand what it's supposed to do (raise redeem level to 5 (or 7 for ch9) so you can redeem higher level enemies (and/or more at a time), but at the cost of not earning any more advancements until you have enough redeems that you would have reached level 5 (or 7) on your own).

If I got that, it's a horrible decision to take it.  Both of those scenarios have plenty of imps to practice on.

Also, what ever it's supposed to do, I don't think it's doing it right.

I enter United with both E/L showing two upgrades and redeem(3).  They both show Redeem Score: x/y in Unit Info.  Decline the offer, all seems well.

Take the offer, both get one upgrade and redeem(5), 3 upgrades and Redeem Score: x/y in Unit Info.  On turn 2, L redeems 5 imps, chooses the absorbs amla path unlock (not supposed to happen, I think), her Redeem Score disappears from Unit Info, and she now shows redeem(4)+focused and redeem(5)+focused.  Ouch.

He redeems 1 imp on turn 3, and the only thing that happens is his Redeem Score: x/y in Unit Info shows one more redeem.

As I've been looking into this, I've noted a few things, probably just from parts of the code getting updated while others didn't.  I want to record them while I'm thinking about it.

1) There are multiple places in the code where the redeem level is determined by counting upgrades using pages of wml.  This could be (and I have) implemented much cleaner in lua, and centralized.

2) An array of the upgrades already exists in util/redeem.cfg (which, of course, I found after creating my own).

3) The count even appears to happen during every redeem attack.  Worse yet is it also calculates max_redeem_count every time using an iterative calculation  (I just pre-calculated them and stashed them in an array, not being able to derive a formula that would take upgrade count and calculate max_redeem_count directly).  You wouldn't think this little bit of math would make a difference with a modern CPU, but redeem is really slow some times compared to other attacks.

4) As I rather suspected, and hoped, it's probably not necessary to count upgrades all the time.  For example, Efrstore.attack.specials.damage.id="redeem 5".  See also Efrstore.variables.redeem_count and Efrstore.variables.max_redeem_count.

**Comment by Dugy** [comment]
If you want to convert all that code into lua and write it properly, you have a green light. I had minimal experience with programming when I was writing that code.

If something is written inefficiently in WML, it can easily become a problem, WML is very slow. Last time I did some simple benchmark, it was slower than lua by two orders of magnitude, throwing it into the super sluggish group of languages that are even slower than Python.

**Comment by white-haired-uncle** [comment]
A rewrite is probably left for someone with more programming/lua skills than I.  I did notice a comment in lua/redeem.lua which lead me to believe that work is/was being done to move redeem to lua.

Currently thinking that raising the max_redeem_count might be the fix for the issues of seeing (for example) redeem(4) and redeem(5) and for taking redeem upgrades before you should if you take the upgrade.  I haven't figured out how to get to that variable other than manually in debug mode.  This comment is basically just a reminder that I (better yet someone) might want to look into that.

**Comment by white-haired-uncle** [comment]
Looks like there were multiple issues, but the big one was that the "jump upgrade" option in United and Transporting was getting the redeem level by counting all upgrades, and assuming others would do the same, while the redeem advance in redeeming.cfg counted unique advancements.  

Simple answer, just go by the id of the attack special (e.g. redeem 5) instead of counting to get the redeem level.  At least, that seems to be working so far.

**Comment by Dugy** [comment]
I think the best solution would be to save the redeem level into `unit.variables.redeem_level`, because it's the simplest solution.

**Comment by white-haired-uncle** [comment]
I guess that would be updated in United (maybe), Transporting (maybe), when redeem advances, and when redeem first becomes available (pretty sure that's Apologies, but I don't see any other redeem stuff get initialized there).
