### ISSUE TITLE
Knockback on Solid Phoenix kills adjacent allied unit

### ISSUE THREAD

**Issue by Toranks** [Dugy/Legend_of_the_Invincibles#538]
I don't know why it happens only with Solid Phoenix. I've used debug to swap the Solid Phoenix for another unit, and the bug doesn't occur.

How to reproduce:
- Attack the Phoenix with the knockback attack of the Lunatic Knight
- The witch in the back dissapears and the phoenix takes its place

[Knockback kills ally.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/11927297/Knockback.kills.ally.gz)

EDIT: Found the cause.

NOTE: There is a lua error that says `[unstore_unit] variable second_unit does not exist`. This bug is localized and belongs to the scenario (the event that disables fire attacks). I'll try to send a PR to fix it soon, but it has nothing to do with this bug. EDIT: DONE

**Comment by Toranks** [comment]
FOUND THE CAUSE: I'ts because Solid Phoenix has all terrains non-passable, so find_vacant and check_passability works bad. Reported on #modding waiting for them to tell me if it is a bug or if the code needs to be modified.

**Comment by Toranks** [comment]
@Dugy @Discontinuum  
They have already explained to me how to fix it. There are two alternatives for the solution. What behavior do you want immobile units to have if knockback is used on them?:
- The unit is moved with check_passability=no to the closest free hex to the destination one.
- The unit does not move.

**Comment by Dugy** [comment]
I think it would be better if the unit didn't move and knowckback did nothing.

**Comment by Toranks** [comment]
That has the simplest solution
