### ISSUE TITLE
Lethargy and wrath intensity is not cleared between scenarios

### ISSUE THREAD

**Issue by Toranks** [Dugy/Legend_of_the_Invincibles#544]
I am asking if this is intentional in the first place. The solution is simple, incorporating the same turn_refresh code into victory or start (or both).
This issue doesn't just affect units that have lethargy at the end of one scenario, stay lethargic the next scenario, and must wait multiple turns to heal. It also affects units that are saved to a variable and come back years later. This is the case of Efraim and Lethalia when they become gods (the one you have not chosen as the main one).

**Comment by Dugy** [comment]
If I recall correctly, statuses are cleared on scenario end. Wrath and lethargy are, however, implemented as a variable inside the unit, which prevents this from happening. Maybe it would be worth reimplementing as a self-leadership using a status to determine its intensity?

**Comment by Toranks** [comment]
The problem is that wrath_intensity is used by many different abilities, and it's a bit complex to implement as you say.

**Comment by Dugy** [comment]
Yes, but most of those cases can be addressed with a single find&replace to change `variables.wrath_intensity` to `status.wrath_intensity`.

**Comment by Toranks** [comment]
Same thing happens with redeem recharge, by the way

**Comment by Toranks** [comment]
> Yes, but most of those cases can be addressed with a single find&replace to change `variables.wrath_intensity` to `status.wrath_intensity`.

Damage is reduced/increased by a special inside the weapon that is "manually" cleared by the code. Clearing the variable (or state) does not cancel these bonuses/maluses.

**Comment by Dugy** [comment]
Yeah, that makes sense. I put several things into variables that should have been statuses.

> Damage is reduced/increased by a special inside the weapon that is "manually" cleared by the code. Clearing the variable (or state) does not cancel these bonuses/maluses.

That's because the code is old. Now it's possible to create a leadership ability that adds damage depending on a property of the unit, if I remember correctly.

**Comment by Discontinuum** [comment]
I don't believe redeem should've been cleared between scenarios: then in Chapter 9 you can infinitely go here and there and redeem an imp to feed it without hindrance

**Comment by Dugy** [comment]
I am inclined to agree with that.

**Comment by Toranks** [comment]
Oh,  I did not know that. So you can undo the editing of redeeming.cfg on #545 ?

**Comment by Dugy** [comment]
I can't do it without a nasty force push into master or a revert commit. I think that removing the part that resets redeem and making another commit from that is more convenient for the state of master.
