### ISSUE TITLE
Beelzebub loses his level when he levels up

### ISSUE THREAD

**Issue by Toranks** [Dugy/Legend_of_the_Invincibles#549]
In Beelzebub's code, this operation is performed:

```
{VARIABLE beel_store_level_add {POWER}}
{VARIABLE_OP beel_store_level_add multiply 5}
{VARIABLE_OP beel_store.level add $beel_store_level_add}
[unstore_unit]
      variable=beel_store
      find_vacant=yes
[/unstore_unit]
```

Basically for the player to raise those experience points when fighting with him, and the corresponding when killing him.
The problem is that when he levels up, he go back to the base level of the Beelzebub unit type, which is 30.
Of course, it is something that happens rarely, but not so rare in the second part, where Lethalia and Efraim are each level 10.

The solution is easy in 1.17, using the new `[effect] apply_to=level`
Not so easy in 1.16, requires lua. But I have a working code for it, if you're interested.

**Comment by Dugy** [comment]
I suggest using the `apply_to=level` solution. It would not fix this problem for 1.16, but it's not very urgent.

I wonder if this prevents some efficient way to farm exp.
