### ISSUE TITLE
Spawn points in Doom Ford

### ISSUE THREAD

**Issue by white-haired-uncle** [Dugy/Legend_of_the_Invincibles#555]
In ch9s08 Doom Ford, I get lots of these:

 error engine: wrong side in [unit] tag - no such side: 6 ( number of teams :5)

which are probably caused by these:

`{INFERNO_SPAWN_POINT 6 ... `

When I changed them to INFERNO_SPAWN_POINT 5 ... the errors went away, and demons started spawning.  Which is nice and all, but I'm not sure what side they are supposed to be on (or why there are 5 sides to begin with)?

P.S.
I noticed recently that only one of the spawn points in Steelhive actually does anything.  I was hoping it was the same issue.  Nope.

**Comment by Dugy** [comment]
Most likely I forgot to define side 6 and the warning didn't exist at that time.

**Comment by white-haired-uncle** [comment]
Should I create a side 6 then, or use one of the other sides that don't appear to be used for anything (they must be there for a reason though?)?

**Comment by Dugy** [comment]
If there is a side that does not appear to be used for anything, then the side number most likely should have been the number of the unused side.

There are often many enemy sides because the AI could not handle sides with many units without frictions, I am not sure how it is now.

**Comment by Toranks** [comment]
Has this issue been fixed in in #558  yet?

**Comment by Dugy** [comment]
It's been fixed, if I recall correctly.
