### ISSUE TITLE
Redeem descriptions vs implementation

### ISSUE THREAD

**Issue by white-haired-uncle** [Dugy/Legend_of_the_Invincibles#561]
I had this idea about using lookup tables to get the redeem chance (e.g.chance[redeemlevel][targetlevel]) instead of calculating them.  I don't know that this provides any real benefit besides making some code no one is going to read easier to read.  It would make setting arbitrary rules a lot easier, but is that really going to happen?  Seems like something that would have been a nice idea to begin with, now of limited value.

This lead to a look at the description of redeem (N).  It seems to me there are a few issues related to redeeming units adjacent to the target.

- To match the code, the description for level 5 and 6 should be the same for units adjacent to the target, as should 7 and 8, etc.  Currently, the description for 5 is unique, 6 and 7 match, etc.
- At redeem (15) and higher, there are levels missing from the descriptions
- At redeem (18) and higher, redeeming units adjacent to the target with levels >= 11 are mentioned.  AFAICT, this is never possible.

I think there are a few options
- Do nothing.  I doubt players will even notice anything unless they spend a lot of time in the thing at the end of chapter 9.
- Fix the descriptions to match the code
- Alter the code to match the descriptions (with the exception of the missing levels, no idea what to do there)

**Comment by Dugy** [comment]
The redeem probabilities follow certain formulas, each for some range of levels. I don't remember them, but they should be relatively simple and implemented somewhere within the weapon special's code. It should be relatively easy to implement in lua and use to both generate the description and determine the probability.
