### ISSUE TITLE
Kamikaze spirit does not take damage-decreasing effects into account

### ISSUE THREAD

**Issue by matsjoyce** [Dugy/Legend_of_the_Invincibles#57]
Example: Attack using whirlwind, should receive no damage but damage is dealt. Savegame at https://forums.wesnoth.org/viewtopic.php?f=8&t=32384&p=620058#p620058

The problem is that damage is calculated by:
```
{VARIABLE opponent_damage $second_weapon.damage}
{VARIABLE_OP opponent_damage multiply $second_weapon.number}
```
Which does not take resistances or abilities into account. Fixing it might be alot of work though.

**Comment by Dugy** [comment]
Resistances should be taken into account, because harm_unit is used. But abilities aren't. I can't think of a good solution, all I can think of is extremely bug-prone.

**Comment by matsjoyce** [comment]
Yeah, I couldn't think of anything simple either. Maybe a hack using `wesnoth.simulate_combat`. Guess we'll wait for the Lua APIs to mature and see if anything shows up.

**Comment by Dugy** [comment]
Yes.
