### ISSUE TITLE
Lethalia God needs to take "able to heal allies" to improve healing

### ISSUE THREAD

**Issue by Toranks** [Dugy/Legend_of_the_Invincibles#575]
On Part II even though Lethalia already comes with basic heal built in (cures and heals+8), she has to grab this advancement in order to aim for heals+11 and beyond.
This only happens with Semi God Lethalia EDIT: AFTER GET THE HEALING REDEEM ADVANCEMENT, not with Preserved Lich Lethalia, i.e. after absorbing the phoenix.

I don't understand why this happens, since in...

https://github.com/Dugy/Legend_of_the_Invincibles/blob/f1706c77ddb8ab5253c96f6a33561dada7760d14/scenarios6/01_The_Awakening.cfg#L201

...she already has the advance id `heal` and `heal1` that allows her to directly aim for heals+11 `"able to heal allies better"` `id=heal2`. Examining with inspect, those two advances continue in Lethalia semi god, have not been erased.

**Comment by Toranks** [comment]
It's definitely Redeem that breaks the healing progression sequence on the advancements, resetting it from the beginning.

**Comment by white-haired-uncle** [comment]
Other than the option to jump redeem levels in United and Transporting Facility, I never got into the actual taking of upgrades. My part stopped where at the point where the upgrade gets triggered (utils/redeeming.cfg search for  "Advance redeem level" or [show_redeem_menu]).

It looks like the upgrade happens just after that in the switch block.  While it says replace, it looks to me like it's just appending the chosen upgrade to redeemer.modifications.advancement, along with replacing the current redeem specials with the new one(s).

Did you happen to take the upgrade for L in United and/or Transporting?

**Comment by Toranks** [comment]
Now I can't reproduce the bug, neither with your savegame nor with mine (if I start them from the beginning of the scenario instead of in the middle of the scenario). I now suspect that it is something that went wrong when I updated LOTI in the middle of the campaign, I close the issue then, and will fix the error manually by editing Lethalia in my savegame.
