### ISSUE TITLE
Chapter 2 Scenario 2 "Gods" can be defeated offscreen

### ISSUE THREAD

**Issue by Toranks** [Dugy/Legend_of_the_Invincibles#584]
The trolls have force to hit 0 mages, but any other side could kill Jacob and produce defeat before even reaching the mountains. Since it is not explained anywhere that saving him is necessary, the player does not know why he has been defeated, and the conversation of Jacob's death makes no narrative sense, about something that happens out of sight of the player.

There would be two solutions:

- Force_to_hit other sides against mages

- Have the AI avoid entering the mountain, at least until the player meets Jacob.

On the other hand, this code doesn't seem to work as intended. What is the original intention to this AI aspect? All enemy AI sides have it:

```
            {MODIFY_AI_ADD_ASPECT 4 attacks (
                [facet]
                    name=testing_ai_default::aspect_attacks
                    id=dont_attack_others
                    invalidate_on_gamestate_change=yes
                    [filter_enemy]
                        [not]
                            side=2
                        [/not]
                        [not]
                            side=3
                        [/not]
                        [not]
                            side=5
                        [/not]
                        [not]
                            side=6
                        [/not]
                        [not]
                            side=7
                        [/not]
                        [not]
                            side=8
                        [/not]
                    [/filter_enemy]
                [/facet]
            )}
```

**Comment by Dugy** [comment]
Yeah, that code was supposed to prevent side 4 from attacking other sides than side 1. This can be solved easier now, Jacob's side may be allied both with the player and all the enemy sides except for the trolls. There is also the `[avoid]` tag that can make the enemies ignore the area where Jacob is.
