### ISSUE TITLE
Efraim has two swordd of Krux

### ISSUE THREAD

**Issue by alain-bkr** [Dugy/Legend_of_the_Invincibles#59]
hi

I tested wesnoth 1.13.+ from git repo : 
commit f76420ba2a568448f45b451f07a7a1807affcb5f
Author: jostephd 
Date:   Sun Dec 17 04:28:20 2017 +0000

and Loti from git : 
commit 163c595f41392ed5b7bdf861371f23528480227b
Author: Matthew Joyce 
Date:   Sat Dec 16 10:33:13 2017 +0000

Efreim has two sword of krux, and i think the bonuses are doubled too.

[LotI1-Tutorial-Sauvegarde_automatique1.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/1569558/LotI1-Tutorial-Sauvegarde_automatique1.gz)
[LotI1-Tutorial-Sauvegarde_automatique2.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/1569559/LotI1-Tutorial-Sauvegarde_automatique2.gz)
[LotI1-Tutorial-Sauvegarde_automatique3.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/1569560/LotI1-Tutorial-Sauvegarde_automatique3.gz)
[LotI1-Tutorial-Sauvegarde_automatique4.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/1569561/LotI1-Tutorial-Sauvegarde_automatique4.gz)
[LotI1-An_Orcish_Assault.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/1569562/LotI1-An_Orcish_Assault.gz)
[LotI1-An_Orcish_Assault-Sauvegarde_automatique1.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/1569563/LotI1-An_Orcish_Assault-Sauvegarde_automatique1.gz)

btw, a ton of warning have disappeared with this recent update from main wesnoth git.
cheers
/Alain

**Comment by Dugy** [comment]
If he has two of them, then the bonuses of both apply. I will check it out, but I am unfortunately quite busy at the moment.

**Comment by matsjoyce** [comment]
@alain-bkr It's a wesnoth regression, reported https://github.com/wesnoth/wesnoth/issues/2310. It allows an action to occur twice that shouldn't.

**Comment by Dugy** [comment]
Great job finding this regression, matsjoyce!

**Comment by matsjoyce** [comment]
The bug in wesnoth has been fixed in https://github.com/wesnoth/wesnoth/commit/393ac9bd7026d138de803fee1b2e123f51c71b06, so just pull and recompile wesnoth and it should work fine.
