### ISSUE TITLE
BZB dropping stuff in unwalkable areas

### ISSUE THREAD

**Issue by white-haired-uncle** [Dugy/Legend_of_the_Invincibles#596]
I think some work was done in the past to avoid this (or maybe they get picked up automatically?  I can't test here since BZB was the last enemy leader).

If you kill him in a corner, a lot of his loot ends up off the map.

https://forums.wesnoth.org/viewtopic.php?p=682792#p682792

Also, I've noticed recently in some scenarios you have to finish the battle with him, while others (and all in the past IIRC) you can win if he lives but all other enemy (leaders?) are killed.  Not sure if this was intentional, but I think it's different now.

**Comment by Dugy** [comment]
His drops fill up an area of radius 2 with items. If they appear in walls, they are autopicked. I didn't consider the option that he might drop those items at the edge of a map. Maybe the autopick could also pick items outside of map boundaries?

**Comment by Discontinuum** [comment]
Related issues #375 and #420

**Comment by white-haired-uncle** [comment]
Is there a way to get the size of the map?

I'm thinking when calculating the x,y for the drop, check if <1 or >map and if so drop the item on "the other side" (e.g. he's at the top of the map, anything that would be dropped at y=0 gets dropped at y=3, y-=1 at y=4, etc).  If that's even possible.

**Comment by Dugy** [comment]
Yes, you can get the size of map. `[store_map_dimensions]` https://wiki.wesnoth.org/InternalActionsWML#.5Bstore_map_dimensions.5D

Your idea is sound.
