### ISSUE TITLE
Weird behavior of "fouls potion"

### ISSUE THREAD

**Issue by alain-bkr** [Dugy/Legend_of_the_Invincibles#60]
Hi

One character "_Connor" has drunk a "Foul's potion" and got more or less 20 additional HP
He level up, and they i started the chapter 2  the potion was still effective weirdly

* the Elvish healer was not taken into account, and connor loses 10 max HP, but it is ok in villages.
* pbwith bonus / malus

Most important for me is,: how to get rid of this potion , or how long will it last ?  :-)

I trid dinking a healing potion, but it did nothing
I have no other Foull's potion to drink, but i would have tried it ! 

Below some saved games most recent first.

[LotI1-The_Beginning_Tour_9-connor-lost-hp-while-near-a-healer.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/1594453/LotI1-The_Beginning_Tour_9-connor-lost-hp-while-near-a-healer.gz)

[LotI1-The_Beginning_Tour_8-foul-poton_does__not_give_bonus_only_malus.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/1594454/LotI1-The_Beginning_Tour_8-foul-poton_does__not_give_bonus_only_malus.gz)

[LotI1-The_Beginning_Tour_1-connor-still-foul-from-potion-after-level-up-and-new-chapter.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/1594455/LotI1-The_Beginning_Tour_1-connor-still-foul-from-potion-after-level-up-and-new-chapter.gz)

[LotI1-The_Battle_for_Ogira_Tour_15-Connor-106hp.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/1594456/LotI1-The_Battle_for_Ogira_Tour_15-Connor-106hp.gz)

[LotI1-The_Battle_for_Ogira_Tour_14-connor-92hp.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/1594457/LotI1-The_Battle_for_Ogira_Tour_14-connor-92hp.gz)

/Alain

**Comment by Dugy** [comment]
There is a long-term issue that healers that heal different amounts of HP than 8 do not always count as healers. Something weird happened during that level-up, all potions should be removed on level-up and there's no reason why should Foul Potion be an exception. This might mean that this can affect all potions. Investigation will be done.

**Comment by alain-bkr** [comment]
btw, what is the behavior of a foul's potion ?
are the change in maxHP permanent, or does it come back to the nromal-original level ?

**Comment by Dugy** [comment]
The supposed behaviour is:

* Gain 3 to max HP and heal 8 additonal HP per kill
* Lose 1 max HP per turn, this count increases but is reset with each kill
* Everything is reverted on level-up

I am sure it worked at some time, but you're suggesting that it somehow changed recently, maybe due to some incompatibilities introduced in late 1.13.

**Comment by alain-bkr** [comment]
With wesnoth and Loti from git 02 feb, I tried the proposed fix in #75 and edited a saved game (s/healing_other/healing/g )
* i noticed nothing wrong
* the fool 's potion is correctly neutralised by an elvish healer or lethalia


btw, i noticed that the +3 max_hp bonus is not granted with the killing of undeads.

**Comment by Dugy** [comment]
I have released the fix. It is intentional that it does not work on undead, but if you insist, I might change it.

*The continuation of effect on levelup is not fixed yet.*

**Comment by Dugy** [comment]
I tested the current version on 1.14 and the effect is correctly gone on levelup. I think it can be closed now.
