### ISSUE TITLE
"Advancement taken" is not displayed

### ISSUE THREAD

**Issue by alain-bkr** [Dugy/Legend_of_the_Invincibles#61]
Hi

I noticed with Lethalia that its advancement was not shown , but it is effective (ice legacy, +3% on various resistances)

![2017-12-29_13-25-04-advancement-not-shown_icelegacy 3](https://user-images.githubusercontent.com/31039036/34455101-004a3a04-ed78-11e7-95e7-0ed35f8b9a4e.png)

/Alain

**Comment by alain-bkr** [comment]
also i noticed that during level-up , the specail advancements (like ice legacy) are not (correctly) displayed.
choosing one advancment or the other does not change the left side of the panel

![advancement_not_displayed_1_2018-01-05_21-50-38](https://user-images.githubusercontent.com/31039036/34638892-906d8aa2-f2d5-11e7-82e9-545a9819fac7.png)

![advancement_not_displayed_2_2018-01-05_21-50-38](https://user-images.githubusercontent.com/31039036/34638893-908c59b4-f2d5-11e7-9419-a39c15af3ca4.png)

**Comment by Dugy** [comment]
I am aware of this issue, but fixing it would be too difficult (like reimplementing that advancement window).

**Comment by IamTechknow** [comment]
Can confirm that the first issue is still present in 1.14, that is "none" is always shown for the list of potions, non-removable items, and advancements are in effect. It would be nice to see what are the advancements I chose for each character, would a fix for this be worth a pull request?

**Comment by IamTechknow** [comment]
@matsjoyce Here you go, start of Axadria scenario, I already got the leadership soul eater advancement, and if you go to the alter last advancement you can see the advancement is better with sword

https://gist.github.com/IamTechknow/a3c691b161053aff67393940c35475dd/raw/9eef0061b21dcfb59e8bea455442f015a4c9cdef/LotI2-Axadria

**Comment by matsjoyce** [comment]
@IamTechknow Thanks, should be fixed now. @Dugi Are we still supporting 1.12, or can we start nuking the ifver code?

**Comment by Dugy** [comment]
No need to support v1.12 anymore.

**Comment by matsjoyce** [comment]
Cool, we can start removing a lot of old code then.

**Comment by Dugy** [comment]
Yeah, but please don't do it manually, I can write a script for that when I'll be less busy (in a month or so).

**Comment by matsjoyce** [comment]
Heh, don't worry about that. I know enough Python to know that this is not a manual job.

**Comment by IamTechknow** [comment]
Confirmed it is fixed, thanks!
