### ISSUE TITLE
At the begining of "Toxic Sun" , an error message appear

### ISSUE THREAD

**Issue by alain-bkr** [Dugy/Legend_of_the_Invincibles#62]
Hi again

I noticed this message at the beginning of the level, but it did not see anything else, so i guess it is not very important.

<Invalid WML found> [unstore_unit]: variable 'advanced' does not contain unit data.

Below the screenshot and save games
![2017-12-26_17-47-35-error](https://user-images.githubusercontent.com/31039036/34455217-56c9e36e-ed7a-11e7-812e-89bc051422a0.png)

[LotI1-Toxic_Sun-Sauvegarde_automatique1.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/1594484/LotI1-Toxic_Sun-Sauvegarde_automatique1.gz)
[LotI1-Toxic_Sun.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/1594485/LotI1-Toxic_Sun.gz)
[LotI1-Ascension-Sauvegarde_automatique6.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/1594486/LotI1-Ascension-Sauvegarde_automatique6.gz)

**Comment by alain-bkr** [comment]
Lethalia did not advanced, and ws en elvish sheer instead of a lich

This is now fixed by 691e9fef29e28a20fc1655a123ca6ad9b1280c8f   (i checked with y saved game)

btw , is there a way to fix my games, and transform lethalia to a lich ?

**Comment by Dugy** [comment]
I think that the debug mode command `unit type=Lethalia_lich` could fix more than it breaks.

**Comment by matsjoyce** [comment]
Not an easy way. I could _technically_ modify a save game, but it would probably break other things. It's safer just to go back, unless you already got too far ahead.

**Comment by alain-bkr** [comment]
ok, i ll do nothing, and keep going on like this, unless it becomes blocking.
