### ISSUE TITLE
TBC textdomains

### ISSUE THREAD

**Issue by white-haired-uncle** [Dugy/Legend_of_the_Invincibles#621]
```
spartan$ grep -r wesnth-tbc The_Beautiful_Child/
The_Beautiful_Child/utils/rpg_events.cfg:#textdomain wesnth-tbc
The_Beautiful_Child/utils/utils.cfg:#textdomain wesnth-tbc
The_Beautiful_Child/utils/global_events.cfg:#textdomain wesnth-tbc
The_Beautiful_Child/utils/strategy_events.cfg:#textdomain wesnth-tbc

spartan$ grep -r wesnoth-tbc The_Beautiful_Child/
The_Beautiful_Child/scenarios/07_Siege_of_Ziggurat.cfg:#textdomain wesnoth-tbc
The_Beautiful_Child/scenarios/03_To_Tame_a_Land.cfg:#textdomain wesnoth-tbc
The_Beautiful_Child/scenarios/08_Bringing_the_Light.cfg:#textdomain wesnoth-tbc
...
The_Beautiful_Child/units/Exalted_Blackguard.cfg:#textdomain wesnoth-tbc
The_Beautiful_Child/_main.cfg:#textdomain wesnoth-tbc
The_Beautiful_Child/_main.cfg:    name="wesnoth-tbc"
```

I don't know anything about textdomains, but those first four are typos, correct?  I assume if they were correct there would be something to "define" them like wesnoth-tbc has?

EDIT:  Actually, now that I look at the diffs, it looks like wmlindent did that.  I suppose I should set them back?  And is that a bug in wmlindent that needs to be reported?  thx

**Comment by Dugy** [comment]
I think it's a typo, there is no reason for anything to be named `wesnth`.

**Comment by Toranks** [comment]
I already fixed that on another PR, pls update your code regulary

**Comment by white-haired-uncle** [comment]
Hmm, I updated yesterday or maybe the day before.

Maybe I had a shell in the old directory.
