### ISSUE TITLE
Incendiary image mod becomes permanent on level up

### ISSUE THREAD

**Issue by arobinson** [Dugy/Legend_of_the_Invincibles#631]
If a unit levels up during the same attack as being incinerated, the red image mod stays on the unit despite the incineration status being removed.

Unit `Vamal` in the attached file
[LotI2-The Den of Evil Turn 28.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/12211341/LotI2-The.Den.of.Evil.Turn.28.gz)

**Comment by white-haired-uncle** [comment]
I've seen something very close recently.  In Shatter the Defilers, on the last or next to last turn, Delly got incinerated.  I moved her to a village (which never got a chance to heal her before the end of the scenario).  In the next scenario, she's no longer burning, but still has the incinerated image.

**Comment by Dugy** [comment]
This happens because the status is cleared on scenario end, but `[effect]`s are not. There is an event to clear this when removing the status through a village or healer, but it's not triggered when scenario ends, leaving units with the colour change but without the status.

**Comment by white-haired-uncle** [comment]
Seems the easy workaround would be to add to the turn refresh a check if there's an object with incineration=yes while the status doesn't include incinerated.  I suppose this would leave them red on the recall list, and it's ugly IMO.

It seems like removing the object is simply missing from advancement, but I can't find where that would happen (save a chunk inside ifdef DISABLE_AMLA_WORKAROUND).  And I'm not sure how the status is cleared at scenario end, I assume it's a wesnoth thing, though if we know it will always happen I suppose the object could just be blindly removed on secenario_end?

**Comment by white-haired-uncle** [comment]
Also, it seems that regenerate may not cure incinerate.  At least it didn't for mushrooms recently.
