### ISSUE TITLE
Why does enemy_sides work the way it seems?

### ISSUE THREAD

**Issue by white-haired-uncle** [Dugy/Legend_of_the_Invincibles#634]
In some scenarios, certain explosive attacks don't work correctly.  For example, in Lost in Space, Cuncator's Sword's explosive slow only slows the target, not adjacent enemies, when used against the prince's team.  I think Army is Born (again, prince's team) is another example.

I checked the attack in LiS, and it appears enemy_sides is set only to 3, so the prince's forces (side 4) are not affected by the explosive part of explosive slow.  So I went looking for where this gets set.

In some scenarios, it looks like enemy_sides is set explicitly (then never cleared).  In other cases, it's set when DROPS includes DROP_EXT which has a prestart event.

If I'm reading this right, it appears that, for example, explosive slow only affects secondary units that are part of a side that has been configured to drop items when they die?

Is that intentional, or just an odd side effect?  It makes sense to me that you might not want certain sides to drop items, but to couple dropping with explosive slow (for example) just doesn't.

Or maybe setting enemy_sides explicitly is used to override this rather interesting behaviour, and it's (potentially) missing from some scenarios?

**Comment by Dugy** [comment]
The `enemy_sides` was a trick I used to determine which unit is the enemy of player. There's a different way of doing that (`[filter_side]` with `[enemy_of]`), but I either didn't know of it or it wasn't available at that time. Because it wasn't updated everywhere, some abilities and weapon specials still use `enemy_sides` and misbehave if the sides changed.

**Comment by white-haired-uncle** [comment]
So change the specials to use enemy_of then?

**Comment by Dugy** [comment]
Yeah, that should reliably fix it.
