### ISSUE TITLE
reproducible crash

### ISSUE THREAD

**Issue by alain-bkr** [Dugy/Legend_of_the_Invincibles#64]
hi again

move the griffon-rider  _Haloral from 29,69 to 25,50  to attack the elvish shaman Ufa in 24,59

it crash with the following message

'alain@servolant:/home/Big/Games/git-wesnoth/wesnoth$ ./wesnoth 2>&1 | tee 20171230-soir-crash.log
Battle for Wesnoth v1.13.10+dev (d21a79b-Modified)
Started on Sat Dec 30 20:26:57 2017

Automatically found a possible data directory at /home/Big/Games/git-wesnoth/wesnoth

Data directory:               /home/Big/Games/git-wesnoth/wesnoth
User configuration directory: /home/alain/.config/wesnoth
User data directory:          /home/alain/.local/share/wesnoth/1.13
Cache directory:              /home/alain/.cache/wesnoth

Setting mode to 1920x1080
20171230 20:26:57 warning config: add-on 'Legend_of_the_Invincibles' has no _info.cfg; cannot read version info
Checking lua scripts... ok
20171230 20:26:57 error general: Unknown key: page up
20171230 20:26:57 error general: Unknown key: page down
20171230 20:27:07 error config: Multiple [unit_type]s with id=Orcish Nightblade encountered.
wesnoth: src/attack_prediction.cpp:1765: double {anonymous}::calculate_probability_of_debuff(double, bool, double, double, bool, double): Assertion `prob_touched >= 0.0 && prob_touched <= 1.0' failed.

alain@servolant:/home/Big/Games/git-wesnoth/wesnoth$ 

'

[LotI1-Gods_Tour_16-reproducible-crash.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/1594711/LotI1-Gods_Tour_16-reproducible-crash.gz)

**Comment by matsjoyce** [comment]
Report this as https://github.com/wesnoth/wesnoth, this is definatly their problem.

**Comment by Dugy** [comment]
Your version's source has been modified somehow, because it says there that the revision is _d21a79b-Modified._ Before reporting it, I suggest to try an unmodified version. It didn't crash for me, but my version is about a week old.

Also, your description of the procedure lacks the attack that has to be used and the coordinates are wrong.

**Comment by alain-bkr** [comment]
It does not crash if the griffon attacks another unit

And later it does not crash with the same units.
[LotI1-Gods_Tour_18-did-not-crash.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/1594722/LotI1-Gods_Tour_18-did-not-crash.gz)
[LotI1-Gods_Tour_18-try-crash-again.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/1594723/LotI1-Gods_Tour_18-try-crash-again.gz)

**Comment by Dugy** [comment]
Didn't crash for me. Must be something recent.

**Comment by alain-bkr** [comment]
reported on wesnot https://github.com/wesnoth/wesnoth/issues/2342
