### ISSUE TITLE
Old style chapter/part defines

### ISSUE THREAD

**Issue by white-haired-uncle** [Dugy/Legend_of_the_Invincibles#640]
I noticed recently that when I load a save from part 2, it says "Legend_of_the_Invincibles_VI".  I think this is a simple fix, in _main.cfg just change id=.  While we're looking at _main.cfg, is that "Legacy stuff" still needed, it looks like it's just ifdefs for things that will never be defined (maybe OLD saves?)?

But that got me looking.  It appears there are a number of references to what I assume to be the old style of dealing with chapters/parts.  I'm thinking maybe the first scenario of each chapter should undefine the setting from the previous chapter (done here because scenario01 will almost always be the first, while what is now the last scenario in a chapter may not always be) and set a new one for this chapter?  However, this would make changes (such as changing unit hitpoints).  It would be "correcting" them back to what they were supposed to be (at one time), but it's also changing the behaviour that has existed, presumedly well enough, for some time.

It looks to me like for the scenarios, these could just be replaced without the ifdef/ifndef, since we know what the outcome be every time.  For the units/hybrids_of_steel.cfg, it's not so simple, there are lots of units affected.

Personally, I'd get rid of all the ifdef/ifndefs and just assume that the way it's been working with those values never defined is now the intended behaviour.

And of course, just leave it is always an option.

```
scenarios2/02_Gods.cfg:#ifdef CAMPAIGN_LEGEND_OF_THE_INVINCIBLES_II
scenarios2/03_Forest_of_Witchery.cfg:#ifndef CAMPAIGN_LEGEND_OF_THE_INVINCIBLES_II
scenarios2/04_Darkness_Closing_In.cfg:#ifdef CAMPAIGN_LEGEND_OF_THE_INVINCIBLES_II
scenarios2/07_Infinite_Legion.cfg:#ifdef CAMPAIGN_LEGEND_OF_THE_INVINCIBLES_II
scenarios2/07_Infinite_Legion.cfg:#ifndef CAMPAIGN_LEGEND_OF_THE_INVINCIBLES_II
scenarios2/08_Sightseeing.cfg:#ifndef CAMPAIGN_LEGEND_OF_THE_INVINCIBLES_II
scenarios2/10_Lilith.cfg:#ifdef CAMPAIGN_LEGEND_OF_THE_INVINCIBLES_II
scenarios4/07_Nemesis.cfg:#ifdef CAMPAIGN_LEGEND_OF_THE_INVINCIBLES_IV
scenarios4/07_Nemesis.cfg:#ifndef CAMPAIGN_LEGEND_OF_THE_INVINCIBLES_IV
scenarios8/03_United.cfg:#ifdef CAMPAIGN_LEGEND_OF_THE_INVINCIBLES_VIII
units/hybrids_of_steel.cfg:#ifdef CAMPAIGN_LEGEND_OF_THE_INVINCIBLES_IV
units/hybrids_of_steel.cfg:#ifdef CAMPAIGN_LEGEND_OF_THE_INVINCIBLES_V
```

**Comment by Dugy** [comment]
Yes, those are leftovers from a time when the campaign could be started at any chapter (with wild balance problems). They can be removed without consequences.
