### ISSUE TITLE
unit  did level-up , but is still poisonned

### ISSUE THREAD

**Issue by alain-bkr** [Dugy/Legend_of_the_Invincibles#65]
Hi

The unit is "_Haloral" the griffon rider.

Maybe  the same kind of trouble as #60 ?  (i would expect anything good or bad to stop at level-up and new scenario/chapter)

[LotI1-Infinite_Legion-Sauvegarde_automatique10.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/1608642/LotI1-Infinite_Legion-Sauvegarde_automatique10.gz)

[LotI1-Infinite_Legion_Tour_10_Haloral_level_up_but_still_poisoned.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/1608641/LotI1-Infinite_Legion_Tour_10_Haloral_level_up_but_still_poisoned.gz)

**Comment by Dugy** [comment]
Yes, it looks very much related. Stuff that should happen on levelup doesn't happen. It seems some event isn't happening when it should.
