### ISSUE TITLE
Firecast does not work with violent mage set

### ISSUE THREAD

**Issue by arobinson** [Dugy/Legend_of_the_Invincibles#651]
Find the celestial messenger at the top of the map. If you attack with him, you will see there is no secondary damage from a firecast ability, despite him having all 3 violent mage set items.

[LotI2-Catacombs of Prolonged Agony-Auto-Save16.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/13260633/LotI2-Catacombs.of.Prolonged.Agony-Auto-Save16.gz)

Unit does show that he has firecast in the unit description however

<img width="815" alt="image" src="https://github.com/Dugy/Legend_of_the_Invincibles/assets/93213/1901e98b-77cb-4843-b7de-d509ba1b29d1">

FYI, it does seem to work fine with the Pyromancer set

**Comment by Dugy** [comment]
My guess is that he has no fire spell that could be triggered, but it's just a quick guess.

**Comment by Dugy** [comment]
Yes, I looked at it, no fire spells to cast, so nothing is cast. Changing the lightbeam's damage to fire would not help, it must be an attack that is normally fire, like fireball.

**Comment by arobinson** [comment]
Ah, thx, I thought it would trigger a random fire spell in the game, not one the character had.

**Comment by Dugy** [comment]
Aha, yeah, that one can be misinterpreted.
