### ISSUE TITLE
Bug or intention? Leech attack removes slow

### ISSUE THREAD

**Issue by agguser** [Dugy/Legend_of_the_Invincibles#653]
It seems that when a unit is slowed, if it successfully hits a mob using a leech attack, it is no longer slowed. For example, when Efraim uses entropy (ranged, leech) to attack Beelzebub, which retaliates with ranged cold slow, now Efraim is slowed, and if Efraim's next entropy attack hits Beelzebub, he will be no longer slowed.

**Comment by Dugy** [comment]
Definitely not intention.

**Comment by Dugy** [comment]
It was caused by an oversight in a refactoring in #590, I fixed it and also removed this behaviour from some other abilities  where it wasn't intentional.
