### ISSUE TITLE
Ranged-only weapon specials aren't applied to ranged axe attacks.

### ISSUE THREAD

**Issue by Chergnobarp** [Dugy/Legend_of_the_Invincibles#661]
AFAICT, the root cause of this is `melee_type_list` and `ranged_type_list` in lua/items.lua. I might take a crack at this, but before I do, I'd like to know:

1. Just how big of a change is this?
2. Why was it done like this in the first place, instead of checking each attack's range?

Here's a save where you can see it. Lilith should have it via Heart of Ice, but doesn't. There's a second heart of ice on the champion bowman that you can transfer to a dwarvish hero for additional confirmation.
[LotI2-Halls of Miscreation-Auto-Save1.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/14076845/LotI2-Halls.of.Miscreation-Auto-Save1.gz)

**Comment by Dugy** [comment]
That's intentional. The logic behind this is that an axe is a melee weapon, which is used at range. This way, you can use some melee-only effects in ranged attacks.
