### ISSUE TITLE
immune to drains/poison/etc may need cleanup

### ISSUE THREAD

**Issue by white-haired-uncle** [Dugy/Legend_of_the_Invincibles#663]
User reports when a drains attack occurs against defender wearing Amulet of SomethingOrOther, defender is left with immune to poison (with loti3.2.7c):
https://forums.wesnoth.org/viewtopic.php?p=686113#p686113

Looks to me like in utils/abilities_events.cfg the attack event immunizes the defender and the attack_end removes that from the attacker (I realize that there are two pairs of events, one for attacker has immune and one for defender has immune, but the latter looks inconsistent and this matches the behaviour).

But while looking at this, I noticed a couple things:

1.  Does this approach of setting not_living for the duration of the attack make sense?  What if an attacker used poison and drain (for example) on the same attack, and the defender only had immune to drain?  
2. In 3.2.7c, is there a reason for using modify_unit to set immunity and unstore_unit to remove?  Don't suppose it really matters, but consistency and all.
3. In 3.2.7c, the "wrong unit issue" applies to both poison and drains
4. In 3.2.7c, there are three pairs of immune to poison attack events (I'd expect two).  It looks like maybe the extra one was an attempt to fix the "wrong unit issue" but was implemented as an addition instead of replacement?
5. In beta, I don't see any reference to immune to drain.  EDIT:  Okay, now uses undrainable.  Maybe much of the above has been addressed, but there's just some cleanup left to do?

**Comment by Dugy** [comment]
Immune to poison is still written by setting the not_living status. That was the only way of doing this in the old days. There are indeed better ways of doing this now, I think it can just set the unit's status to unpoisonable and keep it that way.

**Comment by Discontinuum** [comment]
not sure if appropriate to ask here, but I guess 1.16 final release is needed, both for LotI and spin-offs. 1.18 is near, I guess push the latest fixes to 1.16 before porting would be nice

**Comment by Dugy** [comment]
I have updated LotI on the add-on server.

**Comment by white-haired-uncle** [comment]
So I tried to give an AI unit ABILITY_IMMUNE_TO_SLOW.  It didn't do anything.  It looks like unslowable is only set by a couple items, and ABILITY_IMMUNE_TO_SLOW just gives a description but otherwise does nothing.  I think the item should grant the ability which should set the status.

And I feel like there should be a TRAIT_IMMUNE_TO_SLOW which sets ABILITY_IMMUNE_TO_SLOW.  It just seems like a trait to me.  Like venomous creatures being immune to their own venom, I would think a unit had the ability to slow inherently and slow was a significant aspect of their attacks should probably be immune to slow.

I suspect this (only works from items) probably applies to poison/drain as well.

**Comment by Dugy** [comment]
It should have been implemented as an `[effect]` with a `apply_to=status` to make it unslowable, unpoisonable etc. However, the code for describing items ignores these currently.

**Comment by Dugy** [comment]
Okay, I have removed those abilities, they were doing nothing beside adding the part into the description. The status settings that were providing the actual effect are now shown in the description. Now there shouldn't be anything misleading in the code.

**Comment by white-haired-uncle** [comment]
Bummer.  I pretty much always give E slow (mostly to slow the units attacking him).  Making a boss immune to slow seems like a good way to keep E from killing them so quickly.  Not that it can't be done anyway, the ability just would have been a really easy way to do it (they probably have abilities anway, so it's just one cut and paste vs remembering how to set a status (which probably should come from a trait)/etc.).

**Comment by Dugy** [comment]
Just copypaste this to every boss that should be unslowable:

```
[trait]
  id=immune to slow
  name=_"immune to slow"
  female_name=_"female^immune to slow"
  [effect]
    apply_to=status
    add=unslowable
  [/effect]
[/trait]
```

**Comment by white-haired-uncle** [comment]
Perfect use case for a macro.  I don't want to put it in if you just took it out, but it makes too much sense not to.  Unless the idea was it doesn't make sense as an ability, but could as a weapon special and a trait?

**Comment by Dugy** [comment]
Yeah, there could be a macro for this.

The game developers have decided to that unpoisonable and the others are a status, so it's not an ability. Trying to implement things in different ways makes maintenance hard.

On a second thought, maybe turning it into a trait is not a good idea. Statuses are shown in a specific location in the UI. Poison and slow have their own icons. The various immunities don't, as far as I remember. It's possible to add them, incinerate already has one. Maybe we could add these?

**Comment by white-haired-uncle** [comment]
Traits have their own place, right under the race name.  I like that better, as the status icons have a tiny space and are quickly replaced by ... (you can still hover to find them, but it's not as easy to see).  Also, statuses are generally very short lived, while a trait is at least semi-permanent.

Either way, the important thing is that you can see them.  And easy to add to a unit helps.

**Comment by Dugy** [comment]
I have made these statuses show in the area of the UI where statuses normally show.

**Comment by white-haired-uncle** [comment]
Probably should be an unincinerable (non-combustable? whatever).  I just incinerated a Fire Wraith, which doesn't make much sense.  It would mean messing, in some way, with mainline units, but it's worth considering.

**Comment by Dugy** [comment]
How much damage does Fire Wraith even take from incinerate? 1 damage per turn?

**Comment by white-haired-uncle** [comment]
8.  Which is odd, since they're already on fire from the looks of the unit.

**Comment by Dugy** [comment]
He only has 50% fire resistance, so a lack of immunity to incinerate doesn't seem so unexpected.

**Comment by white-haired-uncle** [comment]
These should probably be reviewed as well.  While 'not_living' may be correct for some, in at least one case not_living should be replaced with undrainable.

```
spartan$ grep -r not_living | sort -u
lua/items.lua:			elseif effect.apply_to == "status" and effect.add == "not_living" then
lua/titles.lua:		if not_living > 1 or has_attack["chill wave"] or has_attack["shadow wave"] or has_attack["curse"] or has_special("plague") then
lua/titles.lua:		local not_living = 0
lua/titles.lua:						not_living = not_living + 1
scenarios6/15_Apologies.cfg:                {CLEAR_VARIABLE advanced2.status.not_living}
scenarios8/04_Kidnapped.cfg:                        add=not_living
units/demons_race.cfg:            add=not_living
utils/abilities_events.cfg:                        name=carcinogenous[$i].status.not_living
utils/abilities_events.cfg:                                name=this_item.status.not_living
utils/abilities_events.cfg.save:                        name=carcinogenous[$i].status.not_living
utils/abilities_events.cfg.save:                                name=this_item.status.not_living
utils/abilities_events.cfg.save:                status=not_living
utils/abilities_events.cfg:                status=not_living
utils/abilities_events.cfg.tmp:                        name=carcinogenous[$i].status.not_living
utils/abilities_events.cfg.tmp:                                name=this_item.status.not_living
utils/abilities_events.cfg.tmp:                status=not_living
utils/amla.cfg:            add=not_living
utils/chapter9_utils.cfg:                    add=not_living
utils/item_list.cfg:            add=not_living
utils/utils.cfg:                                add=not_living
```

**Comment by Dugy** [comment]
Yes, also sometimes with `unpoisonable`, sometimes with all three.

**Comment by white-haired-uncle** [comment]
utils/chapter9_utils.cfg:  MAKE_ANIMATED_STATUE - I'm guessing not_living -> petrified?

utils/item_list.cfg: Soul Eclipse currently sets status to not_living, but makes no mention of the fact.  Should probably be changed to undrainable, unplagueable, unpoisonable, and figure out how to make it show these effects in the description.

utils/amla.cfg: Undead legacy not_living > undrainable, unplagueable, unpoisonable

utils/utils.cfg: makes BZB not_living - why is this in here and not part of the unit type?

**Comment by Dugy** [comment]
> utils/chapter9_utils.cfg: MAKE_ANIMATED_STATUE - I'm guessing not_living -> petrified?

Yes.

> utils/item_list.cfg: Soul Eclipse currently sets status to not_living, but makes no mention of the fact. Should probably be changed to undrainable, unplagueable, unpoisonable, and figure out how to make it show these effects in the description.

Yes.

> utils/amla.cfg: Undead legacy not_living > undrainable, unplagueable, unpoisonable

Yes.

> utils/utils.cfg: makes BZB not_living - why is this in here and not part of the unit type?

Because it can't be part of the unit type as far as I know. It can be part of the race, or individual unit. I may be wrong here but that's the reason why I did it so.

**Comment by white-haired-uncle** [comment]
scenarios6/15_Apologies.cfg, items.lua, and titles.lua don't depend on not_living being a valid status, they just act if it does exist and can be ignored.

abilities_events:  One of them is used in a filter for foul potion.  I don't know what to do with this because foul potion doesn't list any exceptions.

abilities_events:  Feeding says "a living unit", I guess that would be not (race=undead or race=mechanical)?

**Comment by Dugy** [comment]
> scenarios6/15_Apologies.cfg, items.lua, and titles.lua don't depend on not_living being a valid status, they just act if it does exist and can be ignored.

I don't understand this statement.

> abilities_events: One of them is used in a filter for foul potion. I don't know what to do with this because foul potion doesn't list any exceptions.

Either undrainable, or requiring a combination of undrainable, unplaguable and inpoisonable.

> abilities_events: Feeding says "a living unit", I guess that would be not (race=undead or race=mechanical)?

Or just assume assume a living unit is undrainable.

**Comment by Dugy** [comment]
It sounds like if there was some code that adds `not_living` to occurrences of `unplagueable` to make some older code work. But I have no idea where this code could be.
