### ISSUE TITLE
Lich : some bonuses from ... ?

### ISSUE THREAD

**Issue by alain-bkr** [Dugy/Legend_of_the_Invincibles#67]
A former assasin _Gwaraeran , with dagger, scyte and knife became a lich.
All the bonus of these weapons are counted, so the lich is really powerfull , but not that powerful !

It seems to have  more or less +100% to all damages , but this is wrong 

I noticed this while i added on staff , but the same thing happens when i crafted some object (like wanderlust, nothing to do with fight or magic) : 
Roughly, the offensive damages seems to be halfed when i add an object, but i checkeck and in fact all the bonuses go back to their *expected value*

[LotI1-Sightseeing_Tour_1-lich-weaker-with-staff.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/1608766/LotI1-Sightseeing_Tour_1-lich-weaker-with-staff.gz)

I went back to the moment when it became a lich : 

The lich goes from 7-3 during day (-25%)
to 20-3 one round later (at sunset +/- 0%)

[LotI1-Infinite_Legion_Tour_20_before_lich_Gwaraeran.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/1608763/LotI1-Infinite_Legion_Tour_20_before_lich_Gwaraeran.gz)

[LotI1-Infinite_Legion_Tour_21_so_strong_lich.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/1608762/LotI1-Infinite_Legion_Tour_21_so_strong_lich.gz)

**Comment by Dugy** [comment]
I think that this is the problem: damage bonuses on daggers affect only daggers, damage bonuses on scythes affect only scythes etc. So these bonuses have no effect when the unit can no longer use the weapon. This trick is useful only for properties that are not related to that weapon's damage, like abilities or resistances.

**Comment by alain-bkr** [comment]
I have trouble to explain :-)

1/  yes, the 'special' bonuses of the weapons are taken into account (like magic resistance +15% ...) 

2/ the problem is that just after becoming a lich, its attacks are  *too stong* , roughly twice as strong as they should be. This lasts until some object is added/removed, and bonus are recomputed , then everything is correct.

You can check this with the game "LotI1-Sightseeing_Tour_1-lich-weaker-with-staff.gz"
* damages are : 25-3 for the staff  this is not correct, it is roughly twice the value
Just remove the ring (and put it on again , no matter)
* damages are 12-3 with the staff  and this is correct

**Comment by Dugy** [comment]
It could be #60 again.

**Comment by Dugy** [comment]
This actually doesn't happen on 1.14, the lich had all properties correct and they didn't change when I unequipped an item. Everything goes correct.

It could have been caused by some bug in Wesnoth or it was a side effect of some bug that's already fixed.
