### ISSUE TITLE
some errors in log

### ISSUE THREAD

**Issue by alain-bkr** [Dugy/Legend_of_the_Invincibles#68]
I found this in the log, but i don't remember what hapenned at that moment (i can provide a save game just before). 

20180105 22:24:21 warning unit: Unknown attribute 'animate' discarded.
20180105 22:29:02 warning help: Found a section generator that I didn't recognize: units:
20180105 22:29:02 warning help: Found a topic generator that I didn't recognize: units:
20180105 22:32:41 warning unit: Unknown attribute 'animate' discarded.
20180105 22:32:41 error engine: Cannot do [set_variables] with invalid destination variable: advanced.modifications.advancement[] with mode = replace
name = advanced.modifications.advancement[$advanced2.modifications.advancement]
[value]
	always_display = yes
	id = execution
	image = attacks/bow-elven-magic.png
	max_times = 1
	require_amla = 
	strict_amla = yes
	[effect]
		apply_to = remove_attack
		name = execution
	[/effect]
	[effect]
		apply_to = bonus_attack
		damage = -40
		defense_weight = 0
		description = execution
		force_original_attack = longbow
		icon = attacks/bow-elven-magic.png
		merge = yes
		name = execution_bonus_attack
		range = ranged
	[/effect]
[/value]

and another on about images

20180105 23:49:51 error display: could not open image 'portraits/humans/transparent/iron-mauler.png'

**Comment by Dugy** [comment]
I have found the bug that caused it, but I have no idea if this bug was causing something else than the error message. It looks like something really old.

**Comment by alain-bkr** [comment]
(for my information : 
fixed by commit d402723

( _btw, i think if you add in the commit message "fixes #68'  , there will be some magic in github, maybe autoclose the issue, or add a link here ?_  )

**Comment by konecnyjakub** [comment]
That is right. And you can use even more keywords: https://help.github.com/articles/closing-issues-using-keywords/
