### ISSUE TITLE
"book  of courage" not effective immediatly , but at next level., or not

### ISSUE THREAD

**Issue by alain-bkr** [Dugy/Legend_of_the_Invincibles#69]
The lich read the "book of courage" at round 8 , but it still has -25% when in light at round 9

[LotI1-Lilith_Tour_9_lich_is_not_fearless.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/1610240/LotI1-Lilith_Tour_9_lich_is_not_fearless.gz)

At the begining of the next level , the lich is fearless , and has 0% malus in sunlight.
[LotI1-Thirst_for_Adventures-Sauvegarde_automatique1.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/1610241/LotI1-Thirst_for_Adventures-Sauvegarde_automatique1.gz)

**Comment by Dugy** [comment]
Looks again like #60. Some block of code isn't activated when it should. Probably 1.13 only.

**Comment by alain-bkr** [comment]
At the following *turn*, the pb came back
The lich is supposed to be fearless (in properties), book of courage is on the list of 'read books' , but -25% on sunlight

[LotI1-Thirst_for_Adventures_Tour_2-again-lich-is-not-fearless.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/1629531/LotI1-Thirst_for_Adventures_Tour_2-again-lich-is-not-fearless.gz)


![again_lich_is_not_fearless_2018-01-12_16-41-21](https://user-images.githubusercontent.com/31039036/34918375-096d0054-f952-11e7-8c97-feac1b6e9f20.png)

**Comment by Dugy** [comment]
The syntax of _fearless_ has changed. I have fixed it, but the fix will not apply on any units that already have the book.

**Comment by alain-bkr** [comment]
The patch does not work for me.
The lich is still frightened in sunlight

I erased all caches the cache, patched, and reload game then the lich read the book.

[LotI1-Lilith_Tour_8-pre-fearless-bug.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/1629746/LotI1-Lilith_Tour_8-pre-fearless-bug.gz)

[LotI1-Lilith_Tour_8-post-patch-and-book.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/1629748/LotI1-Lilith_Tour_8-post-patch-and-book.gz)


[LotI1-Thirst_for_Adventures_Tour_2-patched-but-lich-not-fearless.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/1629745/LotI1-Thirst_for_Adventures_Tour_2-patched-but-lich-not-fearless.gz)

**Comment by Dugy** [comment]
You also have to start the scenario (reloading first autosave is not enough) on the new version.
