### ISSUE TITLE
Suck does not work with Krux

### ISSUE THREAD

**Issue by arobinson** [Dugy/Legend_of_the_Invincibles#690]
Krux has a Suck(2) on each of his attacks, but he does not seem to ever gain health on any of his attacks

[SuckIssue.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/14540356/SuckIssue.gz)

The Imp next to him has no immunities, but none of Krux's attacks seem to be able to heal him when he hits

**Comment by Discontinuum** [comment]
> other than blade, impact or pierce

Or arcane, see #428

**Comment by arobinson** [comment]
Perhaps then the fix should just be to mention this in the description of suck? At least that way it is obvious why it doesn't work

**Comment by Dugy** [comment]
Okay, done.
