### ISSUE TITLE
Killing Lilith with incinerate

### ISSUE THREAD

**Issue by white-haired-uncle** [Dugy/Legend_of_the_Invincibles#693]
Lilith died from incinerate and an error popped up.

```
20240311 07:18:15 error scripting/lua: ~add-ons/Legend_of_the_Invincibles/lua/main.lua:64: attempt to mul a 'string' with a 'number'
stack traceback:
        [C]: in metamethod 'mul'
        ~add-ons/Legend_of_the_Invincibles/lua/main.lua:64: in local 'cmd'
        lua/wml-utils.lua:145: in field 'handle_event_commands'
        lua/wml-flow.lua:135: in local 'cmd'
        lua/wml-utils.lua:145: in field 'handle_event_commands'
        lua/wml-flow.lua:5: in function <lua/wml-flow.lua:4>
        [C]: in ?

```

Said string would be because cf.death_of_level is blank.  Consider:

```
        [store_unit]
            [filter]
                status=incinerated
                [and]
                    [filter_side]
                        side=$side_number
                    [/filter_side]
                [/and]
            [/filter]
            variable=burn_store
            kill=no
        [/store_unit]
        [for]
            array=burn_store
            [do]
                [harm_unit]
                    [filter]
                        id=$burn_store[$i].id
                    [/filter]
                    amount=16
                    damage_type=fire
                    fire_event=yes
                    kill=no
                    animate=no
                [/harm_unit]
            [/do]
        [/for]
        {CLEAR_VARIABLE burn_store}
        [store_unit]
            [filter]
                status=incinerated
                [and]
                    [filter_side]
                        side=$side_number
                    [/filter_side]
                [/and]
                [and]
                    [filter_wml]
                        hitpoints=1
                    [/filter_wml]
                [/and]
            [/filter]
            variable=burn_store
            kill=no
        [/store_unit]
        [for]
            array=burn_store
            [do]
                {DEBUG_MSG "<$burn_store[$i].id> is level <$burn_store[$i].level>"}
                [kill]
                    id=$burn_store[$i].id
                    [secondary_unit]
                        id=$burn_store[$i].variables.incinerator
                    [/secondary_unit]
                    animate=yes
                    fire_event=yes
                [/kill]
                {DEBUG_MSG "<$burn_store[$i].id> was level <$burn_store[$i].level>"}
                [award_extra_experience]
                    id=$burn_store[$i].variables.incinerator
                    death_of_level=$burn_store[$i].level
                    defer=no
                [/award_extra_experience]
            [/do]
        [/for]
        {CLEAR_VARIABLE burn_store}
```

First a side note:  I don't understand "[filter_wml]hitpoints=1".   Let's come back to that.

Note the DEBUG_MSG lines.  As I suspected, $burn_store[$i].level is empty after she is killed.  But this only happens for her, not other units.  I suppose that somewhere down the line of fire_event there's a special case for her where she is re-spawned and that's what's different about her, but I don't get how that affects a stored unit (unless MAYBE burn_store gets used along the line, everything global and all -- not likely).

Easy enough to work around, just save the incinerator and level before you kill (or maybe award extra XP before the kill?).  But why this is necessary, for her, is bugging me.

Now the hitpoints=1 thing.  I don't get it.  If it was <1, I'd be almost cool with it.  Thing is, while testing, if I give her 1 HP at turn end she'll die on the next turn (hers).  If I give her 14, sometimes she dies, sometimes she doesn't.  Not only is 14 inconsistent, in neither case is N-16==1.  I'm lost on this one.

**Comment by Dugy** [comment]
I don't know why her level is a blank field, maybe it's what you think it is. Your suggestion about how to handle should work.

The filter you are asking about checks if the unit has 1 hitpoint. The reason for that is that the target of incinerate is supposed to lose hitpoints, but not die from it (which would keep it at 1 hitpoint), similarly to poison, but die if having only 1 hitpoint (which would be the next turn after being reduced to 1 hitpoint). I don't know why it works inconsistently, maybe it depends on the order of some events being triggered.

**Comment by white-haired-uncle** [comment]
Hmm, then the code above makes little sense to me (the hp==1 stuff).  As is, harm the unit (leaving at least 1), then if HP==1 kill the unit.  So basically any unit with 17 or less dies on this turn.  Seems wrong in two ways.

Seems it should be if hp==1 kill else hp -= 16.

Of course, there's always the case where some other unit left you at 1HP to mull over as well.

**Comment by white-haired-uncle** [comment]
If an attacker does regular damage, and then on the defender's next turn another 16 which can kill, that's a pretty big jump from regular poison.  If you don't let incinerate kill on that first turn (unless the defender just happens to have 1 HP left), that gives them one turn to find a healer/etc.  That seems reasonable if you don't want it to be too powerful.  And if that's the way you remember it, there's probably a reason so I suspect just move the -16 after the -1/kill?

**Comment by Dugy** [comment]
Yeah, it makes more sense to reduce the unit to 1 hp and kill in the next turn.

**Comment by white-haired-uncle** [comment]
I was going to add that checking for 1 HP might also allow a Shaman, for example, to keep the unit from dying even though it can not cure (depending on order of events).  However, I noticed that incinerate is removed by any adjacent unit with abilities.heals which includes the +4 heals Shaman (tested).  I wonder if this should be abilities.heals.poison=="cured" (based on random sample of exactly one (+24) healer) and/or abilities.heals.poison=="slowed" (a heals +8 druid), or just abilities.heals.poison!=nil.

**Comment by white-haired-uncle** [comment]
Makes for an interesting strategy, "If you're on fire and can't get help, just stand there and you won't die".  Unless you have healthy, in which case it's okay to move.

**Comment by Dugy** [comment]
I don't think that is what I suggested, but it seems like an interesting idea.

**Comment by white-haired-uncle** [comment]
Sorry, I'm being vague.  The catch is rest healing.  For example, incinerate can never kill a unit with healthy, as it will always rest heal BEFORE the turns refresh event, so its HP will never be 1 when we check it.  For other units, the key is to just stand there, which is kind of the opposite of what one would do when on fire.
