### ISSUE TITLE
Legacy/AMLAs exposed

### ISSUE THREAD

**Issue by white-haired-uncle** [Dugy/Legend_of_the_Invincibles#698]
I never knew you could do this.  Looks like it goes back to 1.16 at least.  

When taking an AMLA, if you highlight one and then mouse over your level it will show you which amlas you can take next if you take this one.

![legacy_exposed](https://github.com/Dugy/Legend_of_the_Invincibles/assets/135195815/61a13bdc-fb99-42f2-8aa1-bc3c5c51cfad)

I wonder if the legacy could not be selected until after you choose "aware".  Seems like I looked at that at some point and it had issues.

**Comment by Discontinuum** [comment]
Ah, it can go a step further, that's interesting (I mean, you can learn amlas hovering the mouse over the level but it turns out it works here as well)

> I wonder if the legacy could not be selected until after you choose "aware"
It's chosen back at unit first appearance to prevent choosing desired legacy by reloading I guess

**Comment by Dugy** [comment]
Huh, I never noticed this hover window.

This could be fixed by having the _awareness_ advancement give a meaningless AMLA that would be replaced by the actual _awareness_ advancement.

**Comment by Dugy** [comment]
Okay, it's no longer visible.
