### ISSUE TITLE
patch for :  error scripting/lua: [option]message= is deprecated, use label= instead.

### ISSUE THREAD

**Issue by alain-bkr** [Dugy/Legend_of_the_Invincibles#70]
Hi

There are hundreds of 'errors' in the log 
' error scripting/lua: [option]message= is deprecated, use label= instead. '

I did a simple patch to fix this issues for numerous cases (maybe all ?) : 

the pattern match for the fix is : 
* on one line there is "[option]"
* on the next line there is "message="

In this case, "message="  is replaced by "label="

The sed script
[undeprecator.sh.txt](https://github.com/Dugy/Legend_of_the_Invincibles/files/1629556/undeprecator.sh.txt)

The patch
[option-message_2_option-label.diff.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/1629558/option-message_2_option-label.diff.gz)

I applied this patch and playedwithout problem.

**Comment by Dugy** [comment]
If I applied it, it would break compatibility with wesnoth 1.12. When 1.14 comes out and 1.12 becomes obsolete, I will apply it. The errors are harmless, so I am not going to add an ifver clause to all of these lines.

Leaving it open so that it would not be forgotten.

**Comment by alain-bkr** [comment]
yes i understand 

Maybe   it would be nice to have a 1.13.11+  version for easier debuggingwith smaller logs, and much less warnings :-)

i think #69 was caused by 1.13.0 (something in the git changelog about this) , so maybe the fix is 1.13 only too ?
