### ISSUE TITLE
Invalid color in range: cyan

### ISSUE THREAD

**Issue by white-haired-uncle** [Dugy/Legend_of_the_Invincibles#703]
No idea here. 

```
20240320 00:41:48 error display: caught config::error while processing color-range RC: Invalid color in range: cyan
20240320 00:41:48 error display: bailing out from RC

spartan$ grep -r cyan
utils/item_list.cfg:        image="items/boots.png~RC(magenta>cyan)"
utils/item_list.cfg:        image=items/boots.png~RC(magenta>cyan)~CS(50,50,150)
utils/item_list.cfg:        image="items/boots.png~RC(magenta>cyan)"

```

**Comment by Dugy** [comment]
What happens if you replace `cyan` with `blue`?

**Comment by white-haired-uncle** [comment]
error goes away

**Comment by Dugy** [comment]
I think that the problem is that `cyan` isn't defined as a colour palette. I don't know there they are defined, I am sure that `blue` is defined, maybe `teal` is also defined, and it's quite close to `cyan`.

**Comment by white-haired-uncle** [comment]
teal works too.  I think it looks a little better.

cyan is used for flying, iced, and eidolon's boots.  Do you want to use same for all, or blue for one to distinguish it from the others?

**Comment by Dugy** [comment]
Maybe `teal` for iced boots and `blue` for the others, or something else if you find that suitable.
