### ISSUE TITLE
[micro_ai] tag (recruit_random) contains invalid parameter: randomness

### ISSUE THREAD

**Issue by white-haired-uncle** [Dugy/Legend_of_the_Invincibles#709]
Ch1, Sc1:

[micro_ai] tag (recruit_random) contains invalid parameter: randomness (see Lua console for stack trace)

```
Running preload scripts...
$
wesnoth.dofile 'lua/wml-tags.lua'
wesnoth.dofile 'lua/feeding.lua'
wesnoth.dofile 'lua/diversion.lua'
wesnoth.dofile 'lua/stun.lua'

$  wesnoth.dofile("~add-ons/Legend_of_the_Invincibles/lua/main.lua")
Warning:
  [micro_ai] tag (recruit_random) contains invalid parameter: randomness
stack traceback:
        ai/micro_ais/micro_ai_helper.lua:341: in field 'micro_ai_setup'
        lua/wml/micro_ai.lua:53: in local 'cmd'
        lua/wml-utils.lua:145: in field 'handle_event_commands'
        lua/wml-flow.lua:5: in function <lua/wml-flow.lua:4>
        [C]: in ?

```

```
        [micro_ai]
            side=4
            action=add
            ai_type=recruit_random
            randomness=1
        [/micro_ai]


```

https://wiki.wesnoth.org/Micro_AIs#Random_Recruitment_AI_.28ai_type.3Drecruit_random.29

The scenario plays fine, just tosses an error in the log (possibly only with debug/wml-debug on).  But this was obviously included for a reason, and I'm thinking it's probably not doing anything so...

**Comment by Dugy** [comment]
I think that the setting is no longer supported and it's now configured differently. Removing it should be inconsequential.
