### ISSUE TITLE
some errors in log (after filtering)

### ISSUE THREAD

**Issue by alain-bkr** [Dugy/Legend_of_the_Invincibles#71]
Hi

I filtered out already know warnings , i can provide the saved games i you want.

Something about auto-storeunit  (from a place in sight, with nothing special ?)
[auto-store.err.txt](https://github.com/Dugy/Legend_of_the_Invincibles/files/1629628/auto-store.err.txt)

* errors on images "portraits/humans/transparent/iron-mauler.png" 
fgrep -l "portraits/humans/transparent/iron-mauler.png" .. -r
  ../wesnoth/data/tools/wmllint
  ../Legend_of_the_Invincibles/units/Destroyer.cfg
  ../Legend_of_the_Invincibles/units/Blackguard.cfg
  ../Legend_of_the_Invincibles/units/demon_infiltrators.cfg
  ../Legend_of_the_Invincibles/scenarios4/14_The_Kingslayer.cfg

* errors on images 
20180107 18:08:54 error display: could not open image 'misc/ellipse-hero-leader-top.png'
20180107 18:08:54 error display: could not open image 'misc/ellipse-hero-leader-bottom.png'

* the log after filtering : 

[l4.txt](https://github.com/Dugy/Legend_of_the_Invincibles/files/1629633/l4.txt)

* the full log :
[20180107.log](https://github.com/Dugy/Legend_of_the_Invincibles/files/1629636/20180107.log)

**Comment by Dugy** [comment]
Any idea what's with that Iron Mauler? That image exists in portraits/humans/transparent.

**Comment by matsjoyce** [comment]
In 1.13 they removed the `transparent` from the path, so it's just `portraits/humans/iron-mauler.png`.

**Comment by Dugy** [comment]
This would require a load of changes, not just with Iron Mauler. All of them would break compatibility with 1.12, so I better leave it like this until 1.12 becomes obsolete.

**Comment by matsjoyce** [comment]
Yeah, agreed.
