### ISSUE TITLE
Toxic_Sun dwarf ally

### ISSUE THREAD

**Issue by white-haired-uncle** [Dugy/Legend_of_the_Invincibles#712]
The dwarf is our ally.  Should he get more gold on higher difficulties, or less?  Intentional, or typo?

https://github.com/Dugy/Legend_of_the_Invincibles/blame/0db18664ec7b18911f92ddde668d71154df53d07/scenarios1/12_Toxic_Sun.cfg#L130

FWIW, I've always found this one to be pretty reasonable in terms of difficulty.  This is struck me as odd.

**Comment by Dugy** [comment]
I think the reason for that was that he'll need more survivability if the enemies are stronger, because your possibilities of protecting him are limited.

**Comment by white-haired-uncle** [comment]
Makes sense, though there's no requirement that he survive. 

Again, it works fine, just looked out of place.

**Comment by Dugy** [comment]
There's no requirement that he survives, but his presence won't be known if he does too early.

**Comment by white-haired-uncle** [comment]
That would break the dialog.  I suppose it should be updated in just case he dies very quickly.

**Comment by Dugy** [comment]
Done.
