### ISSUE TITLE
Beelzebulb level up but stay wounded

### ISSUE THREAD

**Issue by alain-bkr** [Dugy/Legend_of_the_Invincibles#72]
Hi

With a very rcent Loti and wesnoth 1.13 , another example of a Loti special unit not being completely cured at level-up

it seems the problem is specific to Loti units, and does not concern "standard" ones.

Games/git-wesnoth/Legend_of_the_Invincibles$ LANG=en git status && git log | head -3
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
commit 62288b0b3240411dfadbd5705f6e3f7ddaf7afbb
Author: Dugy 
Date:   Sat Jan 20 07:03:26 2018 +0100

Games/git-wesnoth/wesnoth$ LANG=en git status && git log | head -3
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
commit 24e40cc0b18a9167f1a910b946cc64586450a77b
Author: Charles Dang 
Date:   Sat Jan 27 02:27:21 2018 +1100

[LotI1-Thirst_for_Adventures-Sauvegarde_automatique41.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/1670855/LotI1-Thirst_for_Adventures-Sauvegarde_automatique41.gz)

[LotI1-Thirst_for_Adventures_Tour_41-beelzebub-leveled-up-but-not-healed.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/1670854/LotI1-Thirst_for_Adventures_Tour_41-beelzebub-leveled-up-but-not-healed.gz)

[20180127.log.cleaned.txt](https://github.com/Dugy/Legend_of_the_Invincibles/files/1670882/20180127.log.cleaned.txt)

**Comment by Dugy** [comment]
I have removed the e-mail addresses. Please don't write anyone's e-mail address to a public location that can be looked up by web crawlers.

It makes sense. I will have really have to have a look at it, but I am quite busy right now.

**Comment by konecnyjakub** [comment]
Beelzebub does not have this in his advancement, unlike other unit types:

```
 [effect]
        apply_to=hitpoints
        heal_full=yes
[/effect]
```

**Comment by Dugy** [comment]
@konecnyjakub That is deliberate. If he fully healed during combat, it would be really, really bad. So I made the advancement's outcome unpleasant, but not as bad as full heal.

**Comment by konecnyjakub** [comment]
Very well. It just looked like an obvious cause to

> not being completely cured at level-up

**Comment by alain-bkr** [comment]
(sorry for the email address)

ok, it may be  feature, not a bug :-) , i just reported it, in case it could be useful .
( it needed some efforts to make this happen ! )

**Comment by Dugy** [comment]
There are many other boss units that don't heal on advance, btw.
