### ISSUE TITLE
Invalid WML  remove_event   ... when beelzebulb appears

### ISSUE THREAD

**Issue by alain-bkr** [Dugy/Legend_of_the_Invincibles#73]
hi

this messages appears just at the end of the "dialog"  with bellezelbub 

[LotI1-Thirst_for_Adventures-Sauvegarde_automatique18.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/1670861/LotI1-Thirst_for_Adventures-Sauvegarde_automatique18.gz)

![invalid_wml_just_after_beelzebulb_2018-01-27_20-11-58](https://user-images.githubusercontent.com/31039036/35480058-cbe85af2-0406-11e8-8a6d-d284fa929564.png)

I don t know what it does, but #62 looked so inocuous...that i report this one too :-)

**Comment by Dugy** [comment]
It isn't related to that bug. This one wasn't mentioned yet.

**Comment by Dugy** [comment]
Fixed in 62288b0.
