### ISSUE TITLE
Error in 1.18.0 for "harmer"

### ISSUE THREAD

**Issue by arobinson** [Dugy/Legend_of_the_Invincibles#737]
Found 1 error so far testing LotI in 1.18.0

<img width="819" alt="image" src="https://github.com/Dugy/Legend_of_the_Invincibles/assets/93213/e3c92e01-b082-4913-af5f-c047f7bb9d2f">

Reproduction? (happened after this turn, not sure if it will reproduce depending on what the AI does in the next turn)
[LotI2-Tundra Turn 2.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/14817592/LotI2-Tundra.Turn.2.gz)

The good news:
1. Loading the mod fine in 1.18
2. Loading a 1.16 save game of LotI working just fine, so far at least
3. Scenario starts working
4. Item information, crafting, unit information dialogs all working so far

**Comment by arobinson** [comment]
I think it is due to the incinerate weapon special

**Comment by Dugy** [comment]
It was probably an ability dealing periodic damage to adjacent enemies.

I also added a check to prevent this from happening. The update should take place immediately, just do a git pull and load your last save file.
