### ISSUE TITLE
DROPS_EXT

### ISSUE THREAD

**Issue by white-haired-uncle** [Dugy/Legend_of_the_Invincibles#741]
In The_Real_Enemy there are lots of drops, even though the chance is low and you don't kill that many units.  While investigating, I ran into this.  Is this redundant, or was something else intended?  I'm a bit dense today, but this doesn't look right to me.

```
        [if]
            [variable]
                name=unit.canrecruit
                equals=yes
            [/variable]
            [and]
                [variable]
                    name=unit.canrecruit
                    equals={BOSSES}
                [/variable]
            [/and]
            [then]
                {DEFAULT_DROP_ITEM $x1 $y1 {WEAPONS}}
            [/then]
        [/if]

```

**Comment by white-haired-uncle** [comment]
Seems to me the only way if canrecruit=yes and if canrecruit={BOSSES} can be true is if BOSSES=yes.  Which should be the same as if BOSSES==yes.

**Comment by Dugy** [comment]
Yes, normally it's set to _yes,_ so bosses always drop.

**Comment by white-haired-uncle** [comment]
Ah, it's just a weird way of saying if {BOSSES}=yes due to the way wml deals with conditionals.

I still have to figure out why so many drops in this one.  If I get around to it.
