### ISSUE TITLE
Elvish Sylph cannot equip a staff

### ISSUE THREAD

**Issue by arobinson** [Dugy/Legend_of_the_Invincibles#743]
The new "Elvish Sylph" does not have a staff equipment spot. I presume this is a bug as the character's graphics even include a staff. The unit can still have one if one is given to the enchantress before she advances, but this does not seem correct to me.

**Comment by Dugy** [comment]
I only remembered this in the middle of doing some other commit, so I never quite did this change even though I knew of it. Now you've caught me while I was just making tea.

**Comment by arobinson** [comment]
Thank you, hope your tea was still warm and not over-steeped
