### ISSUE TITLE
Last Enemy error with 1.18

### ISSUE THREAD

**Issue by arobinson** [Dugy/Legend_of_the_Invincibles#745]
This error occurred while Lethalia was being attacked in "The Last Enemy"

<img width="900" alt="image" src="https://github.com/Dugy/Legend_of_the_Invincibles/assets/93213/3af6cca5-d40d-46b5-a36c-24ed91ed655a">

Save game right before it happened:
[LotI2-The Last Enemy Turn 3.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/14830355/LotI2-The.Last.Enemy.Turn.3.gz)

**Comment by arobinson** [comment]
Think it is when she reproduces at the end of her turn

**Comment by Dugy** [comment]
I couldn't replicate it. Maybe it's fixed on latest master.

What I did:
End turn (all units had used up their moves and attacks)
The enemies will attack Lethalia until she dies, triggering no errors

**Comment by arobinson** [comment]
Lethalia did not die when I had the issue. I also had it on subsequent turns until I won

**Comment by Dugy** [comment]
The problem was that the evil Lethalia disappeared and as a result, she could not be checked if she was supposed to be killed by the attack or not. The problem could also be triggered by hitting one of her as a secondary target with whirlwind.
