### ISSUE TITLE
enemy (at least) wrath not wrathing very wrathfully

### ISSUE THREAD

**Issue by white-haired-uncle** [Dugy/Legend_of_the_Invincibles#751]
I noticed recently that lesser lethargy doesn't seem to do much.  The wrath is getting set, but it doesn't seem to do anything.  I know wrath on side 1 was working in the past, I haven't checked recently.

In the attached, BZB has -2 wrath_intensity.  Serves him right.  Attack him with the dwarf just to his north and you'll see the attack GUI says he'll do 10 damage, and he does.

Reload, and attack BZB with Argan's great underwear (advance him and take crossbow marksman first?).  In my case, BZB's wrath intensity went to -5.  Attack him with the dwarf just to his north and you'll see the attack GUI says he'll do 10 damage, and he does.

[LotI1-Siege Turn 10.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/14910297/LotI1-Siege.Turn.10.gz)

**Comment by Dugy** [comment]
Lethargy and wrath don't work on units controlled by AI. This is not intended.

**Comment by white-haired-uncle** [comment]
Not intended as in it's not working correctly, or it's not intended that wrath/lethargy work for AI units (in which case, why have a lesser lethargy special available to the player)?

**Comment by Dugy** [comment]
Not intended as it's not working correctly. Human controlled units are given a hidden weapon special called latent_wrath which causes the wrath/lethargy variable to have an effect. It's missing on other units, probably as an oversight while moving that code into lua.

The latent_wrath weapon special should be changed to an ability and added to every unit without it by the code that modifies the wrath variable.

**Comment by white-haired-uncle** [comment]
I now see how the latent_wrath works and why AI units don't.

What I don't get is how you would change that from a weapon special to an ability.  Don't you need the [damage] weapon special to adjust the damage (before slow/resistance/etc)?

**Comment by Dugy** [comment]
If a weapon special appears in `[abilities]`, it behaves as an ability that grants the weapon special. It's a relatively new addition.

**Comment by white-haired-uncle** [comment]
Cool.  I'm starting to step through this now, I've moved it from attacks to abilities and I'm starting in on the various levels of events.  I'm really wondering if there is (or will be) any reason to have unit.variables.wrath_intensity now, since it's (probably) just going to match unit.abilities.damage.add.

**Comment by Dugy** [comment]
> I'm really wondering if there is (or will be) any reason to have unit.variables.wrath_intensity now, since it's (probably) just going to match unit.abilities.damage.add.

The problem is that there may be multiple `[damage]` abilities other than wrath.

**Comment by white-haired-uncle** [comment]
I'm not seeing the problem.  There could be other [damage] abilites, but we won't conflict with them as we only touch the one with id=latent_wrath.

**Comment by Dugy** [comment]
Your question was not explaining it properly. It's not an issue when I see it in your Pull Request.

**Comment by white-haired-uncle** [comment]
Yeah, I knew when I wrote unit.abilities.damage.add that I was leaving out the "where unit.abilities.damage.id = latent_wrath" part, but I didn't know how to express that.

**Comment by Dugy** [comment]
All wrath should be reset to zero at scenario end. Some time is supposed to pass between scenarios, long enough for all wrath to cool down.

**Comment by white-haired-uncle** [comment]
Before I go looking, any idea where that used to happen?
