### ISSUE TITLE
Removing objects from Efraim

### ISSUE THREAD

**Issue by white-haired-uncle** [Dugy/Legend_of_the_Invincibles#759]
In Way of Assassins, a mage says something about being able detect assassins, but nothing actually happens.  I gave everyone on side 1 temporary illumination so they couldn't use nightstalk.

```
       [modify_unit]
            [filter]
                side=1
            [/filter]
            [object]
                id=shine_on
                [effect]
                    apply_to=new_ability
                    [abilities]
                        {ABILITY_ILLUMINATES_GREAT}  # combat disadvantage, negates nightstalk
                        #{ABILITY_CONCEALMENT}  # encourage assassin-like behaviour?  Contrary to Mage's comments above
                    [/abilities]
                [/effect]
            [/object]
        [/modify_unit]
```

And then at the end, just before the dopps are stored, I removed that one object:

...

        [remove_object]
            side=1
            object_id=shine_on
        [/remove_object]
 
Well, come the next scenario the dopps are fine, but E's attack show as if he has removed all his weapons.  The weapons and all their specials show up in Unit Info, but the weapon names, their specials (like suck, not specials inherent to the unit type), and the furious attack are all missing (and the damage is really low).  Drop Doombringer to the ground and everything seems to fix itself.

Is there something about E that I can't just remove an object like it seems I can for everyone else?  [Edit: probably not E vs everyone else, but doppelgangers vs everyone else]

P.S.  I'm thinking about giving them concealment to try to encourage player to play like an assassin.  But that contradicts the whole "I can see you" thing.  Thoughts?  I made the enemies VERY tough (they can kill E) but -1MP so he can sneak around them.  I'm thinking give concealment and change the mage's comment to say something like "can't hide in the dark" vs just "can't hide".

**Comment by white-haired-uncle** [comment]
Looks like doing it that way also adds the object to every unit, including the recall list, but remove on removes from units on map.

More: https://forums.wesnoth.org/viewtopic.php?t=56648

**Comment by white-haired-uncle** [comment]
I was done with this, looking at something completely unrelated when my eye fell upon [object] duration=scenario.

I'm just going to assume this would have the same issue as remove_object.  That, or I'll pretend I didn't see it.

**Comment by Dugy** [comment]
> I was done with this, looking at something completely unrelated when my eye fell upon [object] duration=scenario.

This breaks things in LotI. Same as `[remove_object]`. Both of them will remove the `[object]` and then rebuild the unit using its modifications. This, however, ignores LotI-specific properties, so a lot of item effects will be missing.

You can fix this by using the LotI-specific tag `[update_stats]` on the unit afterwards. You'll probably want to use `[remove_object]` and follow it with `[update_stats]` afterwards.
