### ISSUE TITLE
Execution attack does half damage

### ISSUE THREAD

**Issue by white-haired-uncle** [Dugy/Legend_of_the_Invincibles#764]
The Predator should level up on this turn. If you take the execution AMLA you get an attack that does 51% of the damage of the attack it clones.  I'd note I have Archer's Armor and Hatred/SoulThrash to improve the original bow attack.  I just can't see any reason to take this "upgrade", except maybe against a demon with regrowing or whatever the other one is that's similar.  Is something odd going on here, or is it just a bad deal?  

[LotI1-Eastern Guardian Room-Auto-Save7.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/14973817/LotI1-Eastern.Guardian.Room-Auto-Save7.gz)

It's also curious what Warguard is doing in my inventory under limited.

**Comment by Dugy** [comment]
> Is something odd going on here, or is it just a bad deal?

Nothing odd, the code says that the attack gets -45% damage compared to the original. I admit that the penalty may be too high.

> It's also curious what Warguard is doing in my inventory under limited.

Version transition problem. It was supposed to be gauntlets. I reused an existing item number, assuming it was unobtainable for long (the _Tome of Liches_ from before it was moved to the super item drop pool), but that assumption might have been wrong.

**Comment by white-haired-uncle** [comment]
I'm not really sure what the penalty is for.  Combining all your attacks would be good against regrowing or Old F(r)iend (not relevant here), but that's all I can think of.  And now that I think about it, it's of no use against regrowing.  Unless there's something I'm missing, I wouldn't take it even if it did 100% of the original damage unless the chance to hit was greatly increased.

I guess it might have value if you don't want to get hit in return.  But in the case where this would be of benefit, I just wouldn't risk the advanced unit.

**Comment by Dugy** [comment]
I was looking at my notes and it looks like Predator is relatively unpopular. I will change the penalty for the single shot attack. For now, I really need to come up with a few new weapon specials that would be useful for shooters, since Champion Bowman is also not used much.
