### ISSUE TITLE
lavaflow damage

### ISSUE THREAD

**Issue by white-haired-uncle** [Dugy/Legend_of_the_Invincibles#767]
https://github.com/Dugy/Legend_of_the_Invincibles/blob/b383b40ea6a22d75f3446b0541a108cdda3409c3/utils/chapter5_utils.cfg#L658-L669

Says 50, uses 20 damage so the GUI shows 20 (minus fire resistance).  Then the actual damage is 5d10 fire.

Set damage=50 here and in [harm_unit] so everything matches?

**Comment by Dugy** [comment]
Yeah, 20 damage is too little for lava.
