### ISSUE TITLE
Advancing units dies in prestart in 1.13

### ISSUE THREAD

**Issue by matsjoyce** [Dugy/Legend_of_the_Invincibles#78]
I've tracked down the cause of https://forums.wesnoth.org/viewtopic.php?p=624478&sid=e155f2d4485ae6ad0d1c0af40367974d#p624459. What happens is:

 - Scenario prestart:
     - `{ADVANCE_UNIT id=Lethalia Lethalia_god}`
     - This causes the `pre advance`, `advance` and `post advance` events to be fired
     - In the `post advance` event `{UPDATE_STATS}` is used, which kills the unit and fires `update_stats`
     - The plot twist is that `update_stats` is an event only created when the `prestart` event in `{GLOBAL_EVENTS}` creates an `Event Loader` unit, and due to ordering of events in 1.13 that happens after this.
     - No `update_stats`, so unit stays killed
 - `Event Loader` created in `{GLOBAL_EVENTS}`

The events in 1.13 seem to be ordered by definition, so moving `{GLOBAL_EVENTS}` to the top of the scenario will fix this, but I'm not sure if it will cause any other problems. I can go ahead and make this change in all scenarios if you want?

**Comment by Dugy** [comment]
Go on, it shouldn't break anything, I can't think of a reason why should global events depend on scenario-specific events unless there was some kind of subscriber pattern used - and I am fairly sure I didn't know of that technique when I was writing LotI.
