### ISSUE TITLE
Odd soul eater advancement

### ISSUE THREAD

**Issue by white-haired-uncle** [Dugy/Legend_of_the_Invincibles#783]
Start with the turn 51 save.  E has 224/225 soul eater kills.   Kill the necro.  Most of the time, E will still have 224/225.  Now kill the Malefactor with the Predator.  E will take his soul eater advancement and the Predator will take an AMLA (you can also use the dwarf who won't advance, but E will).  If you watch very carefully you can see 0/337 float above E.

This isn't 100% reproducible.  Sometimes E will take the soul eater advancement immediately like he is supposed to.  The 51-2 save is at a point where he got the kill and should have SE advanced, but before the next unit's kill causes him to do so.

[LotI1-Power Station Turn 51-2.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/15196441/LotI1-Power.Station.Turn.51-2.gz)
[LotI1-Power Station Turn 51.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/15196442/LotI1-Power.Station.Turn.51.gz)

**Comment by Dugy** [comment]
Even though it's fixed, it will be still happening in save files from scenarios started before the update.

**Comment by white-haired-uncle** [comment]
Could this be related to #774?

I saw that as well, but forgot to save it.

**Comment by Dugy** [comment]
Very likely.
