### ISSUE TITLE
Need bigger animation for explosive unit

### ISSUE THREAD

**Issue by white-haired-uncle** [Dugy/Legend_of_the_Invincibles#789]
https://github.com/Dugy/Legend_of_the_Invincibles/blob/7f85464f54efbb5db052114332b8a5077f96468a/utils/abilities_events.cfg#L56

I just used the projectiles/fireball-impact-* series.  It really needs something that blows out (to adjacent tiles, since those units will take damage) and not just up.

**Comment by Dugy** [comment]
Done. You can try it.
