### ISSUE TITLE
Nightmare Cellar

### ISSUE THREAD

**Issue by white-haired-uncle** [Dugy/Legend_of_the_Invincibles#796]
I just wanted to change status=not_living, but that led me to Nightmare Cellar where I'm seeing a number of potential problems.  After fixing Lilith's side so that she appears like she's supposed to, I'm seeing these:

```
20240514 00:13:30 error engine: Formula in WML string cannot be evaluated due to Expected another token
	--> "
20240514 00:13:30 error engine: Formula in WML string cannot be evaluated due to Illegal unary operator: '*'
	--> "
```

which I suspect are caused by quests.lilith_deaths not existing.  I debugged my way to this scenario, but looking at the code I think this will happen the first time you meet her (at least) no matter how you get there.

https://github.com/Dugy/Legend_of_the_Invincibles/blob/8dae417d6df6f2e0a3496872008e8d3af22574ec/utils/chapter9_utils.cfg#L571-L579

I actually first thought that error might be coming from this:

https://github.com/Dugy/Legend_of_the_Invincibles/blob/8dae417d6df6f2e0a3496872008e8d3af22574ec/utils/chapter9_utils.cfg#L516

I assume that's supposed to be met_lilith ?  It's not the cause of my current error, but I still think it's wrong.

**Comment by white-haired-uncle** [comment]
Also, that event will leave variables uncleared if you don't activate all of statues.  I suspect this will clear them up, but I need to test re-entering the scenario

```
    [event]
        name=victory
        {CLEAR_VARIABLE gender_{X2}_{Y3},gender_{X3}_{Y1}}
    [/event]

```

**Comment by Dugy** [comment]
> which I suspect are caused by quests.lilith_deaths not existing.

Very likely that that is the cause. I didn't assume it possible to get to Nightmare Cellar without killing Lilith a few times.

> Also, that event will leave variables uncleared if you don't activate all of statues.

That's also possible.

**Comment by white-haired-uncle** [comment]
Activating the statues is weird.  The first one activates when you come close to it, but (moving north) the second one doesn't activate until you move past it.  The third (slightly northeast of the second) I can't activate.

It might be set that way to avoid activating two groups at once, or it's just got some bugs.  What do you think about replacing the range with location(litlith statue), radius=3?

**Comment by Dugy** [comment]
> It might be set that way to avoid activating two groups at once, or it's just got some bugs. What do you think about replacing the range with location(litlith statue), radius=3?

Yeah, as long as the radius corresponds to a similarly sized area than the coordinates.
