### ISSUE TITLE
Lethalia and her staff

### ISSUE THREAD

**Issue by white-haired-uncle** [Dugy/Legend_of_the_Invincibles#799]
In the attached, notice that L is holding Shawshank's Staff.  Move her south, where she will automatically pick up L's Staff (which might not be what I want) and transform to Lich.  Open the Inventory to see she is holding L's Staff, though for some reason the attack is fire.  Click the L's Staff button to find she's hold's Shawshank's Staff.  Pick up her armor and note that "requires L's Staff" is bolded, as if she is holding it.

[LotI2-Who Am I-Auto-Save17.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/15337189/LotI2-Who.Am.I-Auto-Save17.gz)

**Comment by Dugy** [comment]
Without looking at the code, I am quite sure the problem is that the staff is picked up in the cutscene without calling the appropriate lua function, because the scenario code does not reflect the current state of the item code.

**Comment by white-haired-uncle** [comment]
Simply changing the order such that she picks up the staff after transform fixes most of the issue, however:

1) any staff she is carrying is lost
2) she may not want to take the staff

I think the easy fix is just to place the staff and moving her to it (I assume that'll trigger item pick) instead of placing an image and forcing it upon her.  But this could mean she finds her staff, remembers some stuff, but doesn't decide to wield the staff.  I don't know if this messes with the story or not.
