### ISSUE TITLE
story text

### ISSUE THREAD

**Issue by white-haired-uncle** [Dugy/Legend_of_the_Invincibles#800]
Something changed re: beginning of scenario?  I'm seeing stuff like this lately:

![Screenshot_2024-05-16_21-33-29](https://github.com/Dugy/Legend_of_the_Invincibles/assets/135195815/ab146651-e952-4b07-9aa8-5dfe59f0ae5a)
![Screenshot_2024-05-16_21-34-01](https://github.com/Dugy/Legend_of_the_Invincibles/assets/135195815/e0cfdd96-886e-4d60-88fa-cc971a15774a)

**Comment by Dugy** [comment]
I have no idea how could I have done this. I think the reason is that you are using 1.19 and some wild changes are being done there, I don't think there is a way LotI code could have caused that.

I could try to run a save file you send me on 1.18 to verify if it is really something in 1.19.

**Comment by white-haired-uncle** [comment]
I tried 1.16 and it's definitely new.

**Comment by white-haired-uncle** [comment]
https://github.com/wesnoth/wesnoth/issues/8878

**Comment by Dugy** [comment]
It happens also on 1.18. But it looks like a rendering problem, I have strong doubts an add-on could have caused that. Good that you've created that issue.
