### ISSUE TITLE
Demigodess?

### ISSUE THREAD

**Issue by white-haired-uncle** [Dugy/Legend_of_the_Invincibles#803]
This is about as minor a point as it gets, but it struck me as odd.

![Screenshot_2024-05-18_22-41-08](https://github.com/Dugy/Legend_of_the_Invincibles/assets/135195815/cbe0120c-08e6-4115-904d-31ff275923a1)

![Screenshot_2024-05-18_22-41-40](https://github.com/Dugy/Legend_of_the_Invincibles/assets/135195815/3f1195f8-2d55-4ba8-99c6-192c1553985e)

**Comment by Dugy** [comment]
I didn't think of that.

(which might seem a little curious given that my native language has female forms for everything that can somehow be female)

**Comment by Discontinuum** [comment]
It may make sense considering that LotI uses "Demon Lady" for female Demon Lords
