### ISSUE TITLE
Healing potions aren't working

### ISSUE THREAD

**Issue by arobinson** [Dugy/Legend_of_the_Invincibles#819]
No health gained at all

git commit: `037e43e1c11ea406bdc9d5fce1cbf606c83e95ef`
can reproduce with 
[LotI2-Across the Barren Land-Auto-Save11.gz](https://github.com/user-attachments/files/15749140/LotI2-Across.the.Barren.Land-Auto-Save11.gz)
try to heal Meowyn (Mage of Light) using the potion right by her

Wesnoth 1.18.0

**Comment by Dugy** [comment]
It was broken while removing some information stored inside units to make save files smaller. I fixed it. The fix should apply instantly (e.g. just do a git pull and reload the last save file).
