### ISSUE TITLE
Only one unit dies by incinerate per turn

### ISSUE THREAD

**Issue by arobinson** [Dugy/Legend_of_the_Invincibles#821]
In this save game, two goblin knights are incinerated (right middle of the map). Both should die in the next turn, but only one does. One dies and the other loses 3 HP but does not die.

[LotI2-Across the Barren Land Turn 25.gz](https://github.com/user-attachments/files/15855524/LotI2-Across.the.Barren.Land.Turn.25.gz)

**Comment by Dugy** [comment]
Incinerate kills only units that have 1 hitpoints. Those with more than 1 hitpoint take fire damage but will be kept at 1 hitpoint if it would have killed them.

Those two Goblin Knights are at 1 hp and 4 hp, the one at 1 hp is expectedly killed and the one at 4 hp is expectedly reduced to 1 hp. If I use debug mode to set the hitpoints of the one at 4 hp to 1 hp, both are killed.

I could change this behaviour to the more obvious one, but the code is quite prone to regressions and I don't want to break it again.

**Comment by arobinson** [comment]
I figured with the loss of 15, anything at 15 or lower would die. Perhaps just an update on the wording to state the actual behavior?

**Comment by Dugy** [comment]
The wording is quite vague. I can change it to the behaviour you expect, but I am worried it would cause regressions. If you promise you will test it properly after me, I can do it.
