### ISSUE TITLE
All swords are Sword of Krux

### ISSUE THREAD

**Issue by white-haired-uncle** [Dugy/Legend_of_the_Invincibles#826]
3.2.8, reported on 1.18.1 and I tested on 1.19.something.

Skip tutorial.  In S1, have Delly drop Twinkling Sword.  Have E replace SoK with TS.  Click on TS button and see that Items detail shows him holding SoK, and there's an SoK in the inventory.

Unequip SoK, go back to items, click on TS,  You know have three SoK.  Repeat and get more.

I swear something very much like this was fixed recently, probably since 3.2.8, but I don't remember the details.

Note:  You must skip tutorial to reproduce.

**Comment by white-haired-uncle** [comment]
```
        [object]
                name=_"Sword of Krux"
                number=605
                sort="sword"
        [/object]
        [trait]
                description=_"Geared: This unit is equipped with items. This is just to easily identify it on the recall list."
                id="geared"
                name=_"GEARED"
        [/trait]
        [object]
                name=_"Potion of Steel Skin"
                number=130
                sort="potion"
        [/object]

```

The difference here is that sort= is missing (for both the above) if you skip the tutorial.

Strange, this is probably related to my changes to items.  If I only tested one, I would have thought I tested skipping tutorial, not playing.

**Comment by white-haired-uncle** [comment]
Saw another of these today.  Seems skipping the tutorial is pretty common.  Might be wise to push a new stable, at least with #827

**Comment by Dugy** [comment]
Is the current github version stable enough? There weren't many recent changes or new issues, so it probably is, but I'd like to see a confirmation.

**Comment by white-haired-uncle** [comment]
It was (I thought) when I quit messing with a while back (at least part 1, which is what I played several times).

**Comment by Dugy** [comment]
Not many changes were done recently. If no new error reports came out, I suppose it's safe to release it.
