### ISSUE TITLE
tome of liches animations

### ISSUE THREAD

**Issue by white-haired-uncle** [Dugy/Legend_of_the_Invincibles#829]
I think there are a couple issues here.  In amla.cfg, it looks like there are two attacks, shadow wave and chill wave added, and the intention is to add four animations, one male and one female for each new attack.  However:

1. There are three effects that filter on female and one that filters on male.
2. There are at least two instances where the name= of the effect doesn't match the name= of the [filter_attack], for example...

```
                [effect]
                        apply_to=new_animation
                        name=shadow wave
                        [filter]
                                gender=female
                        [/filter]
                        [attack_anim]
                                [filter_attack]
                                        name=chill wave

```

**Comment by Dugy** [comment]
Fixed. This is why copypasting is bad.
