### ISSUE TITLE
Efraim campaign 1: swords are permanent

### ISSUE THREAD

**Issue by arobinson** [Dugy/Legend_of_the_Invincibles#830]
I noticed that I still had attacks from a searing ice, I tried to drop Efraim's sword, but it wouldn't. Then it seemed that every time I dropped a sword to the ground, I could just keep dropping items. Looks like the logic is somehow not removing at least swords from Efraim.
[LotI1-Mining Turn 8.gz](https://github.com/user-attachments/files/16395807/LotI1-Mining.Turn.8.gz)

**Comment by Dugy** [comment]
Are you sure you have the fix from #826 ?

**Comment by arobinson** [comment]
```
git pull --ff
Already up to date.
```

I just pulled this morning though. Perhaps this is a fix that doesn't work on existing characters?

**Comment by Dugy** [comment]
No, that fix should have applied immediately, you would only need to reload a file. This is probably some different bug, though it is probably also related to the same change.

**Comment by Dugy** [comment]
Efraim had 3 swords equipped. This wasn't supposed to happen, and caused weird behaviour. Editing the save file to erase the additional swords fixed it.

@white-haired-uncle, this is a consequence of having started before #826 was fixed, right?

**Comment by white-haired-uncle** [comment]
Looks like it.  E has Sword of Krux and Potion of Steel Skin and both are missing sort=, so I'd say this was started before 826 and the tutorial was skipped.   And the issue sounds the same, can repeatedly drop E's sword without getting rid of it.

826 fixes the issue if you start part1 from the beginning, but does nothing to existing saves.  If it's not in the "stable" version on the add-on server, I suspect we'll see this for everyone who skips the tutorial, unfortunately.  I'm thinking perhaps a patch that checks for the issue when E tries to drop a sword, but then you'd be dragging that code around indefinitely, might be easier just to hand fix a few now.

**Comment by Dugy** [comment]
I am quite indifferent about this. I am not against the idea of adding a piece of code that destroys duplicate items, but I usually don't release fixes just to repair bad data in save files, and this isn't even a serious problem with the fix - a couple of additional swords may remain glued on Efraim, nothing that prevents gameplay.

**Comment by arobinson** [comment]
I restarted again, and I think it is fixed, my save probably was just in a corrupted state?

FYI (separate note), campaign 1 AI is very timid, in later levels Efraim rarely ever gets attacked

**Comment by Dugy** [comment]
> I restarted again, and I think it is fixed, my save probably was just in a corrupted state?

Yes, when I was inspecting your save file, Efraim had 3 swords equipped, which was allowed by the bug. It was causing incorrect behaviour. When I deleted them, the errors were gone and were not coming back.

> FYI (separate note), campaign 1 AI is very timid, in later levels Efraim rarely ever gets attacked

If he has stacked bonuses of 3 swords, then they don't attack because they would just do minimum damage and die. Normally, they may be a little timid too for the same reason, which isn't entirely intended, but it's better than if a significant portion of the army suicided on him and let him rush to the leader.

**Comment by arobinson** [comment]
> If he has stacked bonuses of 3 swords, then they don't attack because they would just do minimum damage and die. Normally, they may be a little timid too for the same reason, which isn't entirely intended, but it's better than if a significant portion of the army suicided on him and let him rush to the leader.

It isn't just with that save, but even on a new game. Also well equipped units sometimes don't get attacked, the enemy just surrounds them without attacking. Campaign 2's AI aggression seems to be higher and better implemented for well equipped units

**Comment by white-haired-uncle** [comment]
I touched the AI in maybe three scenarios.

In And Another Orcish Assault, your allies throw themselves at the demons without any hope.  It's kind of hard to watch.  It might be interesting to look at that scenario and one where the enemy won't attack you (or won't attack E/L, or perhaps they "want" to target E/L but chicken out when it's time to get it on???).  I'd guess part of it has something to do with whether a unit's "strength" is visible to the AI or not (e.g. the AI can "see" large defenses, but it has no idea that an enemy demon has regrowing(N) where N is more than the damage the AI could do anyway).

But, yeah, in large part it seems the enemy can either throw themselves at you (and die), or swarm you and make it cut your way through them.  This was something I tried to focus on when working on Hard, how to get the enemy to engage your army, not just your leaders (and how to encourage the player to use their army and not just E/L).

**Comment by Dugy** [comment]
> In And Another Orcish Assault, your allies throw themselves at the demons without any hope. It's kind of hard to watch.

I don't know why they don't swarm them instead.

> I'd guess part of it has something to do with whether a unit's "strength" is visible to the AI or not (e.g. the AI can "see" large defenses, but it has no idea that an enemy demon has regrowing(N) where N is more than the damage the AI could do anyway).

AI does not consider a lot of things. If I understand it correctly, regeneration is considered only when thinking about pulling back units to heal in villages, but I don't think the fast AI does it.
