### ISSUE TITLE
Faerie Incarnation is worse than Shyde

### ISSUE THREAD

**Issue by Discontinuum** [Dugy/Legend_of_the_Invincibles#833]
<img width="580" alt="Screenshot 2024-08-03 at 02 38 01" src="https://github.com/user-attachments/assets/a6cd9996-7329-47c8-99aa-75e11db6ccd1">

**Comment by Dugy** [comment]
I increased her ensnare and thorns damage in f9b2fb9 and weakened the AMLA for these attacks to compensate.

**Comment by Discontinuum** [comment]
nice, thank you
