### ISSUE TITLE
Gold Carryover message for Unimportant Revolution Sceranio is incorrect

### ISSUE THREAD

**Issue by IamTechknow** [Dugy/Legend_of_the_Invincibles#84]
For Scenario 8 Part 7, Unimportant Revolution, the objective message says there is a Early Finish Bonus and 40% of gold is carried over. However, at the end of the scenario, the message box says there is no bonus and 100% of the gold is carried over, which is actually what happens.

I'm not sure whether the objective message is supposed to be what happens or if it really is intended that all gold is carried over, but it should be corrected.

**Comment by Dugy** [comment]
Fixed.
