### ISSUE TITLE
Bonus attacks for doppelgangers don't get animations or sound effects

### ISSUE THREAD

**Issue by Chergnobarp** [Dugy/Legend_of_the_Invincibles#840]
I gave Lethalia Tears of Void, which grants a bonus attack with the guided weapon special. If her doppelgangers use that attack, all you see and hear is an enemy grunting and losing HP.

[LotI1-An Army Is Born Turn 1 staff bug.gz](https://github.com/user-attachments/files/17090041/LotI1-An.Army.Is.Born.Turn.1.staff.bug.gz)

**Comment by Dugy** [comment]
I forgot to write the code for passing animations to doppelgängers.
