### ISSUE TITLE
Unholybane weapon special does not work for Undead Demons

### ISSUE THREAD

**Issue by IamTechknow** [Dugy/Legend_of_the_Invincibles#86]
In abilities.cfg, the filter for the unholybane weapon special does not include the Undead Demon race, which is distinct from the Undead and Demon race, so it does not work for Undead Demons. If this is meant to be the right behavior (that is, undead demons are non-monster creations of magic) then this should be a simple fix

**Comment by Dugy** [comment]
Fixed.
