### ISSUE TITLE
If the have the dark sword of destruction set (including helm and gloves) the Melee attack does not show as sucking health

### ISSUE THREAD

**Issue by kernowboy** [Dugy/Legend_of_the_Invincibles#89]
If the have the dark sword of destruction set (including helm and gloves) the Melee attack does not show as sucking health.

The sword appears to change the attack type to cold from Melee and the ability to suck health disappears 

EDIT: fixed a spelling error that almost rendered it unreadable

**Comment by Dugy** [comment]
Suck does not affect fire, cold and arcane-damage attacks. This is deliberate to offset the advantage of being able to swap damage type when enemies particularly vulnerable to such damage type appear.

**Comment by kernowboy** [comment]
Just strange that it is one of the abilities from the dark helm of destruction and the sword negates this

**Comment by Dugy** [comment]
I could replace it with something to reduce the number of erroneous bug reports. Any recommendations?

**Comment by kernowboy** [comment]
If it is intentional then I have no good way of stating that a certain ability no longer works

**Comment by Dugy** [comment]
It's written in FAQ.
