### ISSUE TITLE
Images not showing in "market" menu

### ISSUE THREAD

**Issue by arobinson** [Dugy/Legend_of_the_Invincibles#90]
Current git "trunk" in use with Wesnoth 1.14.4 on MacOSX via steam. 

Issue is that items do not have images but rather &items/book3.png= for example

See screen shot

**Comment by arobinson** [comment]
![screen shot 2018-08-09 at 10 22 42 am](https://user-images.githubusercontent.com/93213/43912092-8004a802-9bbe-11e8-9454-f798c20a9947.png)

**Comment by arobinson** [comment]
Found in the Lotl1-Long Way Home scenario

**Comment by Dugy** [comment]
I was able to replicate it on BfW 1.14.3 on Ubuntu via backports. I am not sure why it doesn't appear, it might be some change in 1.14 I don't know of. I will have to investigate more.

**Comment by Dugy** [comment]
Fixed in #141
