### ISSUE TITLE
Skellie health bar appears in wrong hex

### ISSUE THREAD

**Issue by arobinson** [Dugy/Legend_of_the_Invincibles#91]
Skellie's health bar and status appears in the hex to the upper right instead of the unit's hex.

See screen shot

Current git "trunk" in use with Wesnoth 1.14.4 on MacOSX via steam.
![screen shot 2018-08-09 at 10 51 56 am](https://user-images.githubusercontent.com/93213/43913497-630f705c-9bc2-11e8-8c17-f5b66bf4ceb4.png)

**Comment by Dugy** [comment]
That is the disadvantage of oversized sprites. But this option was elected on the forums.

**Comment by arobinson** [comment]
I'll see If I can find a fix for this at some point. At the very least, the image could be reduced in size. Having the bars in the wrong location is difficult to use the unit
