### ISSUE TITLE
Invalid WML found unstore_unit variable Ekrathan_store doesn't exist

### ISSUE THREAD

**Issue by arobinson** [Dugy/Legend_of_the_Invincibles#92]
Upon starting the scenario "Invasion" the error appears (see screen shot)

![screen shot 2018-08-21 at 9 39 53 pm](https://user-images.githubusercontent.com/93213/44441623-c5f46c00-a58a-11e8-984e-888374ed8216.png)

Wesnoth 1.14.4 with latest code from github (Mac OSX + Steam)

I'm attaching the file before the first turn as it happens at the start of the turn and Wesnoth failed to load the first turn save game (hung) when I tried.

[LotI1-Invasion.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/2308790/LotI1-Invasion.gz)

**Comment by Dugy** [comment]
I really hate how 1.14 started throwing showstopper bugs in every possible occasion. Avoiding this error needs extra code whenever a unit that may or may not be stored is being unstored.

Fixed it, btw.
