### ISSUE TITLE
Replace redeem upgrade screen with a lua-based GUI

### ISSUE THREAD

**Issue by Dugy** [Dugy/Legend_of_the_Invincibles#95]
It would look very cool and could be easily backported to 1.10 to deal with the iPhone showstopper.

**Comment by edwardspec** [comment]
Will investigate this.

**Comment by Dugy** [comment]
Leave this to me, this is really annoying to learn because of bugs and strange behaviour and I have some experience in it.

**Comment by edwardspec** [comment]
Too late... already wrote most of it.

**Comment by Dugy** [comment]
Very good.

Though I would prefer removing that _provides_ section and listing the unavailable ones below the available ones with red title and a list of redeem advancements the user needs to get first.

And maybe the description could be on a second line.

**Comment by Dugy** [comment]
I think that the problem with clickable red items could be easily fixed by adding a callback to selecting them that would disable to _accept_ button.

**Comment by edwardspec** [comment]
I'm using wesnoth.show_menu(), it doesn't seem to support any callbacks.
https://wiki.wesnoth.org/LuaWML/Display#wesnoth.show_menu

It just takes an array of menu items and returns the index of selected one.

**Comment by Dugy** [comment]
Are you sure that function was available on 1.10?

I thought you were using wesnoth.show_dialog(), which is what I always used for that, even on 1.10. It would also showing additional info, like number of advancements already taken and the amount of redeeems that will be needed to reach the next level.

**Comment by edwardspec** [comment]
Yes, show_dialog() is present in Wesnoth 1.10: https://github.com/wesnoth/wesnoth/blob/1.10/src/scripting/lua.cpp

**Comment by edwardspec** [comment]
Will replace wesnoth.show_menu() with wesnoth.show_dialog() (show_menu was added in Wesnoth 1.13.6).
Not much difference...

**Comment by Dugy** [comment]
Good.

Now when you have wesnoth.show_dialog(), you can easily add callbacks. It's described at https://wiki.wesnoth.org/LuaWML/Display#wesnoth.show_dialog

I can finish it for you if you want, I was busy all day but now I am not.

**Comment by edwardspec** [comment]
I will complete it myself (if you don't mind).
It's a good task for learning.

**Comment by Dugy** [comment]
Good luck.

**Comment by edwardspec** [comment]
Here is how it looks with `wesnoth.show_dialog()`:

![redeem-menu2](https://user-images.githubusercontent.com/1163218/49908150-4288be80-fe8a-11e8-9cb2-1aca75192c28.jpg)

**Comment by edwardspec** [comment]
> and listing the unavailable ones below the available ones with red title and a list of redeem advancements the user needs to get first.

Will add this next.

**Comment by edwardspec** [comment]
Here we go:

![disabled-menu-entries](https://user-images.githubusercontent.com/1163218/49913191-bf716380-fe9d-11e8-9906-ea27e4041b37.jpg)

**Comment by Dugy** [comment]
Closing the issue as you have solved it. Thanks.
