### ISSUE TITLE
Errors in new git version - check_unit_tile not supported, errors on advancement

### ISSUE THREAD

**Issue by arobinson** [Dugy/Legend_of_the_Invincibles#99]
![screen shot 2018-10-24 at 9 13 11 am](https://user-images.githubusercontent.com/93213/47441357-37a88c00-d76d-11e8-9e45-ed96afd6c679.png)
[LotI2-Across the Barren Land Turn 1.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/2511100/LotI2-Across.the.Barren.Land.Turn.1.gz)

[LotI2-Across the Barren Land-Auto-Save1.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/2511103/LotI2-Across.the.Barren.Land-Auto-Save1.gz)

The turn 1 is after the error, auto save is before. To reproduce it just move Efraim to the top of the screen
Wesnoth 1.14.5 on Mac OSX

**Comment by arobinson** [comment]
Also advancement doesn't work anymore. 

Same save game, just have Efraim level up

![screen shot 2018-10-24 at 9 17 43 am](https://user-images.githubusercontent.com/93213/47441614-c1f0f000-d76d-11e8-8b11-9d71aa9c9ed5.png)

**Comment by arobinson** [comment]
Advancement still not working after pulling the latest (pre_advance_stuff error still happens)

**Comment by Dugy** [comment]
The problem is that some lua files aren't loaded. Can you please check the log because I can't replicate the error to see it?

**Comment by arobinson** [comment]
New save file, error happens on start of first turn, no actions needed (check_unit_tile one). This is on an existing save, but did a 'git pull' then reopened Wesnoth and did an F5 to be sure before loading a start of mission file. 

Here is the log with the load error:
`Battle for Wesnoth v1.14.5
Started on Sat Oct 27 08:49:40 2018

Automatically found a possible data directory at /Users/USER/Library/Application Support/Steam/SteamApps/common/wesnoth/Wesnoth.app/Contents/Resources

Data directory:               /Users/USER/Library/Application Support/Steam/SteamApps/common/wesnoth/Wesnoth.app/Contents/Resources
User configuration directory: /Users/USER/Library/Application Support/Wesnoth_1.14
User data directory:          /Users/USER/Library/Application Support/Wesnoth_1.14
Cache directory:              /Users/USER/Library/Application Support/Wesnoth_1.14/cache

Setting mode to 1600x956
20181027 08:49:42 warning general: no location found for 'data/add-ons/Kill_the_King/translations', skipping textdomain
Checking lua scripts... ok
20181027 08:49:52 error scripting/lua: In function lua_kernel::run(): Lua Error:
  When executing, Lua runtime error: ~add-ons/Legend_of_the_Invincibles/lua.lua:1: bad argument #-1 to 'dofile' (file not found)
stack traceback:
	[C]: in field 'dofile'
	~add-ons/Legend_of_the_Invincibles/lua.lua:1: in main chunk
	[C]: in field 'dofile'
	[string " wesnoth.dofile("~add-ons/Legend_of_the_Invin..."]:1: in main chunk
20181027 08:49:56 warning unit: Unknown attribute 'animate' discarded.
Invalid WML found: [check_unit_title] not supported (3)
20181027 08:50:02 error engine: failed to auto-store $second_unit at (-999,-999)
20181027 08:50:02 error engine: failed to auto-store $second_unit at (-999,-999)
20181027 08:50:02 error engine: failed to auto-store $second_unit at (-999,-999)
20181027 08:50:02 error engine: failed to auto-store $second_unit at (-999,-999)
20181027 08:50:02 error engine: failed to auto-store $unit at (0,0)
20181027 08:50:02 error engine: failed to auto-store $unit at (0,0)
20181027 08:50:02 error engine: failed to auto-store $unit at (0,0)
20181027 08:50:02 error engine: failed to auto-store $unit at (0,0)
20181027 08:50:02 error engine: failed to auto-store $unit at (0,0)
20181027 08:50:02 error engine: failed to auto-store $unit at (0,0)
`

[LotI2-Unimportant Revolution.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/2521902/LotI2-Unimportant.Revolution.gz)

**Comment by arobinson** [comment]
That fixed both the tile errors as well as the advancement errors. Thanks!
